//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GKCacheObject.h"

@class GKChallengeCacheObject, NSString;

@interface GKChallengeCompatibleBundleID : GKCacheObject
{
}

+ (id)entityName;
- (id)internalRepresentation;
- (void)updateWithServerRepresentation:(id)arg1;

// Remaining properties
@property(retain, nonatomic) NSString *bundleID; // @dynamic bundleID;
@property(retain, nonatomic) GKChallengeCacheObject *challenge; // @dynamic challenge;

@end

