//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GKFriendRequestBulletin.h"

@class NSString;

@interface GKFriendRequestCancelBulletin : GKFriendRequestBulletin
{
    NSString *_selfPlayerID;
}

+ (void)loadBulletinsForPushNotification:(id)arg1 withHandler:(CDUnknownBlockType)arg2;
@property(retain) NSString *selfPlayerID; // @synthesize selfPlayerID=_selfPlayerID;
- (id)description;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithPushNotification:(id)arg1;
- (void)removeAssociatedInvite;

@end

