//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GKFriendRequestBulletin.h"

@interface GKFriendRequestAcceptedBulletin : GKFriendRequestBulletin
{
}

+ (void)loadBulletinsForPushNotification:(id)arg1 withHandler:(CDUnknownBlockType)arg2;
- (id)description;
- (void)expireCaches;
- (void)assembleBulletin;
- (id)URLPathForFriend:(id)arg1;
- (id)initWithPushNotification:(id)arg1;
- (void)loadDataWithHandler:(CDUnknownBlockType)arg1;

@end

