//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GKDataReader.h"

@class GKDataTransport, NSSet, NSString;

@interface GKFriendRecommendationsNetworkReader : NSObject <GKDataReader>
{
    GKDataTransport *_transport;
    NSSet *_recentlyDisplayedPlayerIDs;
}

+ (id)readerWithDisplayedPlayerIDs:(id)arg1 transport:(id)arg2;
@property(retain, nonatomic) NSSet *recentlyDisplayedPlayerIDs; // @synthesize recentlyDisplayedPlayerIDs=_recentlyDisplayedPlayerIDs;
@property(retain, nonatomic) GKDataTransport *transport; // @synthesize transport=_transport;
- (void)readResources:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (id)friendRecommendationForRepresentation:(id)arg1;
- (id)requestBody;
- (id)poolName;
- (void)dealloc;
- (id)initWithDisplayedPlayerIDs:(id)arg1 transport:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

