//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSSet.h"

@interface NSSet (GKResource)
+ (id)_gkSetOfResourcesWithIDs:(id)arg1;
- (_Bool)_gkContainsInvalidResource;
- (_Bool)_gkContainsExpiredResource;
- (_Bool)_gkContainsInvalidOrExpiredResource;
- (id)_gkAllResourceIDs;
- (id)_gkAllRepresentedItems;
- (id)_gkInvalidOrExpiredResources;
- (id)_gkValidAndNonExpiredResources;
- (id)_gkInvalidResources;
- (id)_gkExpiredResources;
- (_Bool)_gkContainsObjectPassingPredicate:(CDUnknownBlockType)arg1;
- (id)_gkResourceWithID:(id)arg1;
- (id)_gkResourcesWithIDs:(id)arg1;
@end

