//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ActivityWebProcessController.h"
#import "FormAutoFiller.h"
#import "PageLoadTestWebProcessController.h"
#import "ReaderWebProcessControllerProtocol.h"
#import "RequestDesktopSiteWebProcessPlugInListener.h"
#import "WKWebProcessPlugInLoadDelegate.h"

@class FormMetadataController, NSDictionary, NSMutableSet, NSString, PageLoadTestMeasurementController, ReaderWebProcessPlugInPageController, SafariWebProcessPlugIn, WKWebProcessPlugInBrowserContextController, WKWebProcessPlugInFrame, WKWebProcessPlugInScriptWorld, WebProcessPlugInPageExtensionController, WebProcessPlugInPageSafeBrowsingController, _WKRemoteObjectInterface;

@interface WebProcessPlugInPageController : NSObject <ActivityWebProcessController, FormAutoFiller, PageLoadTestWebProcessController, ReaderWebProcessControllerProtocol, RequestDesktopSiteWebProcessPlugInListener, WKWebProcessPlugInLoadDelegate>
{
    WKWebProcessPlugInBrowserContextController *_webProcessPlugInContextController;
    struct unique_ptr<ReaderAvailabilityController, std::__1::default_delete<ReaderAvailabilityController>> _readerAvailabilityController;
    _WKRemoteObjectInterface *_availabilityControllerInterface;
    id <ReaderEventsListener> _readerActivityListenerProxy;
    ReaderWebProcessPlugInPageController *_readerPageController;
    long long _cachedReaderTopScrollOffset;
    NSDictionary *_initialScrollPositionAsDictionary;
    _WKRemoteObjectInterface *_pageLoadTestControllerInterface;
    PageLoadTestMeasurementController *_pageLoadTestMeasurementController;
    WebProcessPlugInPageExtensionController *_extensionController;
    _WKRemoteObjectInterface *_autoFillerInterface;
    _WKRemoteObjectInterface *_activityControllerInterface;
    id <ActivityJavaScriptObserver> _activityJSObserverProxy;
    WebProcessPlugInPageSafeBrowsingController *_safeBrowsingController;
    WKWebProcessPlugInScriptWorld *_isolatedWorld;
    id <AppBannerMetaTagContentObserver> _appBannerObserverProxy;
    unsigned long long _loadDeferringReasons;
    id <RequestDesktopSiteUIProcessListener> _requestDesktopSiteUIProcessListener;
    _WKRemoteObjectInterface *_requestDesktopSiteWebProcessPlugInListenerInterface;
    NSMutableSet *_domainsNeedingDesktopUserAgent;
    _Bool _readerShouldUseNarrowLayout;
    _Bool _viewingReadingListArchive;
    NSDictionary *_initalArticleScrollPositionAsDictionary;
    unsigned long long _initialReaderTextZoomIndex;
    FormMetadataController *_formMetadataController;
    SafariWebProcessPlugIn *_webProcessPlugin;
}

+ (id)pageControllerForBrowserContextController:(id)arg1;
@property(readonly, nonatomic) SafariWebProcessPlugIn *webProcessPlugin; // @synthesize webProcessPlugin=_webProcessPlugin;
@property(readonly, nonatomic) FormMetadataController *formMetadataController; // @synthesize formMetadataController=_formMetadataController;
@property(readonly, nonatomic, getter=isViewingReadingListArchive) _Bool viewingReadingListArchive; // @synthesize viewingReadingListArchive=_viewingReadingListArchive;
@property(readonly, nonatomic) _Bool readerShouldUseNarrowLayout; // @synthesize readerShouldUseNarrowLayout=_readerShouldUseNarrowLayout;
@property(readonly, nonatomic) unsigned long long initialReaderTextZoomIndex; // @synthesize initialReaderTextZoomIndex=_initialReaderTextZoomIndex;
@property(nonatomic) long long cachedReaderTopScrollOffset; // @synthesize cachedReaderTopScrollOffset=_cachedReaderTopScrollOffset;
@property(copy, nonatomic) NSDictionary *initalArticleScrollPositionAsDictionary; // @synthesize initalArticleScrollPositionAsDictionary=_initalArticleScrollPositionAsDictionary;
@property(retain, nonatomic) ReaderWebProcessPlugInPageController *readerPageController; // @synthesize readerPageController=_readerPageController;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)runJavaScriptForActivity:(id)arg1 withScript:(id)arg2 object:(id)arg3 invokeMethod:(id)arg4 replyIdentifier:(id)arg5;
- (id)activieJSObserverProxy;
- (void)resumeLoadingAfterSavingFormData;
- (void)clearAutoFillMetadata;
- (void)collectMetadataForTextField:(id)arg1 inFrame:(id)arg2 atURL:(id)arg3 replyIdentifier:(id)arg4;
- (void)collectFormMetadataForPrefillingAtURL:(id)arg1;
- (void)autoFillForm:(id)arg1 inFrame:(id)arg2 withGeneratedPassword:(id)arg3;
- (void)autoFillFormSynchronouslyInFrame:(id)arg1 withValues:(id)arg2;
- (void)autoFillFormAsynchronouslyInFrame:(id)arg1 withValues:(id)arg2 selectFieldAfterFilling:(id)arg3;
- (void)markURLAsNeedingDesktopUserAgent:(id)arg1;
- (id)webProcessPlugInBrowserContextController:(id)arg1 frame:(id)arg2 userAgentForURL:(id)arg3;
- (void)webProcessPlugInBrowserContextController:(id)arg1 globalObjectIsAvailableForFrame:(id)arg2 inScriptWorld:(id)arg3;
- (id)webProcessPlugInBrowserContextController:(id)arg1 frame:(id)arg2 willSendRequest:(id)arg3 redirectResponse:(id)arg4;
- (void)webProcessPlugInBrowserContextController:(id)arg1 didRemoveFrameFromHierarchy:(id)arg2;
- (void)webProcessPlugInBrowserContextController:(id)arg1 didFailLoadWithErrorForFrame:(id)arg2 error:(id)arg3;
- (void)webProcessPlugInBrowserContextController:(id)arg1 frame:(id)arg2 didFailLoadForResource:(unsigned long long)arg3 error:(id)arg4;
- (void)webProcessPlugInBrowserContextController:(id)arg1 frame:(id)arg2 didFinishLoadForResource:(unsigned long long)arg3;
- (void)webProcessPlugInBrowserContextController:(id)arg1 frame:(id)arg2 didInitiateLoadForResource:(unsigned long long)arg3 request:(id)arg4;
- (void)webProcessPlugInBrowserContextController:(id)arg1 didHandleOnloadEventsForFrame:(id)arg2;
- (void)webProcessPlugInBrowserContextController:(id)arg1 didFirstVisuallyNonEmptyLayoutForFrame:(id)arg2;
- (void)webProcessPlugInBrowserContextController:(id)arg1 renderingProgressDidChange:(unsigned long long)arg2;
- (void)webProcessPlugInBrowserContextController:(id)arg1 didFinishLoadForFrame:(id)arg2;
- (void)webProcessPlugInBrowserContextController:(id)arg1 didFinishDocumentLoadForFrame:(id)arg2;
- (void)webProcessPlugInBrowserContextController:(id)arg1 didSameDocumentNavigationForFrame:(id)arg2;
- (void)webProcessPlugInBrowserContextController:(id)arg1 didCommitLoadForFrame:(id)arg2;
- (void)webProcessPlugInBrowserContextController:(id)arg1 didStartProvisionalLoadForFrame:(id)arg2;
- (id)_searchForSmartAppBannerMetaContent;
- (id)_appBannerMetaElementInHeaderElement:(id)arg1;
- (id)_appBannerMetaTagObserverProxy;
- (void)_deferPageLoadingUntilSafeBrowsingCheckCompleteForFrame:(id)arg1;
- (void)_setupPageLoadTestController;
- (void)enablePageLoadMeasurementCollection;
- (void)collectReaderContentForMail;
- (void)didSetReaderTextZoomIndex:(unsigned long long)arg1;
- (void)collectReadingListItemInfoWithBookmarkID:(id)arg1;
- (void)decreaseReaderTextSize;
- (void)increaseReaderTextSize;
- (void)loadNewReaderArticle;
- (void)didCreateReaderPageContextHandle:(id)arg1;
- (void)prepareToTransitionToReader;
- (void)setReaderShouldUseNarrowLayout:(_Bool)arg1;
- (void)setReaderInitialTopScrollOffset:(long long)arg1 textZoomIndex:(unsigned long long)arg2 useNarrowLayout:(_Bool)arg3 isViewingArchive:(_Bool)arg4;
- (_Bool)isNetworkReachable;
@property(readonly) WKWebProcessPlugInFrame *mainFrame;
- (struct OpaqueJSValue *)originalArticleFinder;
- (void)_detectAvailabilityAfterDelay:(double)arg1 loadEvent:(int)arg2;
- (void)_clearReaderControllerInterface;
- (void)_setUpReaderControllerInterface;
- (void)didDetermineReaderAvailability:(_Bool)arg1;
- (void)_removeLoadDeferringReasons:(unsigned long long)arg1;
- (void)_addLoadDeferringReasons:(unsigned long long)arg1;
@property(readonly) WKWebProcessPlugInBrowserContextController *browserContextController;
- (void)willDestroyBrowserContextController:(id)arg1;
- (void)dealloc;
- (id)initWithPlugIn:(id)arg1 contextController:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

