//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIResponder.h"

#import "UIApplicationDelegate.h"

@class NSString, PKPassLibrary, UIWindow;

@interface PassbookUIServiceAppDelegate : UIResponder <UIApplicationDelegate>
{
    PKPassLibrary *_passLibrary;
}

@property(readonly, nonatomic) PKPassLibrary *passLibrary; // @synthesize passLibrary=_passLibrary;
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(retain, nonatomic) UIWindow *window;

@end

