_AXSetUIAXReportSenderErrorLoggerFunction
_AXSetValidationErrorLoggingFunction
_OBJC_CLASS_$_UIAccessibilitySafeCategory
_OBJC_METACLASS_$_UIAccessibilitySafeCategory
_UIAccessibilityInstallSafeCategories
_UIAccessibilityInstallSafeCategory
