_Java_sun_tracing_dtrace_JVM_activate0
_Java_sun_tracing_dtrace_JVM_defineClass0
_Java_sun_tracing_dtrace_JVM_dispose0
_Java_sun_tracing_dtrace_JVM_isEnabled0
_Java_sun_tracing_dtrace_JVM_isSupported0
_lookupJvmSymbols
