//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IDEAssistantWindowController.h"

#import "IDEContinuousIntegrationCreateEditBotWindowController.h"

@class NSMutableArray, NSString;

@interface XCSUICreateBotAssistantContextWindowController : IDEAssistantWindowController <IDEContinuousIntegrationCreateEditBotWindowController>
{
    CDUnknownBlockType _createBotCompletionBlockCopy;
    NSMutableArray *_completionPreprocessors;
    NSMutableArray *_completionPreprocessorExecutionStack;
}

@property(retain) NSMutableArray *completionPreprocessorExecutionStack; // @synthesize completionPreprocessorExecutionStack=_completionPreprocessorExecutionStack;
@property(retain) NSMutableArray *completionPreprocessors; // @synthesize completionPreprocessors=_completionPreprocessors;
- (void).cxx_destruct;
- (void)drainPreprocessorOrContinueWithSender:(id)arg1;
- (void)goNextOrFinish:(id)arg1;
- (void)addGoForwardPreprocessor:(CDUnknownBlockType)arg1;
- (BOOL)attemptRecoveryFromError:(id)arg1 optionIndex:(unsigned long long)arg2;
- (void)doneLoadingSourceControlBlueprint:(id)arg1;
- (void)beginSessionModalForWorkspaceTabController:(id)arg1 hostWindow:(id)arg2 editingBot:(id)arg3 withCompletionBlock:(CDUnknownBlockType)arg4;
- (void)beginSessionModalForWorkspaceTabController:(id)arg1 hostWindow:(id)arg2 editingBot:(id)arg3 editingMode:(long long)arg4 withCompletionBlock:(CDUnknownBlockType)arg5;
@property(readonly) CDUnknownBlockType completionBlock;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

