//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface _NSItemProviderTypeCoercion : NSObject
{
    id _value;
    Class _targetClass;
}

+ (id)coercionClassStringFromClass:(Class)arg1;
+ (SEL)selectorForCoercionFromValue:(id)arg1 toClass:(Class)arg2;
+ (id)typeCoercionForValue:(id)arg1 targetClass:(Class)arg2;
@property(copy, nonatomic) Class targetClass; // @synthesize targetClass=_targetClass;
@property(retain, nonatomic) id value; // @synthesize value=_value;
- (id)_NSItemProviderTypeCoercion_coercedNSFileWrapperValueFromNSDataValue:(id)arg1 error:(id *)arg2;
- (id)_NSItemProviderTypeCoercion_coercedNSFileWrapperValueFromNSURLValue:(id)arg1 error:(id *)arg2;
- (id)_NSItemProviderTypeCoercion_coercedNSDataValueFromNSURLValue:(id)arg1 error:(id *)arg2;
- (id)coerceValueAndReturnError:(id *)arg1;
- (_Bool)shouldCoerceForCoding;
- (void)dealloc;

@end

