//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol XRDispatchData <NSObject>
+ (int)dataType;
@property BOOL modified;
@property BOOL selected;
- (void)setSelectedTimeRange:(struct XRTimeRange)arg1;
- (void)transferEventAtTimestamp:(unsigned long long)arg1;
@end

