//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSArray.h"

@interface NSArray (PrivateAPI)
- (id)allItemsWithKeyPath:(id)arg1 equalTo:(id)arg2;
- (id)allItemsWithKey:(id)arg1 equalTo:(id)arg2;
- (id)itemWithKey:(id)arg1 equalTo:(id)arg2;
@end

