//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "XRCodeProvider.h"

@class NSMutableArray, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString, XRArchitecture, XRCodeManager, XRDevice;

@interface PFTPersistentSymbols : NSObject <NSCoding, XRCodeProvider>
{
    XRDevice *_device;
    int _pid;
    BOOL _symbolicatorAttemptMade;
    struct __CFDictionary *_cfSymbolDataForAddress;
    struct __CFDictionary *_ownerDataForRealSymbolOwners;
    struct __CFDictionary *_symbolDataForRealSymbols;
    NSMutableDictionary *_symbolDataForNameAndPath;
    NSMutableArray *_duplicateSymbols;
    struct __CFDictionary *_threadIdentifierToNameDict;
    NSObject<OS_dispatch_queue> *_symToAddrQueue;
    struct _opaque_pthread_mutex_t _threadNamingLock;
    struct _CSTypeRef _symbolicator;
    struct _CSTypeRef _kernelSymbolicator;
    struct __CFData *_signature;
    struct __CFData *_kernelSignature;
    NSMutableArray *_usedThreadNames;
    BOOL _compatabilityCastDown;
    BOOL _unarchived;
    XRCodeManager *_sourceManager;
    NSString *_execName;
    XRArchitecture *_deviceArch;
}

+ (void)_notifyClientsSymbolicatorCreated:(id)arg1;
+ (id)_findSourcePathForProposedSearchPath:(id)arg1;
+ (void)doneWithSymbolStore:(id)arg1;
+ (id)sharedSymbolStoreForPid:(int)arg1 forDevice:(id)arg2;
+ (id)sharedSymbolStoreForPid:(int)arg1 forDevice:(id)arg2 signature:(struct __CFData *)arg3 kernelSignature:(struct __CFData *)arg4;
+ (void)initialize;
- (id)_shadowOwnerForCSOwner:(struct _CSTypeRef)arg1;
- (id)_shadowSymbolForCSSymbol:(struct _CSTypeRef)arg1 isConcrete:(BOOL)arg2;
- (id)_shadowSymbolForAddress:(unsigned long long)arg1 inSymbolicator:(struct _CSTypeRef)arg2 atTime:(unsigned long long)arg3;
- (id)_iterateStackFramesForAddress:(unsigned long long)arg1 inSymbolOwner:(struct _CSTypeRef)arg2 atTime:(unsigned long long)arg3;
- (id)_emptySymbolDataWithName:(id)arg1 withAddress:(unsigned long long)arg2 withSymbolOwner:(struct _CSTypeRef)arg3;
- (void)_makeSymbolicatorAttempt;
- (id)getOwnerDataByUUID:(const CDStruct_e6eac3cb *)arg1 faultingSymbolOwner:(struct _CSTypeRef)arg2;
- (BOOL)getSourceDeclarationPath:(id *)arg1 andLineNumber:(struct _NSRange *)arg2 forIvar:(id)arg3 ofClass:(id)arg4;
- (id)inDwarf:(void *)arg1 compileUnit:(id)arg2 findHeaderForiVar:(id)arg3 inClass:(id)arg4;
- (void)printDIEObject:(void *)arg1 object:(id)arg2;
- (BOOL)getSymbol:(id *)arg1 forAddress:(unsigned long long)arg2 inKernel:(BOOL)arg3;
- (BOOL)forEachSourceMappingInSymbol:(id)arg1 forAddresses:(id)arg2 executeBlock:(CDUnknownBlockType)arg3;
- (BOOL)getSourceCode:(id *)arg1 andPath:(id *)arg2 forSymbol:(id)arg3 error:(id *)arg4;
- (BOOL)getInstructions:(id *)arg1 cpu:(int *)arg2 cpuSubtype:(int *)arg3 mode:(unsigned long long *)arg4 forSymbol:(id)arg5 error:(id *)arg6;
- (id)codeForSymbol:(id)arg1;
- (id)sourceCodeManager;
- (id)execNameForProcess;
- (int)pid;
- (id)deviceArchitecture;
- (id)architecture;
- (id)threads;
- (id)threadNameForThread:(unsigned long long)arg1 pid:(int)arg2;
- (id)learnThreadNameForThread:(unsigned long long)arg1 backtrace:(id)arg2;
- (id)symbolDataForName:(const char *)arg1;
- (id)ownerDataForAddress:(unsigned long long)arg1;
- (id)symbolDataWithName:(id)arg1 inSymbolOwner:(id)arg2;
- (id)symbolDataForAddress:(unsigned long long)arg1 isKernelSymbol:(BOOL)arg2;
- (id)symbolDataForAddress:(unsigned long long)arg1 isKernelSymbol:(BOOL)arg2 allowFault:(BOOL)arg3;
- (struct _CSTypeRef)kernelSymbolicator;
- (struct _CSTypeRef)csSymbolicator;
- (BOOL)symbolsCurrentlyAvailable;
- (void)replaceSourcePath:(id)arg1 withPath:(id)arg2;
- (void)resymbolicate;
- (void)saveFakeSymbolWithName:(id)arg1 address:(unsigned long long)arg2;
- (void)learnSymbolsForBacktrace:(id)arg1;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (void)_addLookupAddressesFromShadowSymbol:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initWithDevice:(id)arg1 signature:(struct __CFData *)arg2 kernelSignature:(struct __CFData *)arg3 pid:(int)arg4;
- (void)_setupSynchronization;

@end

