//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary;

@interface XRActionContextManager : NSObject
{
    NSMutableArray *_actions;
    NSMutableDictionary *_classTargetedActions;
    NSMutableDictionary *_protocolTargetActions;
}

+ (void)dispatchActionWithIdentifier:(id)arg1 forArray:(id)arg2 forDocument:(id)arg3;
+ (id)sharedContextManager;
+ (void)initializePlugIns:(id)arg1;
- (void).cxx_destruct;
- (id)actionWithIdentifier:(id)arg1;
- (id)actionsForClassName:(id)arg1;
- (id)actionsForPrototype:(id)arg1;
- (void)addAction:(id)arg1;
- (id)init;

@end

