//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XRSpace.h"

@class XRSpaceDataToken;

@interface XRAnalysisCoreSpace : XRSpace
{
    XRSpaceDataToken *_pathManTok;
    XRSpaceDataToken *_coresByRunNumberTok;
    XRSpaceDataToken *_coreForNextRunTok;
}

- (void).cxx_destruct;
- (id)spaceName;
- (BOOL)isSerial;
- (id)pathManager;
- (id)coreForNextRun;
- (void)engageCoreForNextRunWithRunNumber:(long long)arg1;
- (id)coreForRunNumber:(long long)arg1;
- (id)initWithSourceURL:(id)arg1;

@end

