//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@interface XRArchitecture : NSObject <NSCoding, NSCopying>
{
    int _cpuType;
    int _cpuSubtype;
}

+ (id)currentArchitecture;
+ (id)architectureWithCSArchitecture:(struct _CSArchitecture)arg1;
+ (void)initialize;
@property(nonatomic) int cpuSubtype; // @synthesize cpuSubtype=_cpuSubtype;
@property(nonatomic) int cpuType; // @synthesize cpuType=_cpuType;
- (BOOL)isLittleEndian;
- (BOOL)isBigEndian;
- (BOOL)is64Bit;
- (BOOL)is32Bit;
- (struct _CSArchitecture)csArchitecture;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCpuType:(int)arg1 cpuSubtype:(int)arg2;

@end

