//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSMenuItem.h"

@interface XRExpandableMenuItem : NSMenuItem
{
    CDUnknownBlockType _clientAction;
    BOOL _trackingInside;
}

+ (id)itemWithTitle:(id)arg1 indentationLevel:(long long)arg2 controlSize:(unsigned long long)arg3 action:(CDUnknownBlockType)arg4;
- (void).cxx_destruct;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
- (void)expandItem:(id)arg1;
- (id)initWithTitle:(id)arg1 indentationLevel:(long long)arg2 controlSize:(unsigned long long)arg3 action:(CDUnknownBlockType)arg4;

@end

