//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSString;

@interface XRFormulaError : NSObject <NSCoding>
{
    NSString *_error;
    long long _character;
}

@property(readonly, nonatomic) long long character; // @synthesize character=_character;
@property(readonly, retain, nonatomic) NSString *error; // @synthesize error=_error;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)description;
- (id)initWithErrorString:(id)arg1 character:(long long)arg2;

@end

