//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSBox.h"

@interface XRLabeledView : NSBox
{
}

- (void)setTitle:(id)arg1;
- (void)setContentView:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)setFrameSize:(struct CGSize)arg1;
- (struct CGRect)titleRect;

@end

