//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@interface XRRecordModeOptions : NSObject <NSCoding, NSCopying>
{
    int _recordMode;
    unsigned long long _recordModeMask;
    double _startDelay;
    double _timeLimit;
    double _windowLimit;
    unsigned long long _sampleLimit;
    BOOL _supportsStartDelay;
    BOOL _supportsTimeLimit;
    BOOL _supportsSampleLimit;
    BOOL _supportsWindowed;
    BOOL _startDelayed;
    BOOL _windowed;
    BOOL _timeLimited;
    BOOL _sampleLimited;
}

@property(readonly) unsigned long long recordModeMask; // @synthesize recordModeMask=_recordModeMask;
@property BOOL supportsSampleLimit; // @synthesize supportsSampleLimit=_supportsSampleLimit;
@property BOOL supportsTimeLimit; // @synthesize supportsTimeLimit=_supportsTimeLimit;
@property BOOL supportsStartDelay; // @synthesize supportsStartDelay=_supportsStartDelay;
@property BOOL supportsWindowed; // @synthesize supportsWindowed=_supportsWindowed;
@property double unrealizedWindowLimit; // @synthesize unrealizedWindowLimit=_windowLimit;
@property unsigned long long unrealizedSampleLimit; // @synthesize unrealizedSampleLimit=_sampleLimit;
@property double unrealizedTimeLimit; // @synthesize unrealizedTimeLimit=_timeLimit;
@property double unrealizedStartDelay; // @synthesize unrealizedStartDelay=_startDelay;
@property BOOL startDelayed; // @synthesize startDelayed=_startDelayed;
@property BOOL timeLimited; // @synthesize timeLimited=_timeLimited;
@property BOOL sampleLimited; // @synthesize sampleLimited=_sampleLimited;
@property BOOL windowed; // @synthesize windowed=_windowed;
@property(readonly) unsigned long long sampleLimit;
@property(readonly) double windowLimit;
@property(readonly) double timeLimit;
@property(readonly) double startDelay;
- (int)recordMode;
- (void)setRecordMode:(int)arg1;
- (void)mergeWithRecordOptions:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)setDataDictionary:(id)arg1;
- (id)dataDictionary;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithDictionary:(id)arg1;
- (id)initWithRecordMask:(unsigned long long)arg1;

@end

