//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSMutableArray, NSMutableDictionary;

@interface XRRunListData : NSObject <NSCoding>
{
    NSMutableArray *_runNumbers;
    NSMutableDictionary *_runData;
    NSMutableArray *_inMemoryProcessCache;
}

+ (void)initialize;
- (struct CGRect)rectOfProperty:(id)arg1 forRunNumber:(unsigned long long)arg2;
- (void)setRect:(struct CGRect)arg1 ofProperty:(id)arg2 forRunNumber:(unsigned long long)arg3;
- (double)heightOfItem:(id)arg1 withDefaultHeight:(double)arg2 forRunNumber:(unsigned long long)arg3;
- (void)setHeight:(double)arg1 ofItem:(id)arg2 forRunNumber:(unsigned long long)arg3;
- (unsigned long long)threadIDForSerialNumber:(unsigned int)arg1 forRunNumber:(unsigned long long)arg2;
- (unsigned int)threadSerialNumberForID:(unsigned long long)arg1 forRunNumber:(unsigned long long)arg2;
- (id)processWithPid:(int)arg1 forRunNumber:(unsigned long long)arg2;
- (id)processDataWithPid:(int)arg1 forRunNumber:(unsigned long long)arg2;
- (id)processDatasForRunNumber:(unsigned long long)arg1;
- (void)addProcess:(id)arg1 forRunNumber:(unsigned long long)arg2;
- (id)logEventsForRunNumber:(unsigned long long)arg1;
- (void)addProcessLogEvents:(id)arg1 forRunNumber:(unsigned long long)arg2;
- (id)recordModeOptionsForRunNumber:(unsigned long long)arg1;
- (void)addRecordModeOptions:(id)arg1 forRunNumber:(unsigned long long)arg2;
- (id)flagListForRunNumber:(unsigned long long)arg1;
- (void)removeFlag:(id)arg1 forRunNumber:(unsigned long long)arg2;
- (void)addFlag:(id)arg1 forRunNumber:(unsigned long long)arg2;
- (id)startStringForRunNumber:(unsigned long long)arg1;
- (id)startDateForRunNumber:(unsigned long long)arg1;
- (unsigned long long)startTimeForRunNumber:(unsigned long long)arg1;
- (void)addStartTime:(unsigned long long)arg1 forRunNumber:(unsigned long long)arg2;
- (BOOL)hasRunningTimeForRunNumber:(unsigned long long)arg1;
- (unsigned long long)runningTimeForRunNumber:(unsigned long long)arg1;
- (void)addRunningTime:(unsigned long long)arg1 forRunNumber:(unsigned long long)arg2;
- (id)stringArchitectureForRunNumber:(unsigned long long)arg1;
- (id)architectureForRunNumber:(unsigned long long)arg1;
- (void)addArchitectureData:(id)arg1 forRunNumber:(unsigned long long)arg2;
- (id)stringOSVersionInfoForRunNumber:(unsigned long long)arg1;
- (id)osVersionForRunNumber:(unsigned long long)arg1;
- (void)addOSVersionData:(id)arg1 forRunNumber:(unsigned long long)arg2;
- (id)allCoresDataForRunNumber:(unsigned long long)arg1;
- (void)addAllCoresData:(id)arg1 forRunNumber:(unsigned long long)arg2;
- (int)numberOfCpusDataForRunNumber:(unsigned long long)arg1;
- (void)addNumberOfCpusData:(int)arg1 forRunNumber:(unsigned long long)arg2;
- (id)targetDataForRunNumber:(unsigned long long)arg1;
- (void)addTargetData:(id)arg1 forRunNumber:(unsigned long long)arg2;
- (id)commentForRunNumber:(unsigned long long)arg1;
- (void)addComment:(id)arg1 forRunNumber:(unsigned long long)arg2;
- (id)iconNamed:(id)arg1 fullSize:(BOOL)arg2;
- (void)addIcon:(id)arg1 name:(id)arg2 fullSize:(BOOL)arg3;
- (id)dataForRunNumber:(unsigned long long)arg1;
- (id)dataForAllRuns;
- (id)runData;
- (id)runNumbers;
- (unsigned long long)runNumberForIndex:(unsigned long long)arg1;
- (unsigned long long)indexOfRunNumber:(unsigned long long)arg1;
- (void)removeRunNumber:(unsigned long long)arg1;
- (void)addRunNumber:(unsigned long long)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)init;

@end

