//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsPlugIn/XRBezierPath.h>

@interface XRStatePath : XRBezierPath
{
    long long _state;
    unsigned long long _pathType;
}

- (void)transformUsingAffineTransform:(id)arg1;
- (long long)compare:(id)arg1;
- (id)initWithState:(long long)arg1 pathType:(unsigned long long)arg2;

@end

