//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "XRProcessTargetedObject.h"

@class NSString, NSWindow, PFTProcess, XRDevice;

@interface XRTemplateChooserTargetedObject : NSObject <XRProcessTargetedObject>
{
    int _defaultTargetType;
    NSWindow *_window;
    XRDevice *_targetDevice;
    PFTProcess *_defaultProcess;
}

@property(retain, nonatomic) PFTProcess *defaultProcess; // @synthesize defaultProcess=_defaultProcess;
@property(retain, nonatomic) XRDevice *targetDevice; // @synthesize targetDevice=_targetDevice;
@property(retain, nonatomic) NSWindow *window; // @synthesize window=_window;
- (void).cxx_destruct;
- (id)mainWindow;
- (id)currentTargetDevice;
- (id)currentTargetProcess;
- (BOOL)supportsTargetType:(int)arg1;
- (void)setTargetsDevice:(id)arg1;
- (void)setTargetsLaunchedProcess:(id)arg1;
- (void)setTargetsExistingProcess:(id)arg1;
- (int)defaultTargetTypeForChooser;
- (void)setTargetsAllProcesses;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

