//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSMutableArray, NSString;

@interface XRThreadGroup : NSObject <NSCoding>
{
    NSString *_threadGroupName;
    int _type;
    NSMutableArray *_threads;
}

+ (void)initialize;
- (void).cxx_destruct;
- (id)description;
- (id)name;
- (id)threadWithIdentifier:(unsigned long long)arg1;
- (id)threads;
- (BOOL)removeThread:(id)arg1;
- (BOOL)addThread:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initThreadGroupName:(id)arg1 type:(int)arg2;

@end

