
/Applications/Xcode.app//Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos/libswiftCoreImage.dylib (for architecture armv7):
__TFE9CoreImageCSo8CIFilterCfMS0_Ft4nameGSQSS_8elementsGSaTPSo9NSCopying_PSs9AnyObject____S0_
__TFE9CoreImageCSo8CIFiltercfMS0_Ft4nameGSQSS_8elementsGSaTPSo9NSCopying_PSs9AnyObject____S0_
__swift_FORCE_LOAD_$_swiftCoreImage

/Applications/Xcode.app//Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos/libswiftCoreImage.dylib (for architecture arm64):
__TFE9CoreImageCSo8CIFilterCfMS0_Ft4nameGSQSS_8elementsGSaTPSo9NSCopying_PSs9AnyObject____S0_
__TFE9CoreImageCSo8CIFiltercfMS0_Ft4nameGSQSS_8elementsGSaTPSo9NSCopying_PSs9AnyObject____S0_
__swift_FORCE_LOAD_$_swiftCoreImage
