//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSCustomImageRep.h"

@interface MyCustomImageRep : NSCustomImageRep
{
    long long code;
}

- (void)setCode:(long long)arg1;
- (long long)code;

@end

