
/Applications/Xcode.app//Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/libexslt.0.dylib (for architecture armv7):
_exsltCommonRegister
_exsltDateRegister
_exsltDateXpathCtxtRegister
_exsltDynRegister
_exsltFuncRegister
_exsltLibexsltVersion
_exsltLibraryVersion
_exsltLibxmlVersion
_exsltLibxsltVersion
_exsltMathRegister
_exsltMathXpathCtxtRegister
_exsltRegisterAll
_exsltSaxonRegister
_exsltSetsRegister
_exsltSetsXpathCtxtRegister
_exsltStrRegister
_exsltStrXpathCtxtRegister

/Applications/Xcode.app//Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/libexslt.0.dylib (for architecture armv7s):
_exsltCommonRegister
_exsltDateRegister
_exsltDateXpathCtxtRegister
_exsltDynRegister
_exsltFuncRegister
_exsltLibexsltVersion
_exsltLibraryVersion
_exsltLibxmlVersion
_exsltLibxsltVersion
_exsltMathRegister
_exsltMathXpathCtxtRegister
_exsltRegisterAll
_exsltSaxonRegister
_exsltSetsRegister
_exsltSetsXpathCtxtRegister
_exsltStrRegister
_exsltStrXpathCtxtRegister

/Applications/Xcode.app//Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/libexslt.0.dylib (for architecture arm64):
_exsltCommonRegister
_exsltDateRegister
_exsltDateXpathCtxtRegister
_exsltDynRegister
_exsltFuncRegister
_exsltLibexsltVersion
_exsltLibraryVersion
_exsltLibxmlVersion
_exsltLibxsltVersion
_exsltMathRegister
_exsltMathXpathCtxtRegister
_exsltRegisterAll
_exsltSaxonRegister
_exsltSetsRegister
_exsltSetsXpathCtxtRegister
_exsltStrRegister
_exsltStrXpathCtxtRegister
