
/Applications/Xcode.app//Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/libipconfig.dylib (for architecture armv7):
_IPConfigurationServiceCopyInformation
_IPConfigurationServiceCreate
_IPConfigurationServiceGetNotificationKey
_IPConfigurationServiceRefreshConfiguration
_ipconfigVersionNumber
_ipconfigVersionString
_kIPConfigurationServiceOptionIPv6Entity
_kIPConfigurationServiceOptionMTU
_kIPConfigurationServiceOptionPerformNUD
_my_CFStringAppendBytesAsHex
_my_CFStringCreateWithIPAddress
_my_CFStringCreateWithIPv6Address
_my_CFStringToCString

/Applications/Xcode.app//Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/libipconfig.dylib (for architecture armv7s):
_IPConfigurationServiceCopyInformation
_IPConfigurationServiceCreate
_IPConfigurationServiceGetNotificationKey
_IPConfigurationServiceRefreshConfiguration
_ipconfigVersionNumber
_ipconfigVersionString
_kIPConfigurationServiceOptionIPv6Entity
_kIPConfigurationServiceOptionMTU
_kIPConfigurationServiceOptionPerformNUD
_my_CFStringAppendBytesAsHex
_my_CFStringCreateWithIPAddress
_my_CFStringCreateWithIPv6Address
_my_CFStringToCString

/Applications/Xcode.app//Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/libipconfig.dylib (for architecture arm64):
_IPConfigurationServiceCopyInformation
_IPConfigurationServiceCreate
_IPConfigurationServiceGetNotificationKey
_IPConfigurationServiceRefreshConfiguration
_ipconfigVersionNumber
_ipconfigVersionString
_kIPConfigurationServiceOptionIPv6Entity
_kIPConfigurationServiceOptionMTU
_kIPConfigurationServiceOptionPerformNUD
_my_CFStringAppendBytesAsHex
_my_CFStringCreateWithIPAddress
_my_CFStringCreateWithIPv6Address
_my_CFStringToCString
