//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBCodable.h"

#import "NSCopying.h"

@class NSString;

@interface AWDNetworkUsage : PBCodable <NSCopying>
{
    unsigned long long _cellIn;
    unsigned long long _cellOut;
    unsigned long long _wifiIn;
    unsigned long long _wifiOut;
    NSString *_bundleName;
    unsigned int _numConnections;
    struct {
        unsigned int cellIn:1;
        unsigned int cellOut:1;
        unsigned int wifiIn:1;
        unsigned int wifiOut:1;
        unsigned int numConnections:1;
    } _has;
}

@property(nonatomic) unsigned int numConnections; // @synthesize numConnections=_numConnections;
@property(nonatomic) unsigned long long cellOut; // @synthesize cellOut=_cellOut;
@property(nonatomic) unsigned long long cellIn; // @synthesize cellIn=_cellIn;
@property(nonatomic) unsigned long long wifiOut; // @synthesize wifiOut=_wifiOut;
@property(nonatomic) unsigned long long wifiIn; // @synthesize wifiIn=_wifiIn;
@property(retain, nonatomic) NSString *bundleName; // @synthesize bundleName=_bundleName;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(nonatomic) _Bool hasNumConnections;
@property(nonatomic) _Bool hasCellOut;
@property(nonatomic) _Bool hasCellIn;
@property(nonatomic) _Bool hasWifiOut;
@property(nonatomic) _Bool hasWifiIn;
@property(readonly, nonatomic) _Bool hasBundleName;
- (void)dealloc;

@end

