//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBCodable.h"

#import "NSCopying.h"

@interface AWDPowerWifiMetrics : PBCodable <NSCopying>
{
    unsigned long long _timestamp;
    unsigned int _wifi2P4GHzRxDuration;
    unsigned int _wifi2P4GHzTxDuration;
    unsigned int _wifi5GHz20MHzRxDuration;
    unsigned int _wifi5GHz20MHzTxDuration;
    unsigned int _wifi5GHz40MHzRxDuration;
    unsigned int _wifi5GHz40MHzTxDuration;
    unsigned int _wifi5GHz80MHzRxDuration;
    unsigned int _wifi5GHz80MHzTxDuration;
    unsigned int _wifiFRTSDuration;
    unsigned int _wifiHsicActiveDuration;
    unsigned int _wifiPcieL0Duration;
    unsigned int _wifiPcieL10Duration;
    unsigned int _wifiPcieL11Duration;
    unsigned int _wifiPcieL12Duration;
    unsigned int _wifiScanDuration;
    unsigned int _wifiSleepDuration;
    unsigned int _wifiTotalDuration;
    unsigned int _wifiTotalPowerMicroWatt;
    struct {
        unsigned int timestamp:1;
        unsigned int wifi2P4GHzRxDuration:1;
        unsigned int wifi2P4GHzTxDuration:1;
        unsigned int wifi5GHz20MHzRxDuration:1;
        unsigned int wifi5GHz20MHzTxDuration:1;
        unsigned int wifi5GHz40MHzRxDuration:1;
        unsigned int wifi5GHz40MHzTxDuration:1;
        unsigned int wifi5GHz80MHzRxDuration:1;
        unsigned int wifi5GHz80MHzTxDuration:1;
        unsigned int wifiFRTSDuration:1;
        unsigned int wifiHsicActiveDuration:1;
        unsigned int wifiPcieL0Duration:1;
        unsigned int wifiPcieL10Duration:1;
        unsigned int wifiPcieL11Duration:1;
        unsigned int wifiPcieL12Duration:1;
        unsigned int wifiScanDuration:1;
        unsigned int wifiSleepDuration:1;
        unsigned int wifiTotalDuration:1;
        unsigned int wifiTotalPowerMicroWatt:1;
    } _has;
}

@property(nonatomic) unsigned int wifiHsicActiveDuration; // @synthesize wifiHsicActiveDuration=_wifiHsicActiveDuration;
@property(nonatomic) unsigned int wifiTotalPowerMicroWatt; // @synthesize wifiTotalPowerMicroWatt=_wifiTotalPowerMicroWatt;
@property(nonatomic) unsigned int wifiPcieL12Duration; // @synthesize wifiPcieL12Duration=_wifiPcieL12Duration;
@property(nonatomic) unsigned int wifiPcieL11Duration; // @synthesize wifiPcieL11Duration=_wifiPcieL11Duration;
@property(nonatomic) unsigned int wifiPcieL10Duration; // @synthesize wifiPcieL10Duration=_wifiPcieL10Duration;
@property(nonatomic) unsigned int wifiPcieL0Duration; // @synthesize wifiPcieL0Duration=_wifiPcieL0Duration;
@property(nonatomic) unsigned int wifiScanDuration; // @synthesize wifiScanDuration=_wifiScanDuration;
@property(nonatomic) unsigned int wifiFRTSDuration; // @synthesize wifiFRTSDuration=_wifiFRTSDuration;
@property(nonatomic) unsigned int wifiTotalDuration; // @synthesize wifiTotalDuration=_wifiTotalDuration;
@property(nonatomic) unsigned int wifiSleepDuration; // @synthesize wifiSleepDuration=_wifiSleepDuration;
@property(nonatomic) unsigned int wifi5GHz80MHzRxDuration; // @synthesize wifi5GHz80MHzRxDuration=_wifi5GHz80MHzRxDuration;
@property(nonatomic) unsigned int wifi5GHz40MHzRxDuration; // @synthesize wifi5GHz40MHzRxDuration=_wifi5GHz40MHzRxDuration;
@property(nonatomic) unsigned int wifi5GHz20MHzRxDuration; // @synthesize wifi5GHz20MHzRxDuration=_wifi5GHz20MHzRxDuration;
@property(nonatomic) unsigned int wifi5GHz80MHzTxDuration; // @synthesize wifi5GHz80MHzTxDuration=_wifi5GHz80MHzTxDuration;
@property(nonatomic) unsigned int wifi5GHz40MHzTxDuration; // @synthesize wifi5GHz40MHzTxDuration=_wifi5GHz40MHzTxDuration;
@property(nonatomic) unsigned int wifi5GHz20MHzTxDuration; // @synthesize wifi5GHz20MHzTxDuration=_wifi5GHz20MHzTxDuration;
@property(nonatomic) unsigned int wifi2P4GHzRxDuration; // @synthesize wifi2P4GHzRxDuration=_wifi2P4GHzRxDuration;
@property(nonatomic) unsigned int wifi2P4GHzTxDuration; // @synthesize wifi2P4GHzTxDuration=_wifi2P4GHzTxDuration;
@property(nonatomic) unsigned long long timestamp; // @synthesize timestamp=_timestamp;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(nonatomic) _Bool hasWifiHsicActiveDuration;
@property(nonatomic) _Bool hasWifiTotalPowerMicroWatt;
@property(nonatomic) _Bool hasWifiPcieL12Duration;
@property(nonatomic) _Bool hasWifiPcieL11Duration;
@property(nonatomic) _Bool hasWifiPcieL10Duration;
@property(nonatomic) _Bool hasWifiPcieL0Duration;
@property(nonatomic) _Bool hasWifiScanDuration;
@property(nonatomic) _Bool hasWifiFRTSDuration;
@property(nonatomic) _Bool hasWifiTotalDuration;
@property(nonatomic) _Bool hasWifiSleepDuration;
@property(nonatomic) _Bool hasWifi5GHz80MHzRxDuration;
@property(nonatomic) _Bool hasWifi5GHz40MHzRxDuration;
@property(nonatomic) _Bool hasWifi5GHz20MHzRxDuration;
@property(nonatomic) _Bool hasWifi5GHz80MHzTxDuration;
@property(nonatomic) _Bool hasWifi5GHz40MHzTxDuration;
@property(nonatomic) _Bool hasWifi5GHz20MHzTxDuration;
@property(nonatomic) _Bool hasWifi2P4GHzRxDuration;
@property(nonatomic) _Bool hasWifi2P4GHzTxDuration;
@property(nonatomic) _Bool hasTimestamp;

@end

