//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBCodable.h"

#import "NSCopying.h"

@class NSString;

@interface AWDWiProxLeSendDataResult : PBCodable <NSCopying>
{
    unsigned long long _timestamp;
    unsigned int _dataLength;
    NSString *_peerId;
    unsigned int _result;
    NSString *_resultString;
    NSString *_sessionId;
    struct {
        unsigned int timestamp:1;
        unsigned int dataLength:1;
        unsigned int result:1;
    } _has;
}

@property(nonatomic) unsigned int result; // @synthesize result=_result;
@property(retain, nonatomic) NSString *resultString; // @synthesize resultString=_resultString;
@property(nonatomic) unsigned int dataLength; // @synthesize dataLength=_dataLength;
@property(retain, nonatomic) NSString *peerId; // @synthesize peerId=_peerId;
@property(retain, nonatomic) NSString *sessionId; // @synthesize sessionId=_sessionId;
@property(nonatomic) unsigned long long timestamp; // @synthesize timestamp=_timestamp;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(nonatomic) _Bool hasResult;
@property(readonly, nonatomic) _Bool hasResultString;
@property(nonatomic) _Bool hasDataLength;
@property(readonly, nonatomic) _Bool hasPeerId;
@property(readonly, nonatomic) _Bool hasSessionId;
@property(nonatomic) _Bool hasTimestamp;
- (void)dealloc;

@end

