//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBCodable.h"

#import "NSCopying.h"

@interface AWDWiFiMetricCustomNetworkSetting : PBCodable <NSCopying>
{
    unsigned long long _timestamp;
    unsigned int _autoProxySetCount;
    unsigned int _bootpSetCount;
    unsigned int _customNetworkCount;
    unsigned int _dhcpSetCount;
    unsigned int _manualProxySetCount;
    unsigned int _staticSetCount;
    unsigned int _totalNetworkCount;
    struct {
        unsigned int timestamp:1;
        unsigned int autoProxySetCount:1;
        unsigned int bootpSetCount:1;
        unsigned int customNetworkCount:1;
        unsigned int dhcpSetCount:1;
        unsigned int manualProxySetCount:1;
        unsigned int staticSetCount:1;
        unsigned int totalNetworkCount:1;
    } _has;
}

@property(nonatomic) unsigned int autoProxySetCount; // @synthesize autoProxySetCount=_autoProxySetCount;
@property(nonatomic) unsigned int manualProxySetCount; // @synthesize manualProxySetCount=_manualProxySetCount;
@property(nonatomic) unsigned int staticSetCount; // @synthesize staticSetCount=_staticSetCount;
@property(nonatomic) unsigned int bootpSetCount; // @synthesize bootpSetCount=_bootpSetCount;
@property(nonatomic) unsigned int dhcpSetCount; // @synthesize dhcpSetCount=_dhcpSetCount;
@property(nonatomic) unsigned int totalNetworkCount; // @synthesize totalNetworkCount=_totalNetworkCount;
@property(nonatomic) unsigned int customNetworkCount; // @synthesize customNetworkCount=_customNetworkCount;
@property(nonatomic) unsigned long long timestamp; // @synthesize timestamp=_timestamp;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(nonatomic) _Bool hasAutoProxySetCount;
@property(nonatomic) _Bool hasManualProxySetCount;
@property(nonatomic) _Bool hasStaticSetCount;
@property(nonatomic) _Bool hasBootpSetCount;
@property(nonatomic) _Bool hasDhcpSetCount;
@property(nonatomic) _Bool hasTotalNetworkCount;
@property(nonatomic) _Bool hasCustomNetworkCount;
@property(nonatomic) _Bool hasTimestamp;

@end

