_DVTDeveloperModeHelperVersionNumber
_DVTDeveloperModeHelperVersionString
_OBJC_CLASS_$_DVTDeveloperModeAlertHelper
_OBJC_CLASS_$_DVTDeveloperModeHelper
_OBJC_METACLASS_$_DVTDeveloperModeAlertHelper
_OBJC_METACLASS_$_DVTDeveloperModeHelper
