//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class DVTTextDocumentLocation;

@protocol DVTSourceLanguageServiceSymbolLookup
- (void)findIndexSymbolAtLocation:(DVTTextDocumentLocation *)arg1 completionBlock:(void (^)(IDEIndexSymbol *))arg2;
@end

