_OBJC_CLASS_$_MZRegularExpression
_OBJC_IVAR_$_MZRegularExpression._expression
_OBJC_IVAR_$_MZRegularExpression._opaque1
_OBJC_IVAR_$_MZRegularExpression._options
_OBJC_METACLASS_$_MZRegularExpression
