
/Applications/Xcode.app//Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/libH5Dynamic.dylib (for architecture armv7):
_h5_init_info_init
_h5_system_protocol_close
_h5_system_protocol_configure_log_size
_h5_system_protocol_enable
_h5_system_protocol_enter_low_power
_h5_system_protocol_free
_h5_system_protocol_get_fatal_error_string
_h5_system_protocol_get_max_payload
_h5_system_protocol_has_fatal_error_occurred
_h5_system_protocol_init
_h5_system_protocol_open
_h5_system_protocol_open_info_init
_h5_system_protocol_snapshot
_h5_system_protocol_write

/Applications/Xcode.app//Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/libH5Dynamic.dylib (for architecture armv7s):
_h5_init_info_init
_h5_system_protocol_close
_h5_system_protocol_configure_log_size
_h5_system_protocol_enable
_h5_system_protocol_enter_low_power
_h5_system_protocol_free
_h5_system_protocol_get_fatal_error_string
_h5_system_protocol_get_max_payload
_h5_system_protocol_has_fatal_error_occurred
_h5_system_protocol_init
_h5_system_protocol_open
_h5_system_protocol_open_info_init
_h5_system_protocol_snapshot
_h5_system_protocol_write

/Applications/Xcode.app//Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/libH5Dynamic.dylib (for architecture arm64):
_h5_init_info_init
_h5_system_protocol_close
_h5_system_protocol_configure_log_size
_h5_system_protocol_enable
_h5_system_protocol_enter_low_power
_h5_system_protocol_free
_h5_system_protocol_get_fatal_error_string
_h5_system_protocol_get_max_payload
_h5_system_protocol_has_fatal_error_occurred
_h5_system_protocol_init
_h5_system_protocol_open
_h5_system_protocol_open_info_init
_h5_system_protocol_snapshot
_h5_system_protocol_write
