//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PLPhotosApplication.h"

@interface PLPhotosApplication (Testing)
- (void)_runImageLoadTestWithSelector:(SEL)arg1 resultIsRetained:(_Bool)arg2;
- (void)runLoadFullScreenImagesTest:(id)arg1;
- (void)runLoadLowResolutionImagesTest:(id)arg1;
- (void)runLoadIndexSheetImagesTest:(id)arg1;
- (void)_navigateToZoomLevelForCurrentTest:(CDUnknownBlockType)arg1;
- (void)_navigateToAlbumListForCurrentTest:(CDUnknownBlockType)arg1;
- (void)_navigateToAlbumForCurrentTest:(CDUnknownBlockType)arg1;
- (void)_navigateToAssetForCurrentTest:(CDUnknownBlockType)arg1;
- (struct NSObject *)_libraryAlbum;
- (id)_tabbedLibraryViewController;
- (void)runSwitchTabTest:(id)arg1;
- (void)runLoadFullScreenSharingTest:(id)arg1;
- (void)runActivityFeedRotationTest:(id)arg1;
- (void)runPhotosTabRotationTest:(id)arg1;
- (void)_runRotationTest;
- (void)runZoomLevelTest:(id)arg1;
- (void)runSelectPhotosTest:(id)arg1;
- (void)runSelectAlbumsTest:(id)arg1;
- (void)runScrubberPerfTest:(id)arg1;
- (void)runBrowserPageTest:(id)arg1;
- (void)runScrollFullScreenSharingTest:(id)arg1;
- (void)runScrollFullScreenSharingIncrementalTest:(id)arg1;
- (void)runScrollActivityFeedTest:(id)arg1;
- (void)runScrollAlbumListTest:(id)arg1;
- (void)runScrollPhotoLibraryTest:(id)arg1;
- (void)runScrollAlbumTest:(id)arg1;
- (int)_scrollAxisForTestWithOptions:(id)arg1;
- (int)_scrollTestDelta:(id)arg1 options:(id)arg2;
- (int)_scrollTestLength:(id)arg1 options:(id)arg2;
- (void)failedCurrentTest;
- (void)finishedCurrentTest;
- (void)startedCurrentTest;
- (_Bool)runTest:(id)arg1 options:(id)arg2;
@end

