//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IBAbstractMessageChannelInterfaceBuilderToolManager.h"

@interface IBCocoaToolManager : IBAbstractMessageChannelInterfaceBuilderToolManager
{
}

+ (id)sharedInstance;
- (void)enumerateToolsWithBlock:(CDUnknownBlockType)arg1;
- (id)attachToToolForTargetRuntime:(id)arg1 isForLiveViews:(BOOL)arg2 scaleFactor:(id)arg3 queue:(id)arg4 assertOnFailureToAttach:(BOOL)arg5 assertOnPostLaunchRequestFailures:(BOOL)arg6 error:(id *)arg7;
- (Class)messageChannelProxyClass;
- (id)taskForAttachingToTargetRuntime:(id)arg1 isForLiveViews:(BOOL)arg2 scaleFactor:(id)arg3;

@end

