//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <SceneKit/_SCNExportOperation.h>

__attribute__((visibility("hidden")))
@interface SCNWebGLExportOperation : _SCNExportOperation
{
}

- (void)main;
- (id)initWithScene:(id)arg1 size:(struct CGSize)arg2 attributes:(id)arg3 outputURL:(id)arg4;

@end

