_Java_sun_jvm_hotspot_debugger_bsd_BsdDebuggerLocal_attach0__I
_Java_sun_jvm_hotspot_debugger_bsd_BsdDebuggerLocal_detach0
_Java_sun_jvm_hotspot_debugger_bsd_BsdDebuggerLocal_getThreadIntegerRegisterSet0
_Java_sun_jvm_hotspot_debugger_bsd_BsdDebuggerLocal_init0
_Java_sun_jvm_hotspot_debugger_bsd_BsdDebuggerLocal_lookupByName0
_Java_sun_jvm_hotspot_debugger_bsd_BsdDebuggerLocal_readBytesFromProcess0
_Java_sun_jvm_hotspot_debugger_macosx_MacOSXDebuggerLocal_translateTID0
_debug
