//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IDEQuickHelpDataContext.h"

@class DVTSourceCodeLanguage, IDEIndexSymbol, NSString, NSXMLElement;

@interface IDEQuickHelpDataContextDefault : NSObject <IDEQuickHelpDataContext>
{
    IDEIndexSymbol *_indexSymbol;
}

+ (id)fixedUpSymbolForDocLookup:(id)arg1;
@property(readonly, nonatomic) IDEIndexSymbol *indexSymbol; // @synthesize indexSymbol=_indexSymbol;
- (void).cxx_destruct;
- (void)enumerateRelatedDeclarationsUsingBlock:(CDUnknownBlockType)arg1;
- (void)enumerateOverriddenSymbolResolutionsUsingBlock:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) DVTSourceCodeLanguage *preferredLanguage;
@property(readonly, nonatomic) NSString *preferredUsr;
@property(readonly, nonatomic) NSXMLElement *documentationMarkup;
@property(readonly, nonatomic) NSXMLElement *declarationSymbolMarkup;
- (id)initWithIDEIndexSymbol:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

