//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class HFFileReference, HFProgressTracker, NSMutableArray;

@interface HFByteSliceFileOperationContext : NSObject
{
    unsigned long long softMaxAllocatedMemory;
    unsigned long long totalAllocatedMemory;
    HFFileReference *file;
    HFProgressTracker *progressTracker;
    NSMutableArray *queue;
}

- (unsigned long long)suggestedAllocationLengthForMinimum:(unsigned long long)arg1 maximum:(unsigned long long)arg2;
- (void)freeMemory:(void *)arg1 ofLength:(unsigned long long)arg2;
- (void *)allocateMemoryOfLength:(unsigned long long)arg1;

@end

