//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DBGDataType.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface DBGLLDBDataType : DBGDataType
{
    struct SBType _lldbType;
    NSString *_pointeeTypeName;
    NSString *_displayTypeName;
    BOOL _isPointer;
}

@property(retain) NSString *pointeeTypeName; // @synthesize pointeeTypeName=_pointeeTypeName;
- (id).cxx_construct;
- (void).cxx_destruct;
- (BOOL)isUnknownType;
- (BOOL)isPointer;
- (id)displayTypeName;
- (id)initWithTypename:(id)arg1 withType:(struct SBType)arg2;

@end

