//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MZMenuManager.h"

@class NSMutableDictionary;

@interface ITunesMenuManager : MZMenuManager
{
    NSMutableDictionary *_cachedMenuItems;
}

- (BOOL)canAddMenuItemWithDictionary:(id)arg1;
- (id)addMenuItem:(id)arg1 target:(id)arg2 selector:(SEL)arg3 keyEquivalent:(id)arg4 dictionary:(id)arg5;
- (void)cacheMenuItem:(id)arg1 contentType:(id)arg2;
- (id)loadMenuItems;
- (void)unloadMenuItems;
- (void)dealloc;

@end

