//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MZAbstractWorker.h"

#import "MZThroughputWorker.h"

@class AssetElement, ITunesPackage, MZFileCopyOperation, NSAlert, NSString;

@interface PackageAssetControllerAddAssetWorker : MZAbstractWorker <MZThroughputWorker>
{
    unsigned long long _operation;
    ITunesPackage *_package;
    NSString *_sourcePath;
    NSString *_destinationPath;
    AssetElement *_element;
    MZFileCopyOperation *_copy;
    NSString *_addedAssetName;
    NSAlert *_alert;
    BOOL _active;
    BOOL _run;
    unsigned long long _size;
}

- (unsigned long long)completed;
- (unsigned long long)size;
- (double)percentComplete;
- (void)cancel;
- (void)run;
- (id)addedAssetName;
- (id)alert;
- (id)modelElement;
- (void)dealloc;
- (id)element;
- (void)setOperation:(unsigned long long)arg1;
- (void)setSourcePath:(id)arg1;
- (id)sourcePath;
- (id)initWithPackage:(id)arg1 operation:(unsigned long long)arg2 sourcePath:(id)arg3 destinationPath:(id)arg4 element:(id)arg5;

@end

