//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ProductIntervalElement.h"

@interface ProductIntervalElement (ITunesProducerExtensions)
+ (BOOL)isValueMacOSAppType:(id)arg1;
+ (BOOL)isValueIOSAppType:(id)arg1;
+ (id)macWholesaleTierDTOWithValue:(id)arg1 iapType:(id)arg2;
+ (id)iosWholesaleTierDTOWithValue:(id)arg1 iapType:(id)arg2;
- (id)longWholesalePriceTier;
- (id)softwareInAppPurchaseElement;
- (id)softwareProductElement;
- (BOOL)isMacOSAppType;
- (BOOL)isIOSAppType;
- (void)setAppType:(id)arg1;
- (id)appType;
- (id)endDateDisplayString;
- (id)startDateDisplayString;
- (void)setLongWholesalePriceTier:(id)arg1 iapType:(id)arg2;
- (id)longWholesalePriceTierWithIapType:(id)arg1;
- (id)wholesalePriceTierDTOWithIapType:(id)arg1;
- (id)wholesaleTierDTOWithValue:(id)arg1 iapType:(id)arg2;
@end

