//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString, RNGDocument;

@interface RNGDocumentVerifier : NSObject
{
    NSString *_schema;
    RNGDocument *_schemaDocument;
    NSArray *_mappings;
    NSString *_localizationTable;
}

+ (id)covertPlistToMappings:(id)arg1;
+ (id)defaultMappingDocument;
+ (void)initialize;
- (id)description;
- (id)elementsWithIdentifier:(id)arg1;
- (id)verifyWithDocument:(id)arg1 identifier:(id)arg2 delegate:(id)arg3 error:(id *)arg4;
- (id)verifyWithDocument:(id)arg1 delegate:(id)arg2 error:(id *)arg3;
- (id)verifyWithDocument:(id)arg1 mappings:(id)arg2 delegate:(id)arg3 error:(id *)arg4;
- (id)verifyWithDocument:(id)arg1 mapping:(id)arg2 delegate:(id)arg3 error:(id *)arg4;
- (id)verifyWithNode:(id)arg1 mapping:(id)arg2 delegate:(id)arg3 error:(id *)arg4;
- (id)verifyDefine:(id)arg1 againstNodes:(id)arg2 mapping:(id)arg3 delegate:(id)arg4 error:(id *)arg5;
- (id)convertErrors:(id)arg1 define:(id)arg2 node:(id)arg3 mapping:(id)arg4 content:(id)arg5 delegate:(id)arg6;
- (id)mappings;
- (void)dealloc;
- (id)initWithMappings:(id)arg1 schema:(id)arg2 error:(id *)arg3;
- (void)setLocalizationTableWithDocumentName:(id)arg1;
- (id)initWithMappingDocument:(id)arg1 schema:(id)arg2 error:(id *)arg3;
- (id)initWithDefaultMappings:(id *)arg1 schema:(id)arg2;
- (id)initializeMappings;

@end

