//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTableView.h"

@class MZLiveSearchField, SearchResultsController;

@interface SearchResultsTableView : NSTableView
{
    MZLiveSearchField *_searchField;
    SearchResultsController *_searchResultsController;
    long long _startingRowSelection;
}

@property(nonatomic) long long startingRowSelection; // @synthesize startingRowSelection=_startingRowSelection;
@property SearchResultsController *searchResultsController; // @synthesize searchResultsController=_searchResultsController;
@property MZLiveSearchField *searchField; // @synthesize searchField=_searchField;
- (void)copy:(id)arg1;
- (void)scrollRowToVisible:(long long)arg1;
- (void)insertNewline:(id)arg1;
- (void)returnToSearchField;
- (void)keyUp:(id)arg1;
- (void)keyDown:(id)arg1;

@end

