//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber, NSString;

@protocol ActivityWebProcessController <NSObject>
- (void)runJavaScriptForActivity:(NSString *)arg1 withScript:(NSString *)arg2 object:(NSString *)arg3 invokeMethod:(NSString *)arg4 replyIdentifier:(NSNumber *)arg5;
@end

