//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BrowserPanel.h"
#import "RotatablePopoverControllerDelegate.h"

@class BrowserICSPreviewPanelNavController, EKICSPreviewController, NSString, OpenInOtherAppActivityViewController, RotatablePopoverController;

@interface BrowserICSPreviewPanel : NSObject <RotatablePopoverControllerDelegate, BrowserPanel>
{
    OpenInOtherAppActivityViewController *_activityViewController;
    BrowserICSPreviewPanelNavController *_wrappingNavController;
    RotatablePopoverController *_activityPopover;
    EKICSPreviewController *_icsController;
    NSString *_filePath;
}

- (void).cxx_destruct;
- (void)popoverControllerDidDismissPopover:(id)arg1;
- (_Bool)shouldHideOnSuspend;
- (int)pausesPages;
- (_Bool)ignoresPrivateBrowsingStyle;
- (int)panelType;
- (id)viewController;
- (void)_done:(id)arg1;
- (void)_openInOtherAppsButtonPressed:(id)arg1;
- (id)activityViewController;
- (void)dealloc;
- (id)initWithFilePath:(id)arg1 sourceURL:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

