//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CloudTabItemView, CloudTabTable, WBSCloudTab, WBSCloudTabDevice;

@protocol CloudTabTableDelegate <NSObject>
- (void)cloudTabTable:(CloudTabTable *)arg1 didFinishEditingTabItemView:(CloudTabItemView *)arg2;
- (void)cloudTabTable:(CloudTabTable *)arg1 didStartEditingTabItemView:(CloudTabItemView *)arg2;
- (void)cloudTabTable:(CloudTabTable *)arg1 closeCloudTab:(WBSCloudTab *)arg2 onDevice:(WBSCloudTabDevice *)arg3;
- (void)cloudTabTable:(CloudTabTable *)arg1 didSelectCloudTab:(WBSCloudTab *)arg2;
@end

