//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WBSCompletionListItem.h"

@class CompletionList, NSString, UITableViewCell, UIView;

@protocol CompletionItem <WBSCompletionListItem>
- (void)auditAcceptedCompletionWithRank:(unsigned long long)arg1;
- (void)acceptCompletionWithActionHandler:(id <CompletionItemActionHandler>)arg1;
- (void)configureCompletionTableViewCell:(UITableViewCell *)arg1 forCompletionList:(CompletionList *)arg2;
- (UITableViewCell *)completionTableViewCell;
- (NSString *)completionTableViewCellReuseIdentifier;

@optional
@property(readonly, nonatomic) NSString *completionTableHeaderViewReuseIdentifier;
- (void)configureCompletionTableHeaderView:(UIView *)arg1 forCompletionList:(CompletionList *)arg2;
- (UIView *)completionTableHeaderView;
- (double)completionTableViewCellCustomHeightForCompletionList:(CompletionList *)arg1;
@end

