//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SafariExtensionEventsListener.h"

@class NSMutableDictionary, NSString, NSTimer, TabDocument, _WKRemoteObjectInterface;

@interface SafariSharingExtensionController : NSObject <SafariExtensionEventsListener>
{
    TabDocument *_tabDocument;
    id <SharingExtensionWebProcessController> _extensionControllerProxy;
    _WKRemoteObjectInterface *_extensionEventListenerInterface;
    NSMutableDictionary *_replyIdentifierToCompletionMap;
    NSTimer *_expirationTimer;
}

- (void).cxx_destruct;
- (void)didEvaluateJavaScriptForSharingExtensionWithResult:(id)arg1 replyIdentifier:(id)arg2;
- (void)_evaluateJavaScriptFinishedWithResult:(id)arg1 replyIdentifier:(id)arg2 error:(id)arg3;
- (void)finalizeJavaScriptForSharingExtension:(id)arg1 arguments:(id)arg2;
- (void)runJavaScriptForSharingExtension:(id)arg1 javaScript:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)_extensionControllerProxy;
- (void)_clearExtensionEventsListenerInterface;
- (void)_setUpExtensionEventsListenerInterface;
- (void)_expirationTimerFired:(id)arg1;
- (void)_startExpirationTimerForReplyIdentifier:(id)arg1;
- (void)_invalidateExpirationTimer;
- (void)dealloc;
- (id)initWithTabDoucment:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

