//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@protocol UIWebFindOnPageHighlighterDelegate <NSObject>

@optional
- (void)findOnPageHighlighter:(id <UIWebFindOnPageHighlighter>)arg1 hasPartialSearchResults:(NSArray *)arg2;
- (void)findOnPageHighlighterSearchDidFinish:(id <UIWebFindOnPageHighlighter>)arg1;
- (void)findOnPageHighlighterSearchLimitHit:(id <UIWebFindOnPageHighlighter>)arg1;
- (void)findOnPageHighlighterSearchWasCancelled:(id <UIWebFindOnPageHighlighter>)arg1;
- (void)findOnPageHighlighterSearchDidTimeOut:(id <UIWebFindOnPageHighlighter>)arg1;
- (void)findOnPageHighlighterSearchDidBegin:(id <UIWebFindOnPageHighlighter>)arg1;
- (void)findOnPageHighlighterDidHighlightMatch:(id <UIWebFindOnPageHighlighter>)arg1;
@end

