//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UniversalSearchSimpleResultTableViewCell.h"

@class EvenlyDistributedImagesView, NSArray, NSLayoutConstraint, NSString, UIImage, UIImageView, UILabel, UniversalSearchITunesResultRatingView;

@interface UniversalSearchITunesResultTableViewCell : UniversalSearchSimpleResultTableViewCell
{
    UniversalSearchITunesResultRatingView *_ratingView;
    EvenlyDistributedImagesView *_moreGlyphsView;
    UILabel *_rottenTomatoesTextLabel;
    UIImageView *_rottenTomatoesGlyphImageView;
    NSLayoutConstraint *_detailLabelBaselineToMoreGlyphsViewBottomConstraint;
    NSLayoutConstraint *_moreGlyphsViewBottomToRatingViewBottomConstraint;
    NSLayoutConstraint *_ratingViewBottomToContentViewBottomConstraint;
    NSArray *_rottenTomatoesGlyphPlacementConstraints;
    NSString *_rottenTomatoesText;
    _Bool _rottenTomatoesTextOnOwnLine;
    UIImage *_rottenTomatoesGlyph;
}

- (void).cxx_destruct;
- (id)templateTextAndImageColor;
- (double)_distanceFromMoreGlyphsViewBottomToRatingViewBottom;
- (double)distanceFromDetailLabelBaselineToMoreGlyphsViewBottom;
- (void)setRottenTomatoesContentFromResult:(id)arg1 searchSession:(id)arg2;
- (void)setMoreGlyphs:(id)arg1;
@property(nonatomic) double rating;
- (id)detailLabelBottomPlacementConstraints;
- (void)updateBottomPlacementConstraintsForDetailLabel;
- (void)configureAdditionalGlyphsWithSearchResult:(id)arg1 searchSession:(id)arg2;
- (void)configureIconImagesWithSearchResult:(id)arg1 searchSession:(id)arg2;
- (void)configureWithSearchResult:(id)arg1 searchSession:(id)arg2;
- (void)initializeLayoutContraints;

@end

