//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XRSamplerDataReceiver.h"

@class DTXChannel;

@interface XRRemoteSamplerDataReceiver : XRSamplerDataReceiver
{
    DTXChannel *_channel;
    unsigned long long _serviceVersion;
    unsigned long long _remoteReferenceTime;
    int _targetPid;
}

+ (id)channelForDevice:(id)arg1 version:(unsigned long long *)arg2;
- (void).cxx_destruct;
- (void)_dispatchStopCollection;
- (void)_dispatchStartCollection;
- (void)configureChannelForCollection:(id)arg1;
- (void)processMessage:(id)arg1;
- (void)stopRecordingPid:(int)arg1;
- (BOOL)recordPid:(int)arg1;
- (void)dealloc;
- (void)handleMessage:(id)arg1;
- (id)initWithRun:(id)arg1 device:(id)arg2 startDate:(id)arg3 sampleRate:(unsigned long long)arg4 updateRate:(unsigned long long)arg5 options:(int)arg6 pmiEventMnemonic:(id)arg7 pmiEventThreshold:(unsigned long long)arg8 pmiCounterName:(id)arg9;

@end

