//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DVTHashTable, NSLock, NSMutableDictionary;

@interface IBAbstractMessageChannelInterfaceBuilderToolManager : NSObject
{
    NSMutableDictionary *_startUpObservers;
    long long _observerTokenCounter;
    NSLock *_lock;
    DVTHashTable *_tools;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)enumerateToolsWithBlock:(CDUnknownBlockType)arg1;
- (id)registerStartUpObserver:(CDUnknownBlockType)arg1;
- (id)attachToToolForTargetRuntime:(id)arg1 isForLiveViews:(BOOL)arg2 scaleFactor:(id)arg3 queue:(id)arg4 assertOnFailureToAttach:(BOOL)arg5 assertOnPostLaunchRequestFailures:(BOOL)arg6 error:(id *)arg7;
- (Class)messageChannelProxyClass;
- (id)taskForAttachingToTargetRuntime:(id)arg1 isForLiveViews:(BOOL)arg2 scaleFactor:(id)arg3;
- (id)init;

@end

