//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DVTFlatSegmentedControlCell.h"

@interface IBAccessorizedScrollViewSegmentedCell : DVTFlatSegmentedControlCell
{
}

- (void)drawWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (struct CGRect)boundsOfSegment:(unsigned long long)arg1;
- (double)_menuDelayTimeForSegment:(long long)arg1;

@end

