//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IBCLIOptionIndex, NSArray, NSDictionary, NSMutableArray, NSMutableDictionary, NSString;

@interface IBArgumentsContainer : NSObject
{
    NSMutableArray *_inputDocumentPaths;
    NSArray *_rawBuildEnvironment;
    NSMutableDictionary *_buildEnvironment;
    BOOL _shouldPrintUsage;
    BOOL _buildEnvironmentFromClient;
    long long _outputFormat;
}

+ (id)containerFromArguments:(id)arg1 collectingErrors:(id)arg2;
@property(copy, nonatomic) NSDictionary *buildEnvironment; // @synthesize buildEnvironment=_buildEnvironment;
@property(nonatomic) BOOL buildEnvironmentFromClient; // @synthesize buildEnvironmentFromClient=_buildEnvironmentFromClient;
@property(copy, nonatomic) NSArray *inputDocumentPaths; // @synthesize inputDocumentPaths=_inputDocumentPaths;
@property long long outputFormat; // @synthesize outputFormat=_outputFormat;
@property BOOL shouldPrintUsage; // @synthesize shouldPrintUsage=_shouldPrintUsage;
- (void).cxx_destruct;
- (BOOL)longArgumentIsPresentOnCommandLine:(id)arg1;
- (void)validateAfterInterpretingOptionsCollectingErrors:(id)arg1;
@property(readonly) IBCLIOptionIndex *optionIndex;
- (long long)outputFormatArgumentCode;
- (void)interpretOption:(CDStruct_96d6799e)arg1 optionalParameter:(id)arg2 collectingErrors:(id)arg3;
- (BOOL)isMissingRequiredInputDocument;
- (BOOL)supportsMultipleInputDocuments;
- (void)setRawEnvironment:(id)arg1;
- (id)collectionOptionsThatRequireInputDocuments;
- (id)objectOptionsThatRequireInputDocuments;
- (id)booleanOptionsThatRequireInputDocuments;
- (void)appendDocumentInputPaths:(id)arg1;
@property(copy, nonatomic) NSString *inputDocumentPath;
- (id)init;

@end

