//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IBDocument;

@interface IBDocumentVerifier : NSObject
{
    IBDocument *_document;
}

+ (BOOL)shouldNeverUseAutoincrementingIDs;
+ (id)verifiedDanglingSubviewParentClassWhitelist;
@property(readonly) IBDocument *document; // @synthesize document=_document;
- (void).cxx_destruct;
- (void)verifyViewsHaveCorrectFrames;
- (id)verifyRootObjectRootsAllObjects;
- (void)verifyXcode5ContentViews;
- (void)verifyIDGenerationStrategy;
- (void)verifyTranslatesAutoresizingMaskIntoConstraints;
- (void)verifyConstraints;
- (void)verifyDevelopmentTarget;
- (id)verifyNoDanglingSubviews;
- (id)verifyViewCCRHPriorities;
- (id)verificationMessageForResolvingConflictBetweenConnections:(id)arg1 byKeepingConnection:(id)arg2;
- (id)connectionsGroupedByExclusitivityHints;
- (id)verifyExclusiveConnections;
- (id)verifyIllegalEditorSizes;
- (id)verify;
- (void)verificationDidFinish;
- (id)performVerification;
- (id)initWithDocument:(id)arg1;

@end

