//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IBLiveViewsBundle;

@protocol IBLiveViewsBundleObserverEnvironment <NSObject>
- (void)liveViewsBundle:(IBLiveViewsBundle *)arg1 dispatchDidFinishBuildingForObservers:(id <IBCollection>)arg2 withBlock:(void (^)(void))arg3;
@end

