//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <IDEInterfaceBuilderKit/IBTaskBasedParser.h>

@interface IBNibExtractorParser : IBTaskBasedParser
{
}

- (id)processParserOutput:(id)arg1 fromFile:(id)arg2 errors:(id *)arg3;
- (id)parserLaunchPath;

@end

