//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <IDEInterfaceBuilderKit/IBAbstractRelationshipInfo.h>

@class NSString;

@interface IBToManyOutletInfo : IBAbstractRelationshipInfo
{
    NSString *_collectionClassName;
}

+ (id)instantiateWithDocumentUnarchiver:(id)arg1 relationshipName:(id)arg2 andCandidateClassName:(id)arg3;
+ (id)relationshipInfoWithName:(id)arg1 andCandidateClassName:(id)arg2;
+ (id)relationshipInfoWithName:(id)arg1 candidateClassName:(id)arg2 andCollectionClassName:(id)arg3;
- (void).cxx_destruct;
- (id)description;
- (BOOL)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)relationshipInfoWithCandidateClassName:(id)arg1;
- (id)relationshipInfoWithName:(id)arg1;
@property(readonly) NSString *collectionClassName;
- (long long)relationshipType;
- (long long)compareForArchiving:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithName:(id)arg1 candidateClassName:(id)arg2 andCollectionClassName:(id)arg3;

@end

