//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IDEInspectorViewController.h"

@interface IDEPlaygroundDocumentInspector : IDEInspectorViewController
{
}

- (id)toolTipContentFromKeyPath:(id)arg1 titleAttribute:(id)arg2 placeholderAttribute:(id)arg3;

@end

