//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IDEDiagnosticActivityLogMessage.h"

@interface IDESwiftDiagnosticActivityLogMessage : IDEDiagnosticActivityLogMessage
{
    int _diagnosticSeverity;
    unsigned long long _diagnosticLevel;
}

@property(readonly) unsigned long long diagnosticLevel; // @synthesize diagnosticLevel=_diagnosticLevel;
- (id)description;
- (id)initWithDiagnostic:(CDStruct_3b0d17db)arg1 documentURL:(id)arg2;
- (int)diagnosticSeverity;

@end

