//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSTimer;

@interface CellularDataAvailabilityMonitor : NSObject
{
    struct __CTServerConnection *_serverConnection;
    NSTimer *_assumeCellularDataTimer;
    _Bool _cellularDataAvailable;
    id <CellularDataAvailabilityMonitorDelegate> _delegate;
}

@property(readonly, nonatomic, getter=isCellularDataAvailable) _Bool cellularDataAvailable; // @synthesize cellularDataAvailable=_cellularDataAvailable;
@property(nonatomic) __weak id <CellularDataAvailabilityMonitorDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_updateCellularDataAvailabilityFromStatusDictionary:(id)arg1;
- (void)_updateCellularDataAvailability;
- (void)_clearAssumeCellularDataTimer;
- (void)_cellularDataAvailabilityDidTimeout;
- (void)dealloc;
- (id)init;

@end

