//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CellularDataAvailabilityMonitorDelegate.h"
#import "DataActivationNoticeViewControllerDelegate.h"
#import "DataActivationWebViewControllerDelegate.h"
#import "RemoteUIControllerDelegate.h"
#import "UIApplicationDelegate.h"
#import "UINavigationControllerDelegate.h"

@class CellularDataAvailabilityMonitor, DataActivationViewController, DataActivationWebViewController, NSMutableArray, NSNumber, NSString, NSURLRequest, RemoteUIController, UIViewController, UIWindow;

@interface DataActivationAppDelegate : NSObject <CellularDataAvailabilityMonitorDelegate, DataActivationNoticeViewControllerDelegate, DataActivationWebViewControllerDelegate, UINavigationControllerDelegate, UIApplicationDelegate, RemoteUIControllerDelegate>
{
    UIViewController *_rootViewController;
    DataActivationViewController *_dataActivationViewController;
    RemoteUIController *_remoteUIController;
    DataActivationWebViewController *_dataActivationWebViewController;
    UIWindow *_mainWindow;
    NSURLRequest *_launchURLRequest;
    int _proxyType;
    NSString *_proxyHost;
    NSNumber *_proxyPort;
    NSString *_currentConnectionType;
    NSMutableArray *_nextConnectionTypes;
    CellularDataAvailabilityMonitor *_cellularDataAvailabilityMonitor;
    _Bool _startRequestWhenCellularDataBecomesAvailable;
    _Bool _preferProvisioningInterface;
    _Bool _shouldPostDeviceParameters;
    _Bool _isDataActivationViewVisible;
    int _pendingErrorAlertType;
}

- (void).cxx_destruct;
- (void)dataActivationNoticeViewControllerDidPressDoneButton:(id)arg1;
- (void)_cancelButtonAction;
- (void)_showCancelButton:(_Bool)arg1 forViewController:(id)arg2 animated:(_Bool)arg3;
- (_Bool)_shouldShowBackButtonForViewController:(id)arg1;
- (void)navigationController:(id)arg1 willShowViewController:(id)arg2 animated:(_Bool)arg3;
- (id)navigationController:(id)arg1 animationControllerForOperation:(long long)arg2 fromViewController:(id)arg3 toViewController:(id)arg4;
- (void)remoteUIController:(id)arg1 willLoadRequest:(id)arg2;
- (void)_presentAlertController;
- (id)_alertActionWithTitle:(id)arg1 style:(long long)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)_showLocationUnavailableAlert;
- (void)_showLocationServiceUnauthorizedAlert;
- (void)_showLocationDisabledAlert;
- (void)_showConnectionErrorAlert;
- (void)dataActivationWebViewController:(id)arg1 didFailLoadWithError:(id)arg2;
- (id)dataActivationWebViewController:(id)arg1 connectionPropertiesForRequest:(id)arg2;
- (id)dataActivationWebViewController:(id)arg1 proxySettingsForRequest:(id)arg2;
- (void)dataActivationWebViewControllerDidFinish:(id)arg1;
- (void)dataActivationWebViewController:(id)arg1 didPurchasePlanSuccessfullyWithIccid:(id)arg2;
- (_Bool)dataActivationWebViewControllerShouldAllowPlanPurchaseWithIccid:(id)arg1;
- (void)dataActivationWebViewControllerAccoutDidUpdateSuccessfully:(id)arg1;
- (id)_nextAvailableConnectionType;
- (id)_preferredConnectionTypes;
- (void)cellularDataAvailabilityMonitorCellularDataDidBecomeAvailable:(id)arg1;
- (void)_beginDismissingSheet;
- (void)dataActivationViewDidAppear;
- (void)endRemoteSheet;
- (_Bool)_WWANActivationRequired;
- (void)_loadLaunchURLRequestWithNextConnectionTypeOrShowErrorAlert;
- (void)applicationWillTerminate:(id)arg1;
- (void)_pushDataActivationWebViewControllerWithURLString:(id)arg1 animated:(_Bool)arg2;
- (void)_pushDataActivationWebViewControllerWithURLRequest:(id)arg1 animated:(_Bool)arg2;
- (void)_destroyCurrentDataActivationWebViewController;
- (void)_setupNewDataActivationWebViewController;
- (void)applicationDidFinishLaunching:(id)arg1;
- (void)_showRootViewController;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(retain, nonatomic) UIWindow *window;

@end

