
/Applications/Xcode.app//Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/libAXSpeechManager.dylib (for architecture armv7):
_AXLanguageCanonicalFormToGeneralLanguage
_AXSpeechTransformText
_AXSpeechTransformTextWithLanguage
_OBJC_CLASS_$_AVAlexSpeechSynthesisVoice
_OBJC_CLASS_$_AXEmojiUtilities
_OBJC_CLASS_$_AXSpeechAction
_OBJC_CLASS_$_AXSpeechManager
_OBJC_METACLASS_$_AVAlexSpeechSynthesisVoice
_OBJC_METACLASS_$_AXEmojiUtilities
_OBJC_METACLASS_$_AXSpeechAction
_OBJC_METACLASS_$_AXSpeechManager
_VOTBundle
__AXSpeechReplaceEmoticons
_isSpeakableEmojiString
_kAXPauseStringExtraLong
_kAXPauseStringMedium
_kAXPauseStringMediumLong
_kAXPauseStringShort
_kAXPauseStringSuperExtraLong

/Applications/Xcode.app//Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/libAXSpeechManager.dylib (for architecture armv7s):
_AXLanguageCanonicalFormToGeneralLanguage
_AXSpeechTransformText
_AXSpeechTransformTextWithLanguage
_OBJC_CLASS_$_AVAlexSpeechSynthesisVoice
_OBJC_CLASS_$_AXEmojiUtilities
_OBJC_CLASS_$_AXSpeechAction
_OBJC_CLASS_$_AXSpeechManager
_OBJC_METACLASS_$_AVAlexSpeechSynthesisVoice
_OBJC_METACLASS_$_AXEmojiUtilities
_OBJC_METACLASS_$_AXSpeechAction
_OBJC_METACLASS_$_AXSpeechManager
_VOTBundle
__AXSpeechReplaceEmoticons
_isSpeakableEmojiString
_kAXPauseStringExtraLong
_kAXPauseStringMedium
_kAXPauseStringMediumLong
_kAXPauseStringShort
_kAXPauseStringSuperExtraLong

/Applications/Xcode.app//Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/libAXSpeechManager.dylib (for architecture arm64):
_AXLanguageCanonicalFormToGeneralLanguage
_AXSpeechTransformText
_AXSpeechTransformTextWithLanguage
_OBJC_CLASS_$_AVAlexSpeechSynthesisVoice
_OBJC_CLASS_$_AXEmojiUtilities
_OBJC_CLASS_$_AXSpeechAction
_OBJC_CLASS_$_AXSpeechManager
_OBJC_METACLASS_$_AVAlexSpeechSynthesisVoice
_OBJC_METACLASS_$_AXEmojiUtilities
_OBJC_METACLASS_$_AXSpeechAction
_OBJC_METACLASS_$_AXSpeechManager
_VOTBundle
__AXSpeechReplaceEmoticons
_isSpeakableEmojiString
_kAXPauseStringExtraLong
_kAXPauseStringMedium
_kAXPauseStringMediumLong
_kAXPauseStringShort
_kAXPauseStringSuperExtraLong
