//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "NSTableViewDataSource.h"
#import "NSTableViewDelegate.h"

@class NSButton, NSMutableArray, NSPopUpButtonCell, NSString, NSTableColumn, NSTableView, XRBacktraceRepository, XRCallTreeDetailView;

@interface XRDataMiningDataElementViewController : NSViewController <NSTableViewDelegate, NSTableViewDataSource>
{
    NSMutableArray *_dataMiningRecords;
    BOOL _enabled;
    XRBacktraceRepository *_repository;
    XRCallTreeDetailView *_partnerDetailView;
    NSTableView *_table;
    NSTableColumn *_symbolColumn;
    NSTableColumn *_actionColumn;
    NSTableColumn *_enabledColumn;
    NSPopUpButtonCell *_cellPrototype;
    NSButton *_symbolButton;
    NSButton *_libraryButton;
    NSButton *_restoreButton;
}

@property(nonatomic) __weak NSButton *restoreButton; // @synthesize restoreButton=_restoreButton;
@property(nonatomic) __weak NSButton *libraryButton; // @synthesize libraryButton=_libraryButton;
@property(nonatomic) __weak NSButton *symbolButton; // @synthesize symbolButton=_symbolButton;
@property(nonatomic) __weak NSPopUpButtonCell *cellPrototype; // @synthesize cellPrototype=_cellPrototype;
@property(nonatomic) __weak NSTableColumn *enabledColumn; // @synthesize enabledColumn=_enabledColumn;
@property(nonatomic) __weak NSTableColumn *actionColumn; // @synthesize actionColumn=_actionColumn;
@property(nonatomic) __weak NSTableColumn *symbolColumn; // @synthesize symbolColumn=_symbolColumn;
@property(nonatomic) __weak NSTableView *table; // @synthesize table=_table;
@property(nonatomic) BOOL enabled; // @synthesize enabled=_enabled;
@property(readonly, nonatomic) XRCallTreeDetailView *partnerDetailView; // @synthesize partnerDetailView=_partnerDetailView;
@property(retain, nonatomic) XRBacktraceRepository *repository; // @synthesize repository=_repository;
- (void).cxx_destruct;
- (void)_reloadDataWithRecords:(id)arg1;
- (id)_unifyTraceWithRepositoryRecords:(id)arg1 additionList:(id)arg2 removalList:(id)arg3;
- (id)_dataMiningRecordsForSymbols:(id)arg1 treatAsLibrary:(BOOL)arg2 context:(id)arg3;
- (void)_applyRepositoryMiningContext:(id)arg1 toSymbolName:(id)arg2;
- (id)_selectedRecordsInExternalSelection:(BOOL)arg1;
- (id)_contextOptionsForContext:(id)arg1;
- (id)_dataCellForContext:(id)arg1;
- (id)_displayNameForContext:(id)arg1;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forTableColumn:(id)arg3 row:(long long)arg4;
- (id)tableView:(id)arg1 dataCellForTableColumn:(id)arg2 row:(long long)arg3;
- (void)tableView:(id)arg1 setObjectValue:(id)arg2 forTableColumn:(id)arg3 row:(long long)arg4;
- (id)tableView:(id)arg1 objectValueForTableColumn:(id)arg2 row:(long long)arg3;
- (long long)numberOfRowsInTableView:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)restore:(id)arg1;
- (void)filterLibraries:(id)arg1;
- (void)filterSymbols:(id)arg1;
- (void)_enableControls;
- (void)reloadData;
- (void)awakeFromNib;
- (void)dealloc;
- (id)initWithCallTreeView:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

