//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <IDEFoundation/IDELocalizationWorkContext.h>

@class IDEContainer<IDELocalizedContainer>, NSDictionary;

@interface IDELocalizedResourcePopulationContext : IDELocalizationWorkContext
{
    IDEContainer<IDELocalizedContainer> *_container;
    NSDictionary *_adaptorsByName;
}

@property(retain) NSDictionary *adaptorsByName; // @synthesize adaptorsByName=_adaptorsByName;
@property(retain) IDEContainer<IDELocalizedContainer> *container; // @synthesize container=_container;
- (void).cxx_destruct;
- (void)primitiveInvalidate;

@end

