//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSImage, NSObject<XRPageNavigationDatasource>, NSObject<XRPageNavigationDelegate>;

@interface XRPageNavigationView : NSView
{
    long long _pageDiameter;
    long long _pageSpacing;
    NSImage *_gearImage;
    NSObject<XRPageNavigationDelegate> *_delegate;
    NSObject<XRPageNavigationDatasource> *_datasource;
}

@property NSObject<XRPageNavigationDatasource> *datasource; // @synthesize datasource=_datasource;
@property NSObject<XRPageNavigationDelegate> *delegate; // @synthesize delegate=_delegate;
@property(retain) NSImage *gearImage; // @synthesize gearImage=_gearImage;
@property(nonatomic) long long pageSpacing; // @synthesize pageSpacing=_pageSpacing;
@property(nonatomic) long long pageDiameter; // @synthesize pageDiameter=_pageDiameter;
- (void).cxx_destruct;
- (void)mouseDown:(id)arg1;
- (void)keyDown:(id)arg1;
- (BOOL)acceptsFirstResponder;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)backgroundGradient;

@end

