//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "XRBrushDataSource.h"

@class NSString, XRSignpostInstrumentTrackviewModel;

@interface XRSignpostGraphedArgumentsSource : NSObject <XRBrushDataSource>
{
    XRSignpostInstrumentTrackviewModel *_model;
    BOOL _drawValueGraphs;
}

- (void).cxx_destruct;
- (unsigned long long)supportedGraphTypesForRun:(id)arg1;
- (BOOL)stackGraphsForRun:(id)arg1;
- (BOOL)run:(id)arg1 graphToCurrentTimeForGraphAtIndex:(long long)arg2;
- (struct XRPathAttribute)run:(id)arg1 attributeForState:(unsigned long long)arg2 graphAtIndex:(long long)arg3;
- (void)run:(id)arg1 provideLabel:(id *)arg2 andLabelPosition:(struct XRGraphPoint *)arg3 forLabelIndex:(long long)arg4 forInspectionTimeStamp:(unsigned long long)arg5 graphAtIndex:(long long)arg6;
- (id)run:(id)arg1 labelForGraphAtIndex:(long long)arg2;
- (unsigned long long)run:(id)arg1 stateForPoint:(struct XRGraphPoint *)arg2 graphAtIndex:(long long)arg3;
- (void)run:(id)arg1 providePoints:(struct XRGraphPoint **)arg2 count:(long long *)arg3 graphSequence:(id)arg4 forTimeRange:(struct XRTimeRange)arg5 minimumInterval:(unsigned long long)arg6 graphAtIndex:(long long)arg7;
- (unsigned long long)numberOfGraphsForRun:(id)arg1;
- (id)graphStyleForRun:(id)arg1;
- (void)setIsDrawingStateGraphs;
- (void)setIsDrawingValueGraphs;
- (id)initWithModel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

