//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@class NSButton, NSPopUpButton, NSTextField;

@interface XRSignpostAutopopulateBinsViewController : NSViewController
{
    id _populateButtonTarget;
    SEL _populateButtonAction;
    NSPopUpButton *_binTypePopup;
    NSTextField *_binCountText;
    NSTextField *_binRangeMinText;
    NSTextField *_binRangeMaxText;
    NSButton *_populateButton;
}

@property NSButton *populateButton; // @synthesize populateButton=_populateButton;
@property NSTextField *binRangeMaxText; // @synthesize binRangeMaxText=_binRangeMaxText;
@property NSTextField *binRangeMinText; // @synthesize binRangeMinText=_binRangeMinText;
@property NSTextField *binCountText; // @synthesize binCountText=_binCountText;
@property NSPopUpButton *binTypePopup; // @synthesize binTypePopup=_binTypePopup;
- (void)populateButtonClicked:(id)arg1;
- (double)binRangeMax;
- (double)binRangeMin;
- (long long)binCount;
- (int)binType;
- (void)setPopulateButtonTarget:(id)arg1 action:(SEL)arg2;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

