//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "XRUIModelChangeObserver.h"

@class NSButton, NSMutableArray, NSView;

@interface XRSignpostConfigViewController : NSViewController <XRUIModelChangeObserver>
{
    NSView *_headerView;
    NSView *_bodyView;
    NSButton *_bodyDisclosureButton;
    NSView *_currentOptionView;
    NSMutableArray *_optionButtons;
    NSMutableArray *_optionViews;
    struct CGSize _bodySize;
}

@property(retain) NSMutableArray *optionViews; // @synthesize optionViews=_optionViews;
@property(retain) NSMutableArray *optionButtons; // @synthesize optionButtons=_optionButtons;
@property __weak NSView *currentOptionView; // @synthesize currentOptionView=_currentOptionView;
@property(nonatomic) struct CGSize bodySize; // @synthesize bodySize=_bodySize;
@property __weak NSButton *bodyDisclosureButton; // @synthesize bodyDisclosureButton=_bodyDisclosureButton;
@property(retain) NSView *bodyView; // @synthesize bodyView=_bodyView;
@property(retain) NSView *headerView; // @synthesize headerView=_headerView;
- (void).cxx_destruct;
- (void)modelDidChange:(id)arg1;
- (void)_removeOptionView;
- (void)_addOptionView:(id)arg1;
- (void)optionButtonClicked:(id)arg1;
- (void)bodyDisclosureClicked:(id)arg1;
- (void)setView:(id)arg1;
- (void)setRepresentedObject:(id)arg1;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

