//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XRCachedDatasetUIModel.h"

@class NSPredicate;

@interface XRSignpostDatasetBackedModel : XRCachedDatasetUIModel
{
    struct XRTimeRange _selectedTimeRange;
    NSPredicate *_basePredicate;
}

@property(retain) NSPredicate *basePredicate; // @synthesize basePredicate=_basePredicate;
- (void).cxx_destruct;
@property struct XRTimeRange selectedTimeRange;
- (void)_runDidLoadDataNotification:(id)arg1;
- (void)dealloc;
- (id)init;

@end

