//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XRKEventsInstrument.h"

@class XRKDebugSignpostMap;

@interface XRSyscallsInstrument : XRKEventsInstrument
{
    XRKDebugSignpostMap *signpostMapping;
}

+ (void)initialize;
@property(retain) XRKDebugSignpostMap *signpostMapping; // @synthesize signpostMapping;
- (void).cxx_destruct;
- (BOOL)getEventName:(id *)arg1 timeRange:(struct XRTimeRange *)arg2 forRow:(long long)arg3;
- (void)dataElementsForConfigurationViewContext:(id)arg1;
- (void)_setCellScaling:(id)arg1;
- (id)tableView:(id)arg1 toolTipForCell:(id)arg2 rect:(struct CGRect *)arg3 tableColumn:(id)arg4 row:(long long)arg5 mouseLocation:(struct CGPoint)arg6;
- (id)tableView:(id)arg1 objectValueForTableColumn:(id)arg2 row:(long long)arg3;
- (void)setupEventsArrayFilterWithToken:(id)arg1;
- (id)dataSourceForBrushWithName:(id)arg1;
- (void)addColumnsToEventListView;
- (void)addColumnsToThreadsView;
- (void)addColumnsToSummaryView;
- (id)traceTemplateData;
- (void)restoreFromTraceTemplateData:(id)arg1;

@end

