//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XRRun.h"

#import "SymbolAwareRun.h"
#import "XRSourceQuery.h"

@class DYGLGuestAppSession, NSArrayController, NSIndexSet, NSMutableArray, NSMutableDictionary, NSMutableSet, NSString, OGLASample, XRBacktraceRepository;

@interface OGLARun : XRRun <SymbolAwareRun, XRSourceQuery>
{
    struct dispatch_queue_s *_queue;
    DYGLGuestAppSession *_session;
    struct TraceContainer _trace_container;
    struct unordered_map<int, GPUTools::objc_wrapper<OGLAAPIStatsSample *>, std::__1::hash<int>, std::__1::equal_to<int>, std::__1::allocator<std::__1::pair<const int, GPUTools::objc_wrapper<OGLAAPIStatsSample *>>>> _api_stats;
    NSMutableDictionary *findingsCategoryControllersMap;
    NSMutableDictionary *findingCategories;
    NSMutableSet *uniqueFindings;
    NSMutableArray *statsArray;
    NSMutableArray *filteredAPIStatsArray;
    NSArrayController *findingsCategoryController;
    NSArrayController *statsController;
    NSArrayController *apiStatsController;
    NSMutableArray *filteredTraceSamples;
    struct XRTimeRange traceFilterTimeRange;
    NSIndexSet *traceFilterIndices;
    NSMutableArray *traceFilterTokens;
    BOOL traceFilterTokensAny;
    XRBacktraceRepository *backtraceRepository;
    NSMutableDictionary *_contextInfoDict;
    int _traceLock;
    int _otherDataLock;
    OGLASample *_cmpSample;
    BOOL _analyzerProcessingCanceled;
    long long _amortizedAnalyzerProcessingTracelinesProcessed;
    long long _amortizedAnalyzerProcessingEstimatedTotalTracelines;
    long long _analyzerProcessingTracelinesProcessed;
    long long _analyzerProcessingEstimatedTotalTracelines;
    NSString *_deviceOSVersionString;
    int _runCoderVersionNumber;
    BOOL finalized;
}

+ (unsigned long long)timeOfSample:(id)arg1;
+ (id)_newArrayControllerWithArray:(id)arg1;
+ (id)colorForSeverityLevel:(int)arg1;
@property(readonly, nonatomic) int runCoderVersionNumber; // @synthesize runCoderVersionNumber=_runCoderVersionNumber;
@property(readonly, nonatomic) NSString *deviceOSVersionString; // @synthesize deviceOSVersionString=_deviceOSVersionString;
@property(readonly, nonatomic) BOOL finalized; // @synthesize finalized;
@property(nonatomic) long long analyzerProcessingEstimatedTotalTracelines; // @synthesize analyzerProcessingEstimatedTotalTracelines=_analyzerProcessingEstimatedTotalTracelines;
@property(nonatomic) long long analyzerProcessingTracelinesProcessed; // @synthesize analyzerProcessingTracelinesProcessed=_analyzerProcessingTracelinesProcessed;
@property(nonatomic) long long amortizedAnalyzerProcessingEstimatedTotalTracelines; // @synthesize amortizedAnalyzerProcessingEstimatedTotalTracelines=_amortizedAnalyzerProcessingEstimatedTotalTracelines;
@property(nonatomic) long long amortizedAnalyzerProcessingTracelinesProcessed; // @synthesize amortizedAnalyzerProcessingTracelinesProcessed=_amortizedAnalyzerProcessingTracelinesProcessed;
@property(nonatomic) BOOL analyzerProcessingCanceled; // @synthesize analyzerProcessingCanceled=_analyzerProcessingCanceled;
@property(retain, nonatomic) XRBacktraceRepository *backtraceRepository; // @synthesize backtraceRepository;
@property(retain, nonatomic) NSMutableSet *uniqueFindings; // @synthesize uniqueFindings;
@property(retain, nonatomic) NSArrayController *apiStatsController; // @synthesize apiStatsController;
@property(retain, nonatomic) NSArrayController *statsController; // @synthesize statsController;
@property(retain, nonatomic) NSArrayController *findingsCategoryController; // @synthesize findingsCategoryController;
@property(retain, nonatomic) DYGLGuestAppSession *session; // @synthesize session=_session;
@property(readonly, nonatomic) struct dispatch_queue_s *queue; // @synthesize queue=_queue;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)operation:(id)arg1 commentsForSymbol:(id)arg2 inSourceManager:(id)arg3 callTreeInformation:(id)arg4;
- (void)filterTraceWithTokens:(id)arg1 any:(BOOL)arg2;
- (void)filterTraceWithIndexSet:(id)arg1;
- (void)filterWithTimeRange:(struct XRTimeRange)arg1;
- (void)_applyTraceFilters;
- (void)applySortDescriptors:(id)arg1 controller:(id)arg2;
- (id)mostRecentSamplefromController:(id)arg1;
- (id)valueForSampleKey:(id)arg1 atIndex:(unsigned long long)arg2 filtered:(BOOL)arg3 controller:(id)arg4;
- (unsigned long long)indexOfSample:(id)arg1 filtered:(BOOL)arg2 controller:(id)arg3;
- (unsigned long long)_indexOfSamplePrelocked:(id)arg1 filtered:(BOOL)arg2 controller:(id)arg3;
- (unsigned long long)indexOfTraceSample:(id)arg1 filtered:(BOOL)arg2;
- (id)samplesInclusiveOfTimeRange:(struct XRTimeRange)arg1 controller:(id)arg2;
- (id)samplesInTimeRange:(struct XRTimeRange)arg1 controller:(id)arg2;
- (id)samplesInTimeRange:(struct XRTimeRange)arg1 controller:(id)arg2 inclusiveOfRange:(BOOL)arg3;
- (id)traceItemsInTimeRange:(struct XRTimeRange)arg1;
- (unsigned long long)indexOfSampleAtTime:(unsigned long long)arg1 filtered:(BOOL)arg2 controller:(id)arg3;
- (unsigned long long)indexOfTraceItemAtTime:(unsigned long long)arg1 filtered:(BOOL)arg2;
- (id)sampleAtIndex:(unsigned long long)arg1 filtered:(BOOL)arg2 controller:(id)arg3;
- (id)_sampleAtIndexPrelocked:(unsigned long long)arg1 filtered:(BOOL)arg2 controller:(id)arg3;
- (id)traceItemAtIndex:(unsigned long long)arg1 filtered:(BOOL)arg2;
- (unsigned long long)sampleCount:(BOOL)arg1 controller:(id)arg2;
- (void)addStatisticsFromArray:(id)arg1;
- (void)addStatistic:(id)arg1;
- (void)updateFindingCategoryAndFlagWithFindingSample:(id)arg1;
- (void)addFinding:(id)arg1;
- (unsigned long long)traceItemCount:(BOOL)arg1;
- (void)addTraceItems:(id)arg1;
- (void)_computeAPIStatistics;
- (id)controllerForFindingCategory:(id)arg1;
- (void)runBlockWhileLocked:(CDUnknownBlockType)arg1;
- (void)finalizeRun;
- (void)updateAmortizedAnalysisStats;
- (void)updateContextsInfo:(id)arg1;
- (id)contextInfoForContextID:(unsigned long long)arg1;
- (id)repositoryForCallTrees;
- (void)setTargetDevice:(id)arg1 pid:(int)arg2;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)init;
- (void)_commonInitPost;
- (void)_commonInitPre;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

