//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DVTSourceControlPlugInPrimary.h"

@class NSXPCConnection, NSXPCListener;

@interface DVTSourceControlXPCPrimary : DVTSourceControlPlugInPrimary
{
    double _xpcLastProgressValueSent;
    NSXPCListener *_listener;
    NSXPCConnection *_connection;
}

@property(retain) NSXPCConnection *connection; // @synthesize connection=_connection;
@property(retain) NSXPCListener *listener; // @synthesize listener=_listener;
- (void).cxx_destruct;
- (void)setProgressStatus:(int)arg1 progressValue:(double)arg2 userReadableString:(id)arg3;
- (BOOL)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;

@end

