//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CLPolygonSimplifier : NSObject
{
}

+ (double)simplifiedLength:(id)arg1 threshold:(double)arg2;
+ (double)simplifiedLength:(id)arg1 threshold:(double)arg2 type:(int)arg3;

@end

