//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CLIntersiloServiceProtocol.h"

@class NSArray, NSURL;

@protocol CLSimulationControllerProtocol <CLIntersiloServiceProtocol>
- (void)setTravellingSpeed:(double)arg1;
- (void)setLocationInterval:(double)arg1;
- (void)setIntermediateLocationDistance:(double)arg1;
- (void)setRepeatBehavior:(int)arg1;
- (void)setSimulationType:(int)arg1;
- (void)clearPendingLocations;
- (void)addPendingLocationsArray:(NSArray *)arg1;
- (void)startSimulation;
- (void)stopSimulation;
- (void)setSimulationScenarioURL:(NSURL *)arg1;
- (void)shutdown;
@end

