//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBRequest.h"

#import "NSCopying.h"

@class CRMeta, NSMutableArray;

@interface CRIndoorCollectionRequest : PBRequest <NSCopying>
{
    NSMutableArray *_indoorLocations;
    NSMutableArray *_indoorWifis;
    CRMeta *_meta;
}

@property(retain, nonatomic) NSMutableArray *indoorLocations; // @synthesize indoorLocations=_indoorLocations;
@property(retain, nonatomic) NSMutableArray *indoorWifis; // @synthesize indoorWifis=_indoorWifis;
@property(retain, nonatomic) CRMeta *meta; // @synthesize meta=_meta;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (Class)responseClass;
- (unsigned int)requestTypeCode;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
- (id)indoorLocationsAtIndex:(unsigned long long)arg1;
- (unsigned long long)indoorLocationsCount;
- (void)addIndoorLocations:(id)arg1;
- (void)clearIndoorLocations;
- (id)indoorWifisAtIndex:(unsigned long long)arg1;
- (unsigned long long)indoorWifisCount;
- (void)addIndoorWifis:(id)arg1;
- (void)clearIndoorWifis;
- (void)dealloc;

@end

