//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AudioSettingsTableViewCell;

__attribute__((visibility("hidden")))
@interface AudioSettingTableRow : NSObject
{
    AudioSettingsTableViewCell *_currentCell;
}

@property(readonly, nonatomic) AudioSettingsTableViewCell *currentCell; // @synthesize currentCell=_currentCell;
- (void).cxx_destruct;
- (void)configureCurrentCell;
- (id)updateCurrentCellForTableView:(id)arg1;
- (id)reuseIdentifierForCell;

@end

