//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class BlurView, NSArray, UIColor;

__attribute__((visibility("hidden")))
@interface ControlBarView : UIView
{
    BlurView *_blurView;
    NSArray *_items;
    NSArray *_nextItems;
    UIColor *_blurDisabledBackgroundColor;
    UIView *_borderLine;
    double _borderLineHeight;
}

@property(retain, nonatomic) NSArray *nextItems; // @synthesize nextItems=_nextItems;
@property(retain, nonatomic) NSArray *items; // @synthesize items=_items;
- (void).cxx_destruct;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)framesForItems:(id)arg1;
- (void)layoutSubviews;
- (void)updateItemsAnimated;
- (void)layoutMarginsDidChange;
- (void)setItems:(id)arg1 animated:(_Bool)arg2;
- (void)removeItem:(id)arg1;
- (void)addItem:(id)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)setBlurDisabledBackgroundColor:(id)arg1;
- (void)setStyle:(long long)arg1;
- (void)transitionToPrivateStyle:(long long)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

