//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIActionSheet.h"

#import "UIActionSheetDelegate.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface EasyCallbackActionSheet : UIActionSheet <UIActionSheetDelegate>
{
    CDUnknownBlockType _willPresentCallback;
    CDUnknownBlockType _didPresentCallback;
    CDUnknownBlockType _willDismissCallback;
    CDUnknownBlockType _didDismissCallback;
}

+ (id)actionSheet;
@property(copy, nonatomic) CDUnknownBlockType didDismissCallback; // @synthesize didDismissCallback=_didDismissCallback;
@property(copy, nonatomic) CDUnknownBlockType willDismissCallback; // @synthesize willDismissCallback=_willDismissCallback;
@property(copy, nonatomic) CDUnknownBlockType didPresentCallback; // @synthesize didPresentCallback=_didPresentCallback;
@property(copy, nonatomic) CDUnknownBlockType willPresentCallback; // @synthesize willPresentCallback=_willPresentCallback;
- (void).cxx_destruct;
- (void)actionSheet:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (void)actionSheet:(id)arg1 willDismissWithButtonIndex:(long long)arg2;
- (void)didPresentActionSheet:(id)arg1;
- (void)willPresentActionSheet:(id)arg1;
- (void)showWithPositioningBlock:(CDUnknownBlockType)arg1 animated:(_Bool)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

