//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class MKStarRatingAndLabelView, SearchResult, UIButton, UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface ListViewSearchResultCell : UITableViewCell
{
    UILabel *_nameLabel;
    UILabel *_addressLabel;
    UIImageView *_icon;
    SearchResult *_searchResult;
    MKStarRatingAndLabelView *_ratingView;
    UILabel *_numReviewsLabel;
    UIButton *_infoButton;
    id <ListViewSearchResultCellAccessoryDelegate> _delegate;
}

+ (id)reuseIdentifier;
@property(nonatomic) __weak id <ListViewSearchResultCellAccessoryDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (double)_numReviewsLabelBaselineToBottom;
- (double)_addressLabelBaselineToNumReviewsLabelBaseline;
- (double)_nameLabelBaselineToAddressLabelBaseline;
- (double)_topToNameLabelBaseline;
- (void)_updateLabels;
@property(retain, nonatomic) SearchResult *searchResult;
- (void)pressedInfo:(id)arg1;
- (id)infoButton;
- (void)_updateFonts;
- (void)prepareForReuse;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

