//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MainChromeTopBarContentProvider.h"

@class MainChromeViewController, NSString;

__attribute__((visibility("hidden")))
@interface MainChromeTopBarMap : NSObject <MainChromeTopBarContentProvider>
{
    _Bool _cachesRegular;
    id _cachedRegular;
    CDUnknownBlockType _createRegular;
    _Bool _cachesCompressed;
    id _cachedCompressed;
    CDUnknownBlockType _createCompressed;
}

- (void).cxx_destruct;
- (void)setTopBarContentForVariant:(long long)arg1 options:(long long)arg2 fromCreationBlock:(CDUnknownBlockType)arg3;
- (void)setTopBarContentForVariant:(long long)arg1 fromCreationBlock:(CDUnknownBlockType)arg2;
- (id)topBarContentForVariant:(long long)arg1;
- (id)initWithTopBarContentForAllVariants:(id)arg1;
- (id)init;

// Remaining properties
@property(nonatomic) MainChromeViewController *chromeViewController;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

