//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSString;

@protocol MapsSynced <NSObject>
@property(readonly, nonatomic) NSData *syncData;
@property(copy, nonatomic) NSString *syncIdentifier;
- (_Bool)updateFromSyncData:(NSData *)arg1;

@optional
@property(nonatomic) double position;
@end

