//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MapsDebugTableRow.h"

__attribute__((visibility("hidden")))
@interface MapsDebugActionTableRow : MapsDebugTableRow
{
}

- (void)configureCell:(id)arg1;
- (id)reuseIdentifier;

@end

