//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UILabel.h"

__attribute__((visibility("hidden")))
@interface MapsAutolayoutLabel : UILabel
{
    _Bool _shouldInsetAlignmentToAscender;
}

@property(nonatomic) _Bool shouldInsetAlignmentToAscender; // @synthesize shouldInsetAlignmentToAscender=_shouldInsetAlignmentToAscender;
- (struct UIEdgeInsets)alignmentRectInsets;

@end

