//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface MapScaleCell : NSObject
{
    double _distanceInMeters;
    _Bool _useMetric;
    _Bool _useYardsForShortDistances;
}

- (void)drawInRect:(struct CGRect)arg1;
- (id)_legendStringForDistanceString:(id)arg1 index:(int)arg2;
- (id)initWithDistanceInMeters:(double)arg1 useMetric:(_Bool)arg2 useYardsForShortDistances:(_Bool)arg3;

@end

