//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MKMapService.h"

@interface MKMapService (Maps)
- (id)ticketForProblem:(id)arg1 mapItemForProblemContext:(id)arg2;
- (void)submitUsageAction:(int)arg1 includeStarkInfo:(_Bool)arg2 mapItem:(id)arg3 timestamp:(double)arg4 resultIndex:(int)arg5 mapRegion:(id)arg6 zoomLevel:(double)arg7;
- (void)submitUsageAction:(int)arg1 mapRegion:(id)arg2 zoomLevel:(double)arg3 includeStarkInfo:(_Bool)arg4;
- (void)submitUsageAction:(int)arg1 includeStarkInfo:(_Bool)arg2;
- (id)ticketForURLQuery:(id)arg1 coordinate:(CDStruct_c3b9c2ee)arg2 muid:(unsigned long long)arg3 resultProviderId:(int)arg4;
- (id)ticketForQuerySearch:(id)arg1 source:(int)arg2 includeETA:(_Bool)arg3;
- (id)ticketForSearchQuery:(id)arg1 completionItem:(id)arg2 includeETA:(_Bool)arg3 traits:(id)arg4;
- (id)_ticketForSearchQuery:(id)arg1 completionItem:(id)arg2 includeETA:(_Bool)arg3 traits:(id)arg4;
- (id)ticketForMapItemToRefine:(id)arg1;
- (id)ticketForReverseGeocodeCoordinate:(CDStruct_c3b9c2ee)arg1 includeETA:(_Bool)arg2;
- (id)mapsDefaultTraitsForAction:(int)arg1 includeStarkInfo:(_Bool)arg2;
- (id)mapsDefaultTraitsForMapView:(id)arg1 mapViewEnteredForegroundDate:(id)arg2 mapViewportChangedDate:(id)arg3;
- (id)mapsDefaultTraitsForMapRegion:(id)arg1 source:(int)arg2;
- (id)_mapsDefaultTraits;
@end

