//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MNGuidanceSignsDisplay.h"

#import "MNGuidanceSignViewDelegate.h"

@class CALayer, ChromeViewController, InterruptibleAnimation, MNGuidanceSecondarySignView, MNGuidanceSignContainerView, MNGuidanceSignView, NSMutableArray, NSString, NSTimeZone, NSTimer, TopBarTitleView, UIView;

__attribute__((visibility("hidden")))
@interface MNClassicSignsDisplay : MNGuidanceSignsDisplay <MNGuidanceSignViewDelegate>
{
    _Bool _isShowingTopTitleBar;
    CALayer *_topBarMask;
    struct CGRect _currentStatusBarFrame;
    struct CGRect _currentUnobscuredBounds;
    ChromeViewController *_viewController;
    id <MapsChromeModeController> _container;
    UIView *_superview;
    _Bool _simulatingStatusBarFrame;
    struct CGRect _simulatedStatusBarFrame;
    _Bool _hidingSigns;
    _Bool _suspendUpdates;
    _Bool _anyUpdateRequiresChangingPrimarySign;
    _Bool _useMetric;
    _Bool _useYardsForShortDistance;
    int _guidanceState;
    _Bool _isAnimatingSignFlyIn;
    _Bool _isAnimatingSignFlyOut;
    _Bool _runLoopIsWaitingForSecondarySignCall;
    NSMutableArray *_pendingSignQueue;
    NSTimer *_etaUpdateTimer;
    _Bool _newPrimaryIsOldSecondary;
    _Bool _hideTopTitleBarViewForRecalculation;
    InterruptibleAnimation *_hidingAnimation;
    double _timeIntervalToDestination;
    double _distanceToDestination;
    NSTimeZone *_destinationTimezone;
    MNGuidanceSignView *_signView;
    MNGuidanceSecondarySignView *_secondarySignView;
    MNGuidanceSignView *_pendingSignView;
    MNGuidanceSecondarySignView *_pendingSecondarySignView;
    MNGuidanceSignContainerView *_currentSignContainerView;
    MNGuidanceSignContainerView *_pendingSignContainerView;
    TopBarTitleView *_topBarTitleView;
    struct CGRect _navigationBarFrame;
}

@property(nonatomic) _Bool hideTopTitleBarViewForRecalculation; // @synthesize hideTopTitleBarViewForRecalculation=_hideTopTitleBarViewForRecalculation;
@property(retain, nonatomic) TopBarTitleView *topBarTitleView; // @synthesize topBarTitleView=_topBarTitleView;
@property(readonly, nonatomic) struct CGRect _navigationBarFrame; // @synthesize _navigationBarFrame;
@property(retain, nonatomic) MNGuidanceSignContainerView *_pendingSignContainerView; // @synthesize _pendingSignContainerView;
@property(retain, nonatomic) MNGuidanceSignContainerView *_currentSignContainerView; // @synthesize _currentSignContainerView;
@property(retain, nonatomic) MNGuidanceSecondarySignView *_pendingSecondarySignView; // @synthesize _pendingSecondarySignView;
@property(retain, nonatomic) MNGuidanceSignView *_pendingSignView; // @synthesize _pendingSignView;
@property(retain, nonatomic) MNGuidanceSecondarySignView *_secondarySignView; // @synthesize _secondarySignView;
@property(retain, nonatomic) MNGuidanceSignView *_signView; // @synthesize _signView;
@property(retain, nonatomic) NSTimeZone *destinationTimezone; // @synthesize destinationTimezone=_destinationTimezone;
@property(nonatomic) double distanceToDestination; // @synthesize distanceToDestination=_distanceToDestination;
@property(nonatomic) double timeIntervalToDestination; // @synthesize timeIntervalToDestination=_timeIntervalToDestination;
@property(retain, nonatomic) InterruptibleAnimation *hidingAnimation; // @synthesize hidingAnimation=_hidingAnimation;
- (void).cxx_destruct;
- (void)_didChangeCurrentLocale:(id)arg1;
- (void)setDestinationDisplayName:(id)arg1;
- (void)showRecalculationFailed;
- (void)showRecalculating;
- (void)resetForNewReceivedRoute;
- (void)showArrived;
- (void)hideSecondaryManeuver;
- (void)showSecondaryManeuver:(int)arg1 junction:(id)arg2 instructions:(id)arg3 shorterAlternativeInstructions:(id)arg4 shieldType:(int)arg5 shieldText:(id)arg6 drivingSide:(int)arg7;
- (void)setTimeToManeuver:(double)arg1 distanceToManeuver:(double)arg2;
- (void)showManeuverAlertForAnnouncementStage:(unsigned long long)arg1;
- (void)showNewManeuver:(int)arg1 junction:(id)arg2 instructions:(id)arg3 shorterAlternativeInstructions:(id)arg4 shieldType:(int)arg5 shieldText:(id)arg6 drivingSide:(int)arg7;
- (void)showProceedingToRouteDistance:(double)arg1 displayString:(id)arg2;
- (void)setTotalRemainingTime:(double)arg1 remainingDistance:(double)arg2 destinationTimezone:(id)arg3;
- (void)_updateEstimatesDisplay;
- (void)showNoGuidance;
- (void)_hideSignsAnimated:(_Bool)arg1;
- (void)guidanceSignViewSingleTap:(id)arg1;
- (_Bool)guidanceSignViewsShouldAcceptsSingleTap:(id)arg1;
- (void)_flyInNewSign:(id)arg1 behindOldSign:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_flyUpSecondaryToPrimaryWithCompletion:(CDUnknownBlockType)arg1;
- (void)_animateInNewSecondarySign:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_scheduleSignDisplay;
- (void)_handleQueueItem:(id)arg1;
- (void)_makeNewPrimarySign:(CDUnknownBlockType)arg1 secondarySign:(CDUnknownBlockType)arg2;
- (void)_flyAwaySign:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)removeFromContainingViewController;
- (void)_setFrameForContainerView:(id)arg1;
- (void)setMaximumWidthForContainerView:(id)arg1;
- (void)updateInsets;
- (void)_layoutTitleView;
- (void)layoutForUnobscuredBoundsChange;
- (int)_variantForSizeClass;
- (void)_updateBlur;
- (void)_updateCurrentSignStyle;
- (void)setShowsDimmedSigns:(_Bool)arg1 animation:(id)arg2;
- (id)_newSecondarySignView;
- (id)_newSignView;
- (id)layerMaskAnimationWithFrom:(double)arg1 to:(double)arg2;
- (void)setHidden:(_Bool)arg1 animated:(_Bool)arg2;
@property(readonly, nonatomic) struct CGRect _unobscuredBounds;
- (void)_useStatusBarFrame:(struct CGRect)arg1 withinBlock:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) struct CGRect _statusBarFrame;
- (void)_removeTopBarLayerMask;
- (void)_addTopBarLayerMaskIfNeeded;
- (id)mainChromeViewController;
- (void)dealloc;
- (id)initWithContainingChromeViewController:(id)arg1 mode:(id)arg2 inView:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

