//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MNMotionContextProvider.h"

@class CMActivityManager, NSString;

__attribute__((visibility("hidden")))
@interface MNCoreMotionContextProvider : NSObject <MNMotionContextProvider>
{
    CMActivityManager *_activityManager;
    id <MNMotionContextProviderDelegate> _delegate;
}

@property(nonatomic) __weak id <MNMotionContextProviderDelegate> motionDelegate; // @synthesize motionDelegate=_delegate;
- (void).cxx_destruct;
- (void)stopMotionUpdates;
- (void)startMotionUpdates;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

