//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MNNavigationOverviewBar, NSString;

@protocol MNNavigationOverviewBarDelegate <NSObject>
- (NSString *)currentExpandedTravelTimeForNavigationOverviewBar:(MNNavigationOverviewBar *)arg1 forTimeInterval:(double)arg2;
- (void)navigationOverviewBarEndTapped:(MNNavigationOverviewBar *)arg1;
- (void)navigationOverviewBarOverviewTapped:(MNNavigationOverviewBar *)arg1;
@end

