//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MNETAManagerDelegate.h"

@class GEOComposedWaypoint, GEODirectionsFeedbackCollector, GEODirectionsRequestFeedback, GEODirectionsRouteRequest, GEOMapRegion, GEORoute, GEORouteGenerator, GEOURLRouteHandle, MNETAManager, MNRoute, MNRouteSet, MNTracePlayer, MNTraceRecorder, MapsRoutePreloadSession, NSData, NSString;

__attribute__((visibility("hidden")))
@interface MNRouteManager : NSObject <MNETAManagerDelegate>
{
    GEODirectionsRouteRequest *_request;
    GEOComposedWaypoint *_origin;
    GEOComposedWaypoint *_destination;
    int _desiredTransportType;
    GEOMapRegion *_mapRegion;
    GEOURLRouteHandle *_routeHandle;
    MNRouteSet *_activeRouteSet;
    int _routeState;
    id <MNRouteManagerDelegate> _delegate;
    MNTraceRecorder *_traceRecorder;
    MNTracePlayer *_tracePlayer;
    GEODirectionsRequestFeedback *_feedback;
    MapsRoutePreloadSession *_mapsRoutePreloadSession;
    MNETAManager *_etaManager;
    NSData *_prevRouteID;
    unsigned int _prevStepID;
    GEODirectionsFeedbackCollector *_feedbackCollector;
    double _lastRereouteTime;
    GEORouteGenerator *_routeGenerator;
    MNRoute *_userSelectedRoute;
    GEORoute *_userSelectedGeoRoute;
    NSString *_voiceLanguage;
    _Bool _fromCurrentLocation;
    _Bool _preloadRoutes;
    _Bool _allowAlternateTransportTypes;
}

+ (id)defaultRouteAttributesForNavigation;
+ (id)defaultRouteAttributes;
@property(retain, nonatomic) GEORoute *userSelectedGeoRoute; // @synthesize userSelectedGeoRoute=_userSelectedGeoRoute;
@property(retain, nonatomic) MNRoute *userSelectedRoute; // @synthesize userSelectedRoute=_userSelectedRoute;
@property(retain, nonatomic) NSData *prevRouteID; // @synthesize prevRouteID=_prevRouteID;
@property(retain, nonatomic) GEODirectionsRequestFeedback *feedback; // @synthesize feedback=_feedback;
@property(retain, nonatomic) MNTracePlayer *tracePlayer; // @synthesize tracePlayer=_tracePlayer;
@property(retain, nonatomic) MNTraceRecorder *traceRecorder; // @synthesize traceRecorder=_traceRecorder;
@property(nonatomic) __weak id <MNRouteManagerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) NSString *voiceLanguage; // @synthesize voiceLanguage=_voiceLanguage;
@property(retain, nonatomic) MNRouteSet *activeRouteSet; // @synthesize activeRouteSet=_activeRouteSet;
@property(readonly, nonatomic) GEOURLRouteHandle *routeHandle; // @synthesize routeHandle=_routeHandle;
@property(readonly, nonatomic) int desiredTransportType; // @synthesize desiredTransportType=_desiredTransportType;
@property(readonly, nonatomic) MNETAManager *etaManager; // @synthesize etaManager=_etaManager;
@property(readonly, nonatomic) GEOComposedWaypoint *destination; // @synthesize destination=_destination;
@property(readonly, nonatomic) GEOComposedWaypoint *origin; // @synthesize origin=_origin;
@property(readonly, nonatomic) GEORouteGenerator *routeGenerator; // @synthesize routeGenerator=_routeGenerator;
@property(retain, nonatomic) GEODirectionsRouteRequest *request; // @synthesize request=_request;
- (void).cxx_destruct;
- (void)etaManager:(id)arg1 updatedRouteFromETARoute:(id)arg2 etaBehavior:(long long)arg3 routeRemainingDistance:(double)arg4 routeRemainingTime:(unsigned int)arg5;
- (void)etaManager:(id)arg1 failedToReceiveETAResponse:(id)arg2;
- (void)etaManager:(id)arg1 receivedETAResponse:(id)arg2;
- (void)etaManager:(id)arg1 willSendETARequest:(id)arg2;
- (void)etaManager:(id)arg1 recommendsNewRoute:(id)arg2 etaRoute:(id)arg3 oldEstimatedTime:(unsigned int)arg4 newEstimatedTime:(unsigned int)arg5;
- (void)etaManager:(id)arg1 forceSwitchToNewRoute:(id)arg2 etaRoute:(id)arg3;
- (void)etaManagerUpdatedTrafficIncidents:(id)arg1;
- (void)etaManagerUpdatedETATime:(id)arg1;
- (void)_sendTrafficRerouteFeedbackForRoute:(id)arg1 etaRoute:(id)arg2 forcedReroute:(_Bool)arg3;
- (_Bool)_requestDirectionsFromTracePlayer:(id)arg1 finishedHandler:(CDUnknownBlockType)arg2 errorHandler:(CDUnknownBlockType)arg3;
- (void)forceReroutingWithRouteResponse:(id)arg1 request:(id)arg2;
@property(readonly, nonatomic) id <MNRouteManagerTestingDelegate> testingDelegate;
- (void)selectRouteAtIndex:(unsigned long long)arg1;
- (void)_handleRequesterError:(id)arg1 problemDetails:(CDStruct_850a5e09 *)arg2;
- (void)resetToNewRoute:(id)arg1 etaRoute:(id)arg2 forcedSwitch:(_Bool)arg3;
- (void)_handleRequesterResponse:(id)arg1 routeAttributes:(id)arg2 retrievedFromTrace:(_Bool)arg3;
- (void)startNavETAOverviewRequests;
- (void)startNavETAUpdateRequests;
- (void)stopNavETAUpdateRequests;
- (void)switchToNewRouteIfNecessaryFrom:(id)arg1 transportType:(int)arg2;
- (void)_switchToContingentRoute:(id)arg1 atLocation:(id)arg2 routeCoordinate:(CDStruct_f48a8b00)arg3 onRoute:(_Bool)arg4;
- (void)reset;
- (void)cancelRoute;
- (void)cancelRecalculation;
- (_Bool)recalculateRouteFrom:(id)arg1 stepIndex:(unsigned long long)arg2 forceRepeatedRecalc:(_Bool)arg3 transportType:(int)arg4;
- (_Bool)findContingentRouteFrom:(id)arg1 transportType:(int)arg2;
- (void)loadMaxRoutes:(unsigned int)arg1 timepoint:(CDStruct_191b847f *)arg2 errorHandler:(CDUnknownBlockType)arg3 recordTrace:(_Bool)arg4;
- (void)_getNewDirectionsMaxRouteCount:(unsigned int)arg1 from:(id)arg2 routeHandle:(id)arg3 isReroute:(_Bool)arg4 type:(int)arg5 includeAlternateTransportTypes:(_Bool)arg6 timepoint:(CDStruct_191b847f *)arg7;
- (_Bool)_destinationShortEnoughForWalkingFromWaypoint:(id)arg1;
- (_Bool)_destinationTooLongForWalkingFromWayPoint:(id)arg1;
- (double)_straightLineDistanceToDestinationFromWaypoint:(id)arg1;
- (void)_updateRoutePreloading;
- (void)sendRouteFeedbackWithLocationWhereRouteWasCancelled:(id)arg1 audioFeedback:(CDStruct_8a30f810 *)arg2;
- (void)updateLocation:(id)arg1;
- (void)recordCurrentRoute;
@property(readonly, nonatomic) id <GEORoutePreloadSession> routePreloadSession;
@property(nonatomic) __weak MNRoute *currentRoute;
- (id)currentGeoRoute;
- (void)didArriveAtLocation:(id)arg1;
- (void)markCurrentRoute;
@property(nonatomic) int routeState;
- (void)_clearETAManager;
- (void)dealloc;
- (id)initWithDirectionsFrom:(id)arg1 to:(id)arg2 mapRegion:(id)arg3 type:(int)arg4 fromCurrentLocation:(_Bool)arg5 preloadRoutes:(_Bool)arg6 allowAlternateTypes:(_Bool)arg7 routeHandle:(id)arg8 withFeedback:(id)arg9;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

