//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "ManeuverGuidanceObserver.h"

@class InstructionsLabel, MNGuidanceManeuverView, MNStarkSignStyle, ManeuverGuidance, MapsAutoLayoutContext, NSString, UIImageView, UIView<StarkDistanceLabel>;

__attribute__((visibility("hidden")))
@interface MNStarkGuidanceSign : UIView <ManeuverGuidanceObserver>
{
    InstructionsLabel *_instructionsLabel;
    MNGuidanceManeuverView *_maneuverView;
    MapsAutoLayoutContext *_autoLayoutContext;
    UIView<StarkDistanceLabel> *_distanceLabel;
    UIImageView *_shieldView;
    ManeuverGuidance *_guidance;
    long long _displayedLightLevel;
    MNStarkSignStyle *_style;
}

+ (id)compactPrimarySignWithGuidance:(id)arg1;
+ (id)primarySignWithGuidance:(id)arg1;
+ (id)secondarySignWithGuidance:(id)arg1;
+ (_Bool)requiresConstraintBasedLayout;
@property(readonly, nonatomic) MNStarkSignStyle *style; // @synthesize style=_style;
@property(nonatomic) long long displayedLightLevel; // @synthesize displayedLightLevel=_displayedLightLevel;
@property(readonly, nonatomic) ManeuverGuidance *guidance; // @synthesize guidance=_guidance;
- (void).cxx_destruct;
- (id)_inlineDistanceLabel;
- (id)_rightAlignedDistanceLabel;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (double)_maxWidthForSize:(struct CGSize)arg1;
- (void)_updateGrowingRequirementsForSize:(struct CGSize)arg1;
- (void)layoutSubviews;
- (id)_secondaryLayoutContext;
- (id)_compactPrimaryLayoutContext;
- (id)_primaryLayoutContext;
- (void)_updateShieldForNewWindow:(id)arg1;
- (void)willMoveToWindow:(id)arg1;
- (void)updateConstraints;
- (id)_currentStyleAttributes;
- (void)_fadeViewIfNeeded:(id)arg1 forChanges:(CDUnknownBlockType)arg2;
- (void)_reloadDetails;
- (void)maneuverGuidanceDistanceDidChange:(id)arg1;
- (void)maneuverGuidanceDetailsDidChange:(id)arg1;
- (_Bool)isSecondary;
- (void)_updateStyling;
- (id)initWithGuidance:(id)arg1 variant:(int)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

