//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface MNStarkSignStyle : NSObject
{
    int _variant;
}

+ (id)styleWithVariant:(int)arg1;
@property(readonly, nonatomic) int variant; // @synthesize variant=_variant;
- (int)desiredFraming;
- (struct CGSize)arrowReferenceSize;
- (CDStruct_092aca68)arrowMetrics;
- (_Bool)isSecondary;
- (id)instructionsFont;
- (double)instructionsLabelTopMargin;
- (id)distanceColor;
- (id)primaryDistanceFont;
- (id)secondaryDistanceFont;
- (_Bool)displaysShield;
- (_Bool)displaysDistance;
- (id)initWithVariant:(int)arg1;

@end

