//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton;

__attribute__((visibility("hidden")))
@interface MNTraceControlView : UIView
{
    id <MNTraceControlViewDelegate> _delegate;
    _Bool _isPlaying;
    double _playSpeed;
    _Bool _isLogging;
    UIButton *_jumpBackButton;
    UIButton *_playButton;
    UIButton *_ffButton;
    UIButton *_frButton;
    UIButton *_bookmarksButton;
    UIButton *_testLoggingButton;
}

@property(readonly, nonatomic) UIButton *bookmarksButton; // @synthesize bookmarksButton=_bookmarksButton;
@property(readonly, nonatomic) UIButton *frButton; // @synthesize frButton=_frButton;
@property(readonly, nonatomic) UIButton *ffButton; // @synthesize ffButton=_ffButton;
@property(readonly, nonatomic) UIButton *playButton; // @synthesize playButton=_playButton;
@property(readonly, nonatomic) UIButton *jumpBackButton; // @synthesize jumpBackButton=_jumpBackButton;
@property(nonatomic) _Bool isLogging; // @synthesize isLogging=_isLogging;
@property(nonatomic) double playSpeed; // @synthesize playSpeed=_playSpeed;
@property(nonatomic) _Bool isPlaying; // @synthesize isPlaying=_isPlaying;
@property(nonatomic) __weak id <MNTraceControlViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_testLoggingButtonPressed:(id)arg1;
- (void)_bookmarksButtonPressed:(id)arg1;
- (void)_ffButtonPressed:(id)arg1;
- (void)_frButtonPressed:(id)arg1;
- (unsigned long long)_currentPlaySpeedIndex;
- (void)_playButtonPressed:(id)arg1;
- (void)_jumpBackButtonPressed:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

