//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface PDFUtilities : NSObject
{
    struct CGPDFDocument *_northPin;
    struct CGPDFDocument *_eastPin;
    struct CGPDFDocument *_southPin;
    struct CGPDFDocument *_westPin;
    struct CGPDFDocument *_greenPin;
    struct CGPDFDocument *_redPin;
    struct CGPDFDocument *_searchPin;
    struct CGPDFDocument *_badgeSearch;
    struct CGPDFDocument *_badgeBus;
    struct CGPDFDocument *_badgeCar;
    struct CGPDFDocument *_badgeWalk;
    NSMutableDictionary *_imageCache;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)purgeAssets;
- (struct CGPDFDocument *)newDocumentWithName:(struct __CFString *)arg1;
- (struct CGAffineTransform)drawingTransformForPage:(struct CGPDFPage *)arg1 pdfBox:(int)arg2 destRect:(struct CGRect)arg3 preserveAspectRatio:(_Bool)arg4;
- (void)renderDocumentForType:(int)arg1 inRect:(struct CGRect)arg2;
- (void)renderPage:(struct CGPDFPage *)arg1 InRect:(struct CGRect)arg2;
- (struct CGPDFDocument *)documentForType:(int)arg1;

@end

