//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AdvisorySheetViewDelegate.h"
#import "SearchManagerObserver.h"

@class AdaptivePresenter, MainChromeViewController, NSString, PlacePresentationController, SearchResult;

__attribute__((visibility("hidden")))
@interface PlacePresentationSelectionManager : NSObject <AdvisorySheetViewDelegate, SearchManagerObserver>
{
    _Bool _registeredForAddressBookChanges;
    PlacePresentationController *_placePresentationController;
    AdaptivePresenter *_placeCardPresenter;
    _Bool _readyForPlaceCard;
    SearchResult *_pendingPlaceCardSearchResult;
    MainChromeViewController *_chrome;
    SearchResult *_selectedSearchResult;
}

@property(retain, nonatomic) SearchResult *selectedSearchResult; // @synthesize selectedSearchResult=_selectedSearchResult;
@property(nonatomic) __weak MainChromeViewController *chrome; // @synthesize chrome=_chrome;
- (void).cxx_destruct;
- (_Bool)mode:(id)arg1 shouldShowPlacePresentationOptionInCalloutForLabelMarker:(id)arg2;
- (_Bool)mode:(id)arg1 shouldShowPlacePresentationOptionInCalloutForAnnotationView:(id)arg2;
- (_Bool)mode:(id)arg1 shouldShowFlyoverButtonForSearchResult:(id)arg2;
- (_Bool)mode:(id)arg1 shouldShowDirectionsButtonForSearchResult:(id)arg2;
- (_Bool)mode:(id)arg1 shouldChangeMKApplicationStateForLabelMarker:(id)arg2;
- (void)advisorySheetButtonWasTapped:(id)arg1;
- (void)_unregisterForAddressBookChanges;
- (void)_registerForAddressBookChanges:(id)arg1;
- (_Bool)shouldAllowAutorotation;
- (void)handleAdvisoryForRoute:(id)arg1 inContext:(id)arg2;
- (void)updateETAForSearchResult:(id)arg1 calloutButton:(id)arg2 transportType:(unsigned long long)arg3;
- (void)directionsCalloutButtonTransportTypeForSearchResult:(id)arg1 context:(id)arg2 withCompletionHandler:(CDUnknownBlockType)arg3;
- (void)updateRatingsReviewsForSelection:(id)arg1 searchResult:(id)arg2 animated:(_Bool)arg3;
- (_Bool)_shouldShowFlyoverForLabel:(id)arg1 inContext:(id)arg2;
- (void)updateDirectionsCalloutButtonForContext:(id)arg1 selection:(id)arg2 searchResult:(id)arg3;
- (id)trafficViewControllerForTrafficIncidentAtLabelMarker:(id)arg1 inContext:(id)arg2;
- (void)viewModeDidChangeForContext:(id)arg1;
- (void)updateCalloutForSelectionInContext:(id)arg1;
- (void)_updateEntitiesForSearchResult:(id)arg1 withContext:(id)arg2 withError:(id)arg3;
- (void)noteSearchResultChanged:(id)arg1 forContext:(id)arg2;
- (void)handleDidFinishCalloutExpansionInContext:(id)arg1;
- (void)calloutDidAppearForSelection:(id)arg1 inContext:(id)arg2;
- (void)handleCalloutAccessoryTap:(id)arg1 onSelection:(id)arg2 inContext:(id)arg3;
- (void)handleDeselection:(id)arg1 inContext:(id)arg2;
- (void)handleSelection:(id)arg1 inContext:(id)arg2;
- (void)handleUserLocationUpdate:(id)arg1 inContext:(id)arg2;
- (void)dismissPlaceCardWithContext:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)dismissPlaceCardWithContext:(id)arg1;
- (void)presentViewControllerInContext:(id)arg1 withPlaceCardPresentation:(id)arg2 animated:(_Bool)arg3 changeHandler:(CDUnknownBlockType)arg4;
- (_Bool)isPresentingPlaceCard;
- (void)_doneButtonTapped;
- (void)presentPlaceCardInContext:(id)arg1 forSearchResult:(id)arg2 animated:(_Bool)arg3;
- (id)_mapSelection;
- (_Bool)_placeCardPresentationRequiresSelection;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

