//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RAPQuestion.h"

@class MKMapItem, NSArray, NSMutableDictionary, NSString, RAPCategory;

__attribute__((visibility("hidden")))
@interface RAPCategoryQuestion : RAPQuestion
{
    NSMutableDictionary *_categoriesByKind;
    NSArray *_selectableCategories;
    RAPCategory *_selectedCategory;
}

@property(retain, nonatomic) RAPCategory *selectedCategory; // @synthesize selectedCategory=_selectedCategory;
- (void).cxx_destruct;
- (id)_newCategoryOfKind:(long long)arg1;
@property(readonly, nonatomic) NSString *localizedCategoriesHeaderText;
- (id)_alternateMapViewContext;
- (_Bool)_isRecursivelyComplete;
- (_Bool)isComplete;
- (void)_fillSubmittableProblem:(id)arg1;
@property(readonly, nonatomic) NSArray *selectableCategories; // @synthesize selectableCategories=_selectableCategories;
- (_Bool)_canSegueToProblemWithDirections;
- (id)_categoryOfKind:(long long)arg1;
@property(readonly, nonatomic) NSString *snippetDirectionsEndWaypointTitle;
@property(readonly, nonatomic) NSString *snippetDirectionsStartWaypointTitle;
@property(readonly, nonatomic) MKMapItem *snippetMapItem;
@property(readonly, nonatomic) long long snippetKind;

@end

