//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RAPQuestion.h"

@class NSString, RAPCommentQuestion, RAPPlaceCorrectableString, RAPReportContext, VKLabelMarker;

__attribute__((visibility("hidden")))
@interface RAPLabelCorrectionsQuestion : RAPQuestion
{
    RAPPlaceCorrectableString *_correctableName;
    VKLabelMarker *_labelMarker;
    RAPCommentQuestion *_commentQuestion;
    RAPReportContext *_labelMarkerPickingMapContext;
}

@property(retain, nonatomic) RAPReportContext *labelMarkerPickingMapContext; // @synthesize labelMarkerPickingMapContext=_labelMarkerPickingMapContext;
@property(retain, nonatomic) VKLabelMarker *labelMarker; // @synthesize labelMarker=_labelMarker;
- (void).cxx_destruct;
@property(readonly, nonatomic) RAPCommentQuestion *commentQuestion; // @synthesize commentQuestion=_commentQuestion;
- (void)_fillSubmittableProblem:(id)arg1;
- (id)_alternateMapViewContext;
- (_Bool)isComplete;
@property(readonly, nonatomic) RAPPlaceCorrectableString *correctableName; // @synthesize correctableName=_correctableName;
@property(readonly, nonatomic) CDStruct_02837cd9 initialLabelMarkerPickingMapRect;
@property(readonly, nonatomic) NSString *localizedLabelMarkerPickingPrompt;

@end

