//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol RAPPlaceCorrectableItem <NSObject>
@property(nonatomic, getter=isMarkedWrong) _Bool markedWrong;
@property(readonly, nonatomic) long long kind;
@property(readonly, nonatomic, getter=isEdited) _Bool edited;
@property(readonly, nonatomic) NSString *localizedTitle;
- (void)revertCorrections;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1 changeHandler:(void (^)(id, id))arg2;
@end

