//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RAPTablePartSection.h"

@class NSArray, NSString;

__attribute__((visibility("hidden")))
@interface RAPTableCheckmarkRadioSection : RAPTablePartSection
{
    id _owner;
    Class _defaultCellClass;
    CDUnknownBlockType _dequeue;
    CDUnknownBlockType _configure;
    CDUnknownBlockType _selection;
    CDUnknownBlockType _presentOverflow;
    NSString *_overflowTitleNoValues;
    NSString *_overflowTitleWithValues;
    _Bool _selectedValueIsOverflowSelection;
    _Bool _isDequeueingCellForOverflowSelection;
    _Bool _showsOverflowCell;
    NSArray *_values;
    id _selectedValue;
}

@property(nonatomic) _Bool showsOverflowCell; // @synthesize showsOverflowCell=_showsOverflowCell;
@property(retain, nonatomic) id selectedValue; // @synthesize selectedValue=_selectedValue;
@property(copy, nonatomic) NSArray *values; // @synthesize values=_values;
- (void).cxx_destruct;
- (void)presentOverflow;
- (id)_effectiveOverflowCellTitle;
- (void)setOverflowCellTitle:(id)arg1 forDisplayWhenOtherValuesPresent:(_Bool)arg2;
- (id)overflowCellTitleWithOtherValuesPresent:(_Bool)arg1;
- (void)didSelectCellForRowAtIndex:(long long)arg1 tableIndexPath:(id)arg2;
- (id)cellForRowAtIndex:(long long)arg1;
- (long long)rowsCount;
- (void)configureCell:(id)arg1 forValue:(id)arg2;
- (void)configureCell:(id)arg1 forValue:(id)arg2 isOverflowSelection:(_Bool)arg3;
- (id)dequeueCellForValue:(id)arg1;
- (id)dequeueCellForValue:(id)arg1 isOverflowSelection:(_Bool)arg2;
- (void)registerReuseIdentifiersForCells;
- (void)selectedValueDidChange;
- (long long)_overflowSelectionCellIndex;
- (long long)_overflowCellIndex;
- (Class)defaultCellClass;
- (id)initWithOwner:(id)arg1 defaultCellClass:(Class)arg2 dequeueForValue:(CDUnknownBlockType)arg3 configureForValue:(CDUnknownBlockType)arg4 selection:(CDUnknownBlockType)arg5 presentOverflow:(CDUnknownBlockType)arg6;
- (id)init;

@end

