//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CollectionsTableViewControllerDelegate.h"

@class RecentsViewController, SearchResult;

@protocol RecentsViewControllerDelegate <CollectionsTableViewControllerDelegate>
- (_Bool)recentsViewControllerShouldPresentToOrFromSelectionAlert:(RecentsViewController *)arg1;
- (void)recentsViewController:(RecentsViewController *)arg1 choseBookmark:(SearchResult *)arg2;
- (void)recentsViewController:(RecentsViewController *)arg1 choseHistoryItem:(id <HistoryItem>)arg2;

@optional
- (void)recentsViewControllerDidSelectCollectionsButton:(RecentsViewController *)arg1;
- (void)recentsViewControllerDidDismissClearHistorySheet:(RecentsViewController *)arg1;
- (void)setSearchType:(int)arg1;
@end

