//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface RouteETA : NSObject
{
    double _distance;
    unsigned long long _transportType;
    double _travelTime;
}

+ (id)routeETAWithDistance:(double)arg1 travelTime:(double)arg2 transportType:(unsigned long long)arg3;
@property(readonly, nonatomic) double travelTime; // @synthesize travelTime=_travelTime;
@property(readonly, nonatomic) unsigned long long transportType; // @synthesize transportType=_transportType;
@property(readonly, nonatomic) double distance; // @synthesize distance=_distance;

@end

