//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TopBarTitleView.h"

@class MNRoute, NSString;

__attribute__((visibility("hidden")))
@interface RouteStartStepView : TopBarTitleView
{
    unsigned long long _alternateRoutesCount;
    unsigned long long _selectedAlternateRouteIndex;
    MNRoute *_selectedRoute;
    NSString *_destinationName;
}

@property(nonatomic) unsigned long long alternateRoutesCount; // @synthesize alternateRoutesCount=_alternateRoutesCount;
@property(retain, nonatomic) NSString *destinationName; // @synthesize destinationName=_destinationName;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)setRoute:(id)arg1 withIndex:(unsigned long long)arg2 destinationName:(id)arg3;
- (id)initWithFrame:(struct CGRect)arg1;

@end

