//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "MainChromeTopBarContent.h"

@class MainChromeViewController, NSString, PassthruSearchBar, UIButton, UIImage, UITextField;

__attribute__((visibility("hidden")))
@interface SearchBar : UIView <MainChromeTopBarContent>
{
    id <SearchBarDelegate> _delegate;
    UITextField *_searchField;
    PassthruSearchBar *_searchBar;
    UIButton *_directionsButton;
    UIButton *_shareButton;
    UIButton *_cancelButton;
    UIImage *_defaultClearButtonImage;
    UIImage *_defaultClearButtonPressedImage;
    long long _suspensionCount;
    long long _lightness;
    _Bool _didPerformInitialSetup;
    MainChromeViewController *_chromeViewController;
}

+ (id)shareButtonUsingGlyphs:(_Bool)arg1;
+ (id)directionsButtonUsingGlyphs:(_Bool)arg1;
+ (double)defaultHeight;
@property(nonatomic) MainChromeViewController *chromeViewController; // @synthesize chromeViewController=_chromeViewController;
@property(readonly, nonatomic) PassthruSearchBar *searchBar; // @synthesize searchBar=_searchBar;
@property(readonly, nonatomic) UITextField *searchField; // @synthesize searchField=_searchField;
@property(nonatomic) __weak id <SearchBarDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_updateSearchFieldAppearance;
- (void)setBackdropLightness:(long long)arg1 animation:(id)arg2;
- (void)endSuspendingTapDelegateMessages;
- (void)beginSuspendingTapDelegateMessages;
- (void)_cancelButtonTapped:(id)arg1;
- (void)_shareButtonTapped:(id)arg1;
- (void)_directionsButtonTapped:(id)arg1;
- (id)presentationSourceForShareSheet;
- (id)presentationSourceForDirectionsSearch;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)performInitialSetup;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

