//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SnapshotResponderProtocol.h"

@class MKMapSnapshot, MKMapSnapshotter, NSString, SearchResult, UIColor, UIImage;

__attribute__((visibility("hidden")))
@interface SearchResultCell : NSObject <SnapshotResponderProtocol>
{
    SearchResult *_searchResult;
    struct CGRect _frame;
    long long _page;
    long long _order;
    _Bool _hasSnapshot;
    MKMapSnapshot *_snapshot;
    MKMapSnapshotter *_snapshotter;
    UIColor *_blueTextColor;
    UIColor *_calloutTextColor;
}

+ (id)cellWithSearchResult:(id)arg1 order:(long long)arg2;
@property(readonly, nonatomic) _Bool hasSnapshot; // @synthesize hasSnapshot=_hasSnapshot;
@property(nonatomic) long long order; // @synthesize order=_order;
@property(nonatomic) long long page; // @synthesize page=_page;
@property(nonatomic) struct CGRect frame; // @synthesize frame=_frame;
@property(retain, nonatomic) SearchResult *searchResult; // @synthesize searchResult=_searchResult;
- (void).cxx_destruct;
- (struct CGPoint)transformedPoint:(struct CGAffineTransform)arg1;
- (void)dealloc;
- (void)releaseSnapshotCreator;
@property(readonly, nonatomic) UIImage *snapshotImage; // @dynamic snapshotImage;
- (CDUnknownBlockType)snapshotBlock;
- (void)drawInRect:(struct CGRect)arg1;
- (double)_textLayoutHeight;
- (void)_drawPinInRect:(struct CGRect)arg1 zoomLevel:(double)arg2;
@property(nonatomic) double y; // @dynamic y;
- (id)initWithSearchResult:(id)arg1 order:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

