//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MapPageRenderer.h"

@class NSArray, NSMutableArray;

__attribute__((visibility("hidden")))
@interface SearchResultsPageRenderer : MapPageRenderer
{
    NSArray *_searchResults;
    NSMutableArray *_searchResultCells;
    CDStruct_34734122 topLeftCorner;
    CDStruct_34734122 mlMapPoint;
    CDStruct_34734122 mrMapPoint;
}

- (void).cxx_destruct;
- (void)drawContentForPageAtIndex:(long long)arg1 inRect:(struct CGRect)arg2;
- (void)_drawPinsInRect:(struct CGRect)arg1 zoomLevel:(double)arg2;
- (void)drawTopContentInRect:(struct CGRect)arg1 forPageAtIndex:(long long)arg2;
- (struct CGRect)overviewRect;
- (long long)numberOfPages;
- (void)_preparePageContent;
- (long long)searchResultsPerPage;
- (void)prepareForDrawingPages:(struct _NSRange)arg1;
- (id)initWithSearchResults:(id)arg1 title:(id)arg2 subTitle:(id)arg3 mapView:(id)arg4;
- (double)_zoomLevelForCoordinateRegion:(CDStruct_02837cd9)arg1 clampTo:(double)arg2;

@end

