//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UITextFieldDelegate.h"

@class NSString, StarkDeleteFocusRingButton, StarkSearchField, UIButton;

__attribute__((visibility("hidden")))
@interface StarkSearchBarView : UIView <UITextFieldDelegate>
{
    _Bool _editing;
    _Bool _isRequiringVisibility;
    UIView *_backgroundView;
    StarkSearchField *_searchField;
    UIButton *_cancelButton;
    StarkDeleteFocusRingButton *_deleteButton;
    NSString *_searchTextBeforeEditingStarted;
    id <StarkSearchBarViewDelegate> _delegate;
    long long _lightLevel;
    long long _interactionModel;
}

@property(retain, nonatomic) UIButton *deleteButton; // @synthesize deleteButton=_deleteButton;
@property(nonatomic) long long interactionModel; // @synthesize interactionModel=_interactionModel;
@property(nonatomic) __weak id <StarkSearchBarViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSString *searchTextBeforeEditingStarted; // @synthesize searchTextBeforeEditingStarted=_searchTextBeforeEditingStarted;
- (void).cxx_destruct;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)_willChangeSearchTextToString:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)textFieldDidEndEditing:(id)arg1;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
@property(copy, nonatomic) NSString *searchText;
- (void)beginEditing;
- (void)_endEditingWithOutcome:(long long)arg1 searchTextForCommitting:(id)arg2;
- (void)cancelAndEndEditing;
- (void)_cancelAndEndEditingProgrammatically;
- (void)_deleteLastCharacter;
- (void)commitAndEndEditingWithSearchText:(id)arg1;
- (void)_moveViewsToFinalPosition;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)dealloc;
- (_Bool)isFirstResponder;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

