//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GEORouteMatch, StarkLikelyRouteUpdater;

@protocol StarkLikelyRouteUpdaterObserver <NSObject>
- (void)likelyRouteUpdaterArrived:(StarkLikelyRouteUpdater *)arg1;
- (void)likelyRouteUpdaterUpdatedETA:(StarkLikelyRouteUpdater *)arg1;
- (void)likelyRouteUpdater:(StarkLikelyRouteUpdater *)arg1 matchedToRoute:(GEORouteMatch *)arg2;
- (void)likelyRouteUpdaterRerouted:(StarkLikelyRouteUpdater *)arg1;
@end

