//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AuxiliaryDebugViewController.h"

#import "GEOResourceManifestTileGroupObserver.h"

@class GEOResourceManifestDownload, NSString;

__attribute__((visibility("hidden")))
@interface TileGroupInfoDebugController : AuxiliaryDebugViewController <GEOResourceManifestTileGroupObserver>
{
    _Bool _canChangeActiveTileGroup;
    id <MapsDebugViewControllerDelegate> _delegate;
    long long tileGroupIdentifier;
    GEOResourceManifestDownload *_resourceManifest;
}

+ (id)navigationDestinationTitle;
@property(nonatomic) _Bool canChangeActiveTileGroup; // @synthesize canChangeActiveTileGroup=_canChangeActiveTileGroup;
@property(retain, nonatomic) GEOResourceManifestDownload *resourceManifest; // @synthesize resourceManifest=_resourceManifest;
@property(nonatomic) long long tileGroupIdentifier; // @synthesize tileGroupIdentifier;
- (void)setDelegate:(id)arg1;
- (id)delegate;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)_resourceNames;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)_tileGroup;
- (void)dealloc;
- (id)initWithStyle:(long long)arg1;
- (void)resourceManifestManagerDidChangeActiveTileGroup:(id)arg1;
- (void)resourceManifestManagerWillChangeActiveTileGroup:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

