//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UILabel.h"

@class NSDictionary, NSString;

__attribute__((visibility("hidden")))
@interface TwoPartTopBarLabel : UILabel
{
    _Bool _willUpdateText;
    _Bool _separatorUsesSecondaryAttributes;
    long long _arrangement;
    NSString *_primaryText;
    NSString *_secondaryText;
    NSDictionary *_primaryTextAttributes;
    NSDictionary *_secondaryTextAttributes;
}

+ (void)getPrimaryText:(out id *)arg1 secondaryText:(id *)arg2 forRemainingDistance:(double)arg3 detail:(int)arg4;
+ (void)getPrimaryText:(out id *)arg1 secondaryText:(id *)arg2 forRemainingTimeInterval:(double)arg3;
+ (void)getDisplayValue:(out id *)arg1 displayValueIsSingular:(_Bool *)arg2 unit:(out unsigned long long *)arg3 forRemainingTimeInterval:(double)arg4;
+ (id)primaryTextForShortTimeWithoutAmPmForDate:(id)arg1 destinationTimezone:(id)arg2;
+ (void)_updateShortTimeFormatString;
+ (id)dateFormatterForShortTimeWithoutAmPm;
@property(nonatomic) _Bool separatorUsesSecondaryAttributes; // @synthesize separatorUsesSecondaryAttributes=_separatorUsesSecondaryAttributes;
@property(copy, nonatomic) NSString *secondaryText; // @synthesize secondaryText=_secondaryText;
@property(copy, nonatomic) NSString *primaryText; // @synthesize primaryText=_primaryText;
@property(nonatomic) long long arrangement; // @synthesize arrangement=_arrangement;
- (void).cxx_destruct;
@property(copy, nonatomic) NSDictionary *primaryTextAttributes; // @synthesize primaryTextAttributes=_primaryTextAttributes;
@property(copy, nonatomic) NSDictionary *secondaryTextAttributes; // @synthesize secondaryTextAttributes=_secondaryTextAttributes;
- (struct CGSize)intrinsicContentSize;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)updateText;
- (void)_setAttributedTextNeedsUpdate;
- (void)_updateAttributedText;

@end

