//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSThread, NSURL;

@interface Copier : NSObject
{
    NSURL *_sourceURL;
    NSURL *_destURL;
    NSString *_uniqueID;
    int _continue;
    NSThread *_thread;
    id _callbackTarget;
    SEL _callbackSelector;
    int _options;
}

+ (id)copierWithSourceURL:(id)arg1 uniqueIdentifier:(id)arg2 destURL:(id)arg3 callbackTarget:(id)arg4 selector:(SEL)arg5 options:(int)arg6;
+ (id)inboxPath;
+ (id)sharedInstance;
- (void)invalidate;
- (void)cancelCopy;
- (_Bool)startCopy;
- (void)_copyThread:(id)arg1;
- (_Bool)destroyTemporaryDirectory:(id)arg1 error:(id *)arg2;
- (id)createTemporaryDirectory:(id *)arg1;
- (id)uniquePathInDirectory:(id)arg1 sourceURL:(id)arg2;
- (id)identicalDocumentInDirectory:(id)arg1 sourceURL:(id)arg2 uniqueIdentifier:(id)arg3;
- (_Bool)isCandidateFileName:(id)arg1 forSourceFileName:(id)arg2;
- (_Bool)setUniqueIdentifier:(id)arg1 forPath:(id)arg2;
- (_Bool)fileName:(id)arg1 inDirectory:(id)arg2 hasUniqueIdentifier:(id)arg3;
- (_Bool)createDirectory:(id)arg1 error:(id *)arg2;
- (_Bool)validateSourceURLForMoving:(id)arg1 error:(id *)arg2;
- (_Bool)validateSourceURLForCopying:(id)arg1 error:(id *)arg2;
- (void)dealloc;
- (id)initWithSourceURL:(id)arg1 uniqueIdentifier:(id)arg2 destURL:(id)arg3 callbackTarget:(id)arg4 selector:(SEL)arg5 options:(int)arg6;

@end

