//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CDMEntity;

@interface IDECDDataModelEntityItem : NSObject
{
    CDMEntity *entity;
    BOOL shouldUse;
}

@property BOOL shouldUse; // @synthesize shouldUse;
@property(readonly) CDMEntity *entity; // @synthesize entity;
- (void).cxx_destruct;
- (id)initWithEntity:(id)arg1 shouldUse:(BOOL)arg2;

@end

