//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IDEDataModelEditor, NSArray, NSView;

@protocol IDEDataModelEditorController <NSObject>
- (void)takeFocus;
- (void)paste:(id)arg1;
- (void)copy:(id)arg1;
- (void)editNameForModelObject:(id <IDEDMModelObject>)arg1;
- (void)selectModelObjects:(NSArray *)arg1;

@optional
- (IDEDataModelEditor *)rootEditor;
- (NSView *)view;
- (NSArray *)selection;
- (void)invalidate;
- (void)setViewType:(int)arg1;
- (BOOL)allowsViewType:(int)arg1;
@end

