//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class _CPTapGuarded;

@protocol _ContainerStrategy <NSObject>
@property(readonly, getter=isSessionBased) BOOL sessionBased;
- (void)fetchFromTap:(id)arg1 guard:(_CPTapGuarded *)arg2;
- (void)unpauseTap:(id)arg1 guard:(_CPTapGuarded *)arg2;
- (void)pauseTap:(id)arg1 guard:(_CPTapGuarded *)arg2;
- (void)stopTap:(id)arg1 guard:(_CPTapGuarded *)arg2;
- (void)startTap:(id)arg1 guard:(_CPTapGuarded *)arg2;
- (void)receivedRecordContainers:(struct DTCoreProfileTapContainerRec *)arg1 count:(long long)arg2 guard:(_CPTapGuarded *)arg3;
- (void)setSessionHandler:(void (^)(struct _CPSession *))arg1 guard:(_CPTapGuarded *)arg2;
- (void)invokeClientHandlers:(id)arg1;
- (id)willInvokeClientHandlers:(_CPTapGuarded *)arg1;
- (void)reset:(_CPTapGuarded *)arg1;
@end

