__Z12extract_argsPU24objcproto13OS_xpc_object8NSObjectPKcPPS3_
__Z20_wait_for_child_exiti
__Z23_validate_authorizationPU24objcproto13OS_xpc_object8NSObject
__Z41_setup_posixspawn_attributes_file_actionsPU24objcproto13OS_xpc_object8NSObjectPPvS3_
__Z8get_argsPU24objcproto13OS_xpc_object8NSObjectPPKcPS4_S5_
__mh_execute_header
_main
