
/Applications/Xcode.app//Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/libTelephonyDebugDynamic.dylib (for architecture armv7):
_TelephonyBasebandWatchdogStart
_TelephonyBasebandWatchdogStartWithStackshot
_TelephonyBasebandWatchdogStop
__ZTINSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEEE
__ZTINSt3__119basic_ostringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE
__ZTSNSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEEE
__ZTSNSt3__119basic_ostringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE

/Applications/Xcode.app//Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/libTelephonyDebugDynamic.dylib (for architecture armv7s):
_TelephonyBasebandWatchdogStart
_TelephonyBasebandWatchdogStartWithStackshot
_TelephonyBasebandWatchdogStop
__ZTINSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEEE
__ZTINSt3__119basic_ostringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE
__ZTSNSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEEE
__ZTSNSt3__119basic_ostringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE

/Applications/Xcode.app//Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/libTelephonyDebugDynamic.dylib (for architecture arm64):
_TelephonyBasebandWatchdogStart
_TelephonyBasebandWatchdogStartWithStackshot
_TelephonyBasebandWatchdogStop
