//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIScrollViewDelegate.h"
#import "WeekViewAllDayContentsDelegate.h"

@class EKDayOccurrenceView, EKEvent, NSArray, NSCalendar, NSDateComponents, NSMutableArray, NSString, NSTimeZone, UIScrollView, UITapGestureRecognizer, WeekViewAllDayContents;

@interface WeekAllDayView : UIView <WeekViewAllDayContentsDelegate, UIScrollViewDelegate>
{
    NSDateComponents *_startDate;
    NSDateComponents *_endDate;
    unsigned long long _daysToDisplay;
    NSArray *_dayStarts;
    NSMutableArray *_layedOutRows;
    WeekViewAllDayContents *_contentView;
    UIScrollView *_scroller;
    NSArray *_dayNumberViews;
    NSArray *_dayNameLabels;
    NSArray *_verticalDaySeparators;
    UIView *_topSeparator;
    UIView *_bottomSeparator;
    EKEvent *_selectedEvent;
    EKEvent *_dimmedOccurrence;
    EKDayOccurrenceView *_selectedOccurrenceView;
    EKEvent *_scrollingToOccurrence;
    struct CGRect _latestVisibleRect;
    _Bool _needsHeaderUpdate;
    UITapGestureRecognizer *_tapGestureRecognizer;
    _Bool _showWeekNumbers;
    _Bool _showsHalfOfScrolledEvents;
    _Bool _allowsOccurrenceSelection;
    _Bool _receiveTapsInHeader;
    _Bool _usesSmallText;
    _Bool _leftMarginIncludesTimeView;
    _Bool _hideVerticalLinesInHeader;
    int _maxOccurrencesWithoutScroller;
    id <WeekAllDayViewDelegate> _delegate;
    NSCalendar *_calendar;
    double _fixedDayWidth;
    double _fixedDayHeight;
    long long _orientation;
    double _minimumHeight;
}

+ (double)dayLabelHeight;
+ (id)_todayDayLabelFont;
+ (id)_dayLabelFont;
+ (double)baselineForWeekdayLabels;
+ (double)_heightForWeekdayLabels;
+ (double)_yOffsetForWeekdayLabels;
+ (struct UIEdgeInsets)occurrencePadding;
@property(nonatomic) _Bool hideVerticalLinesInHeader; // @synthesize hideVerticalLinesInHeader=_hideVerticalLinesInHeader;
@property(retain, nonatomic) EKEvent *dimmedOccurrence; // @synthesize dimmedOccurrence=_dimmedOccurrence;
@property(nonatomic) _Bool leftMarginIncludesTimeView; // @synthesize leftMarginIncludesTimeView=_leftMarginIncludesTimeView;
@property(nonatomic) double minimumHeight; // @synthesize minimumHeight=_minimumHeight;
@property(nonatomic) long long orientation; // @synthesize orientation=_orientation;
@property(nonatomic) _Bool usesSmallText; // @synthesize usesSmallText=_usesSmallText;
@property(nonatomic) double fixedDayHeight; // @synthesize fixedDayHeight=_fixedDayHeight;
@property(nonatomic) double fixedDayWidth; // @synthesize fixedDayWidth=_fixedDayWidth;
@property(nonatomic) _Bool receiveTapsInHeader; // @synthesize receiveTapsInHeader=_receiveTapsInHeader;
@property(nonatomic) _Bool allowsOccurrenceSelection; // @synthesize allowsOccurrenceSelection=_allowsOccurrenceSelection;
@property(nonatomic) int maxOccurrencesWithoutScroller; // @synthesize maxOccurrencesWithoutScroller=_maxOccurrencesWithoutScroller;
@property(nonatomic) _Bool showsHalfOfScrolledEvents; // @synthesize showsHalfOfScrolledEvents=_showsHalfOfScrolledEvents;
@property(nonatomic) _Bool showWeekNumbers; // @synthesize showWeekNumbers=_showWeekNumbers;
@property(copy, nonatomic) NSCalendar *calendar; // @synthesize calendar=_calendar;
@property(copy, nonatomic) NSDateComponents *startDate; // @synthesize startDate=_startDate;
@property(nonatomic) __weak id <WeekAllDayViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)emptySpaceClickForCalendarWeekDayEventContent:(id)arg1 atPoint:(struct CGPoint)arg2;
- (void)dayOccurrenceViewClicked:(id)arg1 atPoint:(struct CGPoint)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (id)_numberOfDaysSortDescriptor;
- (id)_calendarOrderSortDescriptor;
- (long long)rowIndexOfOccurrence:(id)arg1;
- (double)_dateForPoint:(struct CGPoint)arg1;
- (void)layoutSubviews;
- (void)_updateHeaderViewsIfNeeded;
- (void)_setNeedsHeaderUpdate;
- (struct CGRect)_frameForOccurrenceBlock:(id)arg1 index:(unsigned long long)arg2;
- (double)nextAvailableOccurrenceViewYOriginForDay:(double)arg1;
@property(readonly, nonatomic) double firstEventYOffset;
- (unsigned long long)_calendarOrderForCalendar:(id)arg1;
- (long long)_dayIndexForToday;
- (struct CGSize)_circleSize;
- (id)_dayLabelColorAtDayIndex:(long long)arg1;
- (id)_dayLabelFontAtDayIndex:(long long)arg1;
- (struct CGRect)_weekdayFrameForDayIndex:(long long)arg1;
- (struct CGRect)_numberFrameForDayIndex:(long long)arg1;
- (void)_layoutVerticalDaySeparators;
- (void)_layoutDayNumberCells;
- (void)_layoutDayNameLabels;
- (void)_buildVerticalDaySeparators;
- (void)_buildDayNumberAndNameViews;
- (void)_tapReceived:(id)arg1;
- (double)_dayWidth;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
@property(readonly, nonatomic) double naturalHeight;
- (double)heightForNumberOfOccurrences:(unsigned long long)arg1;
- (id)_extractEventsEndingAfterTimeframeFrom:(id)arg1;
- (id)_extractEventsStartingBeforeTimeframeFrom:(id)arg1;
- (id)_sortBlocks:(id)arg1 intoRowsUsingDataFrom:(id)arg2;
- (void)setOccurrences:(id)arg1;
- (void)addViewToScroller:(id)arg1;
- (id)_getSortedBlocksFromOccurrenceBlocks:(id)arg1;
- (id)occurrenceViewForEvent:(id)arg1;
@property(readonly, nonatomic) NSArray *occurrenceViews;
- (void)selectEvent:(id)arg1;
- (_Bool)hasOccurrences;
- (id)selectedEvent;
- (void)setViewsDimmed:(_Bool)arg1 forEvent:(id)arg2;
- (void)scrollToEvent:(id)arg1 animating:(_Bool)arg2;
- (id)occurrenceViewForOccurrence:(id)arg1;
- (void)rectBecameVisible:(struct CGRect)arg1;
- (id)selectedOccurrenceView;
@property(copy, nonatomic) NSTimeZone *timeZone;
- (void)_computeDayStartsAndEndDate;
- (double)occurrenceHeight;
@property(nonatomic) struct CGPoint contentOffset;
- (void)showOverlayMonthInCellAtOffset:(double)arg1 animated:(_Bool)arg2;
- (void)_significantTimeChanged:(id)arg1;
- (void)_localeChanged:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 orientation:(long long)arg2 numberOfDaysToDisplay:(unsigned long long)arg3 opaque:(_Bool)arg4 backgroundColor:(id)arg5;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

