//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AnimationTest.h"

@class EKCalendarDate, YearViewController;

@interface YearToMonthAnimationTest : AnimationTest
{
    YearViewController *_yearViewController;
    EKCalendarDate *_initialDate;
}

- (void).cxx_destruct;
- (void)kickOffAnimation;
- (void)setUp;
- (id)notificationName;

@end

