//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CIFilter.h"

@class CIImage, NSNumber;

@interface DBGConstraintOutlineFilter : CIFilter
{
    CIImage *_inputImage;
    NSNumber *_backingScaleFactor;
    NSNumber *_selected;
}

@property(retain, nonatomic) NSNumber *selected; // @synthesize selected=_selected;
@property(retain, nonatomic) NSNumber *backingScaleFactor; // @synthesize backingScaleFactor=_backingScaleFactor;
@property(retain, nonatomic) CIImage *inputImage; // @synthesize inputImage=_inputImage;
- (void).cxx_destruct;
- (id)outputImage;
- (id)attributeKeys;

@end

