//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DBGMapBasedQuickLookProvider, MKMapView, NSDictionary;

@protocol DBGMapDataAndAnnotationProvider <NSObject>
- (void)cancel;
- (void)provideMapAnnotations:(MKMapView *)arg1;
- (void)provideMapData:(void (^)(DVTMutableOrderedDictionary *))arg1;
- (id)initWithQuickLookProvider:(DBGMapBasedQuickLookProvider *)arg1 options:(NSDictionary *)arg2;
@end

