//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DBGDataValue, NSDictionary, NSImage;

@protocol DBGNSImageProvider <NSObject>
@property(readonly) NSImage *image;
@property(readonly) BOOL hasImageBeenRetrieved;
- (void)cancel;
- (id)initWithDataValue:(DBGDataValue *)arg1 options:(NSDictionary *)arg2;
@end

