//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <DebuggerUI/DBGNode.h>

@class DBGHostNode, SCNMaterial, SCNNode;

@interface DBGTrueSpacingBox : DBGNode
{
    DBGNode *_boxNode;
    SCNNode *_boxBorderNode;
    SCNMaterial *_boxMaterial;
    DBGHostNode *_host;
}

@property __weak DBGHostNode *host; // @synthesize host=_host;
- (void).cxx_destruct;
- (void)setHidden:(BOOL)arg1 animated:(BOOL)arg2;
- (id)createBorderGeometryWithWidth:(double)arg1 height:(double)arg2 length:(double)arg3;
- (void)updateWithWidth:(double)arg1 height:(double)arg2 length:(double)arg3 chamferRadius:(double)arg4;
- (id)initWithWidth:(double)arg1 height:(double)arg2 length:(double)arg3 chamferRadius:(double)arg4;

@end

