//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSString, iCloudMonitor;

@protocol iCloudMonitorLineProcessor
- (void)monitor:(iCloudMonitor *)arg1 didReceiveResponseCode:(unsigned long long)arg2 response:(NSString *)arg3 forToken:(NSString *)arg4 responseContinues:(BOOL)arg5;
@end

