//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@class IDEShellCommandBreakpointAction;

@interface IDEShellCommandBreakpointActionEditor : NSViewController
{
    IDEShellCommandBreakpointAction *_action;
}

- (void).cxx_destruct;
- (void)chooseCommand:(id)arg1;
- (id)initWithAction:(id)arg1;

@end

