//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSProcessInfo.h"

@interface NSProcessInfo (PBXFoundationExtra)
- (id)darwinUserCacheDirectoryPath;
- (id)darwinUserTemporaryDirectoryPath;
- (id)darwinUserDirectoryPath;
- (id)shortGroupName;
- (id)shortUserName;
@end

