//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, XCMacroExpansionScope;

@interface PBXBuildContext : NSObject
{
    NSString *_baseDirectoryPath;
    XCMacroExpansionScope *_macroExpansionScope;
}

- (void).cxx_destruct;
- (id)absolutePathForPath:(id)arg1;
- (id)absoluteExpandedPathForString:(id)arg1;
- (BOOL)expandedBooleanValueForString:(id)arg1;
- (BOOL)expandedValueIsNonEmptyForString:(id)arg1;
- (id)expandedValueForString:(id)arg1;
- (void)_setMacroExpansionScope:(id)arg1;
- (id)macroExpansionScope;
- (void)setBaseDirectoryPath:(id)arg1;
- (id)baseDirectoryPath;
- (id)init;
- (id)valueForUndefinedKey:(id)arg1;

@end

