//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class PBXCStringPool;

@interface PBXHeaderMap : NSObject
{
    PBXCStringPool *_stringPool;
    struct PBXHeaderMapBucket *_buckets;
    unsigned long long _capacity;
    unsigned long long _count;
    unsigned long long _maxValueLength;
}

- (void).cxx_destruct;
- (void)setValuePrefixCStr:(const char *)arg1 suffixCStr:(const char *)arg2 forKeyCStr:(const char *)arg3 replaceExisting:(BOOL)arg4;
- (void)printStatistics;
- (id)asciiData;
- (id)data;
- (unsigned long long)numEntries;
- (id)pathForHeaderNamed:(id)arg1;
- (void)markKeyAsDuplicate:(id)arg1;
- (id)allValues;
- (void)addEntriesFromHeaderMap:(id)arg1 replaceExisting:(BOOL)arg2;
- (void)addEntriesToHeaderMap:(id)arg1 replaceExisting:(BOOL)arg2;
- (void)setValuePrefix:(id)arg1 suffix:(id)arg2 forKey:(id)arg3;
- (void)setValuePrefix:(id)arg1 suffix:(id)arg2 forKey:(id)arg3 replaceExisting:(BOOL)arg4;
- (void)_growIfNeeded;
- (void)dealloc;
- (id)init;
- (id)initWithCapacity:(unsigned long long)arg1;

@end

