//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class XCDependencyNode;

@interface XCDepGraphNodeState : NSObject
{
    XCDependencyNode *_node;
    unsigned int _options;
    int _errno;
    unsigned int _mtime;
    unsigned int _size;
    unsigned short _mode;
    short _retainCount;
}

+ (id)currentStateWithNode:(id)arg1 options:(unsigned long long)arg2;
- (void).cxx_destruct;
- (id)description;
- (id)stateDescription;
- (BOOL)isValid;
- (void)invalidate;
- (BOOL)isCompatibleWithOptions:(unsigned long long)arg1;
- (id)dependencyGraph;
- (BOOL)isEqualToNodeState:(id)arg1;
- (unsigned short)mode;
- (long long)size;
- (long long)mtime;
- (int)errorNumber;
- (unsigned long long)options;
- (id)node;
- (id)init;
- (id)initWithNode:(id)arg1 options:(unsigned long long)arg2 error:(int)arg3 mtime:(unsigned int)arg4 size:(unsigned int)arg5 mode:(unsigned short)arg6;

@end

