//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DVTModelObject.h"

#import "DVTInvalidation.h"
#import "IDEBlueprint.h"
#import "IDEIndexable.h"
#import "Xcode3SourceListItemEditing.h"

@class DVTStackBacktrace, DVTToolsVersion, IDEActivityLogSection, IDETestBlueprintHostSettings, NSArray, NSDictionary, NSMapTable, NSMutableArray, NSMutableDictionary, NSSet, NSString, PBXTarget, Xcode3Project;

@interface Xcode3Target : DVTModelObject <IDEBlueprint, IDEIndexable, Xcode3SourceListItemEditing, DVTInvalidation>
{
    PBXTarget *_pbxTarget;
    Xcode3Project *_project;
    NSArray *_buildables;
    NSArray *_buildableProducts;
    id <IDEBuildable> _primaryBuildable;
    NSMutableDictionary *_productHeaders;
    NSString *_cachedIdentifier;
    NSString *_cachedIndexName;
    id _fileWasAddedNotificationObservingToken;
    id _fileWillBeRemovedNotificationObservingToken;
    id _fileWasRenamedNotificationObservingToken;
    id _fileWasAddedToGroupNotificationObservingToken;
    id _fileWillBeRemovedFromGroupNotificationObservingToken;
    id _targetSettingsDidChangeNotificationObservingToken;
    id _projectIntegrityLogDidChangeNotificationObservingToken;
    id _targetProductSettingsDidChangeNotificationObservingToken;
    id _buildOperationDidStopNotificationObservingToken;
    id _targetNameDidChangeNotificationObservingToken;
    IDEActivityLogSection *_integrityLog;
    NSMutableArray *_watchedFilesForIntegrityLog;
    id <IDEIndexable> _proxy;
    BOOL _headermapsUpToDate;
    BOOL _integrityCheckingBlockQueued;
    NSSet *_allPublicHeaderFileReferences;
    NSSet *_allPrivateHeaderFileReferences;
    NSSet *_allProjectHeaderFileReferences;
    NSMapTable *_extraSettingsCompletionBlocks;
    id <IDECapabilitiesContextProviding><IDEPortalInfoDelegate><IDECodesigningInfoDelegate><DVTInvalidation> _capabilitiesContext;
}

+ (id)deserializedSourceListItem:(id)arg1;
+ (id)pasteboardDataType;
+ (id)appCategoryDisplayValues;
+ (id)validAppCategories;
+ (id)keyPathsForValuesAffectingName;
+ (id)keyPathsForValuesAffectingLatestBuildLogSection;
+ (id)supportedSourceListItemEditorClasses;
+ (void)initialize;
@property(retain) id <IDECapabilitiesContextProviding><IDEPortalInfoDelegate><IDECodesigningInfoDelegate><DVTInvalidation> capabilitiesContext; // @synthesize capabilitiesContext=_capabilitiesContext;
@property(nonatomic) __weak id <IDEIndexable> proxy; // @synthesize proxy=_proxy;
@property(retain) IDEActivityLogSection *integrityLog; // @synthesize integrityLog=_integrityLog;
@property(readonly) Xcode3Project *project; // @synthesize project=_project;
@property(retain) PBXTarget *pbxTarget; // @synthesize pbxTarget=_pbxTarget;
- (void).cxx_destruct;
- (id)entitlementsFilePathForBuildConfiguration:(id)arg1;
- (void)_respondToProjectIntegrityLogDidChangeNotification:(id)arg1;
- (void)_respondToBuildOperationDidStopNotification:(id)arg1;
- (void)_respondToTargetNameDidChangeNotification:(id)arg1;
- (void)_respondToTargetProductSettingsDidChangeNotification:(id)arg1;
- (void)_respondToTargetSettingsDidChangeNotification:(id)arg1;
- (void)_respondToFileWillBeRemovedFromGroupNotification:(id)arg1;
- (void)_respondToFileWasAddedToGroupNotification:(id)arg1;
- (void)_respondToFileRenamedNotification:(id)arg1;
- (void)_respondToBuildFileRemovedNotification:(id)arg1;
- (void)_respondToBuildFileAddedNotification:(id)arg1;
- (id)serializedSourceListItem;
- (id)toolSearchPathWithBuildParameters:(id)arg1;
- (id)stringsByEvaluatingPropertyString:(id)arg1 inAllConfigurationsForWorkspaceArenaSnapshot:(id)arg2;
- (id)absolutePathByEvaluatingBuildSettingExpressionString:(id)arg1 withBuildParameters:(id)arg2;
- (id)stringByEvaluatingBuildSettingExpressionString:(id)arg1 withBuildParameters:(id)arg2;
- (id)evaluatedStringListValueForBuildSetting:(id)arg1 withBuildParameters:(id)arg2;
- (id)evaluatedStringValueForBuildSetting:(id)arg1 withBuildParameters:(id)arg2;
- (id)allBuildSettingNamesWithBuildParameters:(id)arg1;
- (id)productType;
- (id)productNameWithBuildSetting:(id)arg1 workspace:(id)arg2;
- (id)buildSettingsForMainFile:(id)arg1 workspace:(id)arg2;
- (id)localizedIndexableDescription;
- (void)languageOfMainFile:(id)arg1 workspace:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (BOOL)writeProductHeaders:(id)arg1 toFile:(id)arg2 error:(id *)arg3;
- (void)productHeadersInWorkspace:(id)arg1 withCompletionBlock:(CDUnknownBlockType)arg2;
- (void)settingsForFilesInWorkspace:(id)arg1 shouldWriteAuxiliaryFiles:(BOOL)arg2 withCompletionBlock:(CDUnknownBlockType)arg3;
- (void)settingsForFilesInWorkspace:(id)arg1 withCompletionBlock:(CDUnknownBlockType)arg2;
- (void)_validateBuildParametersForIndexingOrRefactoring:(id)arg1;
- (id)_buildParametersForIndexingInWorkspace:(id)arg1;
- (id)_bestSchemeForWorkspace:(id)arg1;
- (BOOL)_isPartOfScheme:(id)arg1;
- (void)_performDependentBlock:(CDUnknownBlockType)arg1;
- (id)indexableFiles;
- (id)_targetBuildContext;
- (BOOL)_projectIsValid;
- (id)containerForIndexables:(id)arg1 rootPaths:(id)arg2;
- (id)indexName;
- (BOOL)requiresMainThread;
- (id)identifier;
- (void)_indexingRespondToFileRenamedNotification:(id)arg1;
- (void)_indexingRespondToVariantGroupNotification:(id)arg1 withNewName:(id)arg2;
- (void)_indexingRespondToBuildFileNotification:(id)arg1 withNewName:(id)arg2;
- (void)clearCachedBuildSettings;
- (void)analyzeModelIntegrity;
- (id)bundleBaselineRecordFilePathWithError:(id *)arg1;
@property(copy) NSString *developmentTeam;
@property(readonly, getter=isUnitTest) BOOL unitTest;
@property(retain) IDETestBlueprintHostSettings *testBlueprintHostSettings;
- (id)additionalOverridingCompilerArgumentsForSourceCodeBuildFileReference:(id)arg1;
- (void)setOverridingAdditionalCompilerArguments:(id)arg1 forSourceCodeBuildFileReference:(id)arg2;
- (id)additionalCompilerArgumentsForSourceCodeBuildFileReference:(id)arg1;
- (void)setAdditionalCompilerArguments:(id)arg1 forSourceCodeBuildFileReference:(id)arg2;
- (id)_pbxBuildFileForFileReference:(id)arg1;
- (id)linkedBinaries;
- (id)allProjectHeaderFiles;
- (id)allPrivateHeaderFiles;
- (id)allPublicHeaderFiles;
- (void)cachePublicPrivateProjectHeaders;
- (int)visibilityOfHeaderBuildFile:(id)arg1;
- (id)sourceCodeBuildFileReferences;
- (id)allBuildFileReferences;
- (BOOL)configureToBuildMixedTargetWithDestinationGroup:(id)arg1 configureBridgingHeader:(BOOL)arg2 returningErrorString:(id *)arg3;
- (BOOL)isConfiguredToBuildMixedTarget;
- (BOOL)wouldBecomeMixedTargetAfterAddingTypes:(id)arg1;
- (BOOL)wouldBecomeMixedTargetAfterAddingFiles:(id)arg1;
- (BOOL)canUseBridgingHeader;
- (BOOL)isMixedTarget;
- (id)predominantSourceCodeLanguage;
- (BOOL)configureToBuildWithOptimizationProfileReturningErrorString:(id *)arg1;
- (BOOL)isConfiguredToBuildWithOptimizationProfile;
- (void)convertToUseModernObjCSyntax;
- (void)convertToUseARC;
- (void)_updateSDKIfNeeded;
- (void)_updateSDKIfNeededInConfigurations:(id)arg1;
- (void)_updateMacDeploymentTargetIfNeeded:(id)arg1;
- (BOOL)canConvertToUseARC;
- (void)convertToBuild64bitOnly;
- (void)convertToUseClang;
- (void)addFileReference:(id)arg1 toBuildablesContainingFileReference:(id)arg2;
- (id)compilerSpecificationIdentifier;
- (id)customDataStore;
- (id)supportedPlatformsForConfiguration:(id)arg1 workspaceArenaSnapshot:(id)arg2;
- (id)supportedPlatformsForBuildParameters:(id)arg1;
- (id)availableArchitecturesForConfiguration:(id)arg1 workspaceArenaSnapshot:(id)arg2;
- (id)availableArchitecturesForBuildParameters:(id)arg1;
- (id)defaultConfigurationName;
- (id)availableConfigurationNames;
- (id)buildableProducts;
- (id)buildables;
- (id)primaryBuildable;
- (id)buildableForIdentifier:(id)arg1;
@property(readonly, copy) NSString *blueprintIdentifier;
- (id)localizedDescription;
- (id)blueprintProvider;
- (void)setName:(id)arg1;
@property(readonly) NSString *name;
- (id)ideModelObjectTypeIdentifier;
@property(readonly, copy) NSString *description;
- (BOOL)containsFilePath:(id)arg1;
- (BOOL)containsFileReference:(id)arg1;
@property(readonly) DVTToolsVersion *createdOnToolsVersion;
@property(readonly) NSString *iconPath;
@property(readonly) NSString *infoPlistFilePath;
@property(readonly) NSSet *pathsOfFilesInCopyFilesBuildPhases;
@property(readonly) NSSet *pathsOfFilesInLinkedBinariesPhase;
@property(readonly) NSSet *namesOfLinkedBinaries;
@property(readonly) NSDictionary *targetProductInfo;
- (id)specifiedBaseSDKForBuildConfigurationName:(id)arg1;
- (id)baseSDKForBuildConfigurationName:(id)arg1;
- (id)deviceSDKFor:(id)arg1 SDKs:(id)arg2;
- (id)simulatorSDKFor:(id)arg1 SDKs:(id)arg2;
- (void)primitiveInvalidate;
- (id)initWithTarget:(id)arg1 project:(id)arg2;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)infoPlistFileReference;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

