//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <DevToolsCore/XCWorkQueueCommandSubprocessInvocation.h>

@interface XCWorkQueueCommandLocalSubprocessInvocation : XCWorkQueueCommandSubprocessInvocation
{
    int _processID;
    BOOL _mightHaveMoreOutput;
    int _outputFD;
    int _inputFD;
    BOOL _isCancelled;
}

+ (void)initialize;
- (void)setIsCancelled:(BOOL)arg1;
- (BOOL)isCancelled;
@property BOOL mightHaveMoreOutput; // @synthesize mightHaveMoreOutput=_mightHaveMoreOutput;
@property int processID; // @synthesize processID=_processID;
@property int inputFileDescriptor; // @synthesize inputFileDescriptor=_inputFD;
@property int outputFileDescriptor; // @synthesize outputFileDescriptor=_outputFD;
- (void)killSubprocess;
- (void)handleInputFileDescriptorActivity;
- (void)handleOutputFileDescriptorActivity;
- (void)handleEndOfOutput;
- (void)reapExitedSubprocess;
- (BOOL)launchSubprocessWithArguments:(const char **)arg1 environment:(const char **)arg2 workingDirectory:(const char *)arg3;
- (BOOL)isRunning;
- (void)dealloc;
- (id)initWithWorkQueueCommand:(id)arg1 arguments:(id)arg2 environmentAssignments:(id)arg3 workingDirectoryPath:(id)arg4 searchPath:(id)arg5;

@end

