//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JNFTypeCoercion.h"

@interface JNFVectorCoercion : NSObject <JNFTypeCoercion>
{
}

- (struct _jobject *)coerceNSObject:(id)arg1 withEnv:(const struct JNINativeInterface_ **)arg2 usingCoercer:(id)arg3;
- (id)coerceJavaObject:(struct _jobject *)arg1 withEnv:(const struct JNINativeInterface_ **)arg2 usingCoercer:(id)arg3;

@end

