//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FirenzeArchiveExpander, NSMutableArray, NSString, PurpleApplicationArchiveExpander;

@interface ITunesPurpleProductMetadataDescriber : NSObject
{
    PurpleApplicationArchiveExpander *_expander;
    FirenzeArchiveExpander *_macExpander;
    NSMutableArray *_iconFiles;
    NSMutableArray *_resourceSpecifications;
    NSString *_path;
    NSString *_extractionPath;
}

+ (void)initialize;
@property(retain, nonatomic) NSString *extractionPath; // @synthesize extractionPath=_extractionPath;
@property(retain, nonatomic) NSString *path; // @synthesize path=_path;
- (id)describeArchiveWithErrors:(id *)arg1;
- (id)describeVersionAsPlist;
- (id)describePurpleArchiveWithErrors:(id *)arg1;
- (id)describeFirenzeArchiveWithErrors:(id *)arg1;
- (id)describeWithErrors:(id *)arg1;
- (id)describeProductMetadataAtPath:(id)arg1 productutilOutput:(id)arg2;
- (id)describePackageAtPath:(id)arg1 payloadPaths:(id)arg2;
- (void)describeBundlesAtPath:(id)arg1 context:(id)arg2;
- (id)createBundleAndAddExecutable:(id)arg1 parentContext:(id)arg2;
- (void)determineBundlePayloadPath:(id)arg1 parentContext:(id)arg2;
- (void)determinePayloadPath:(id)arg1 parentContext:(id)arg2;
- (id)describeBundle:(id)arg1 context:(id)arg2;
- (id)signingAnalysis:(id)arg1 withError:(id *)arg2;
- (void)describeFilesAtPath:(id)arg1 context:(id)arg2;
- (void)determineIfFileOfInterest:(id)arg1 context:(id)arg2 isDirectory:(BOOL)arg3 bundleExecutables:(id)arg4;
- (void)checkBundleExecutable:(id)arg1 bundleExecutables:(id)arg2 context:(id)arg3;
- (BOOL)foundPath:(id)arg1 inBundleExecutables:(id)arg2;
- (void)checkFrameworkFilesOnFile:(id)arg1;
- (void)determineIfWeShouldIncludeFileData:(id)arg1;
- (void)checkFileIsExecutable:(id)arg1;
- (void)checkExternalAttributesOnFile:(id)arg1;
- (void)checkHasExtendedAttributesOnFile:(id)arg1;
- (void)checkHasResourceForkOnFile:(id)arg1;
- (void)checkHasACLOnFile:(id)arg1;
- (void)checkResourceSpecifications:(id)arg1 context:(id)arg2;
- (void)checkIncludedImagesOnFile:(id)arg1;
- (void)checkFilenameOnFile:(id)arg1;
- (void)dealloc;
- (id)initWithPath:(id)arg1;
- (id)init;

@end

