//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ITunesSoftwareService/ITunesAbstractPurpleSoftwareDescriberContext.h>

@class MZToolExecutorResult, NSDictionary, NSMutableArray, NSNumber, NSString;

@interface ITunesPurpleProductMetadataDescriberContext : ITunesAbstractPurpleSoftwareDescriberContext
{
    NSNumber *_archiveBytes;
    NSString *_fileName;
    NSMutableArray *_packages;
    NSDictionary *_productutilOutput;
    MZToolExecutorResult *_xarCommandResult;
}

+ (id)uniqueErrorCodes;
+ (id)context;
+ (void)initialize;
+ (id)defaultCodesToUnique;
@property(retain, nonatomic) MZToolExecutorResult *xarCommandResult; // @synthesize xarCommandResult=_xarCommandResult;
- (id)describeAsPlist;
- (id)describeVersionAsPlist;
- (id)describeXarResultAsPlist:(id)arg1;
- (void)mergeFromDictionary:(id)arg1 intoDictionary:(id *)arg2;
- (id)describeAllWarnings;
- (id)describeAllErrors;
- (id)uniqueErrors:(id)arg1;
- (void)mergeFromArray:(id)arg1 intoArray:(id *)arg2;
- (void)addPackage:(id)arg1;
- (id)packages;
- (void)setProductutilOutput:(id)arg1;
- (id)productutilOutput;
- (void)setFileName:(id)arg1;
- (id)fileName;
- (void)setArchiveBytes:(id)arg1;
- (id)archiveBytes;
- (id)xcodeVersions;
- (id)xcodeVersionDictionaryWithVersion:(id)arg1 path:(id)arg2;
- (id)versionPathWithBundlePath:(id)arg1;
- (id)versionDictionaryWithPath:(id)arg1;
- (id)osVersion;
- (id)toolVersion;
- (void)dealloc;
- (id)init;

@end

