//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface _XRCLIPSDebuggerChooserState : NSObject
{
    NSArray *_debuggerStatesByID;
}

@property(retain, nonatomic) NSArray *debuggerStatesByID; // @synthesize debuggerStatesByID=_debuggerStatesByID;
- (void).cxx_destruct;
- (id)init;

@end

