//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSString, PFTTableHeaderCell;

@interface PFTHeadlineView : NSView
{
    NSString *_title;
    PFTTableHeaderCell *_headerCell;
}

+ (void)initialize;
- (void)drawRect:(struct CGRect)arg1;
- (id)title;
- (void)setTitle:(id)arg1;
- (BOOL)isFlipped;
- (void)dealloc;

@end

