//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PFTNibView.h"

@class NSButton, NSString, NSTextField, PFTLCDField;

@interface PFTMiniDisplay : PFTNibView
{
    NSTextField *_title;
    PFTLCDField *_lcdField;
    NSButton *_appButton;
    NSButton *_stopButton;
    NSString *_documentUuid;
}

- (void)recordTrace:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)checkStateForCommand:(id)arg1;
- (void)_commandDidEnd:(id)arg1;
- (void)_commandDidStart:(id)arg1;
- (id)document;
- (void)viewDidMoveToWindow;
- (void)dealloc;
- (id)initWithDocumentUUID:(id)arg1;

@end

