//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSScrollView.h"

@class NSView;

@interface PFTScrollView : NSScrollView
{
    NSScrollView *_scrollSibling;
    BOOL _scrollingPeer;
    BOOL _ignoreScrollWheelEvents;
    double _minHeight;
    NSView *_horizontalScrollerViewToAvoid;
}

- (void)viewDidMoveToWindow;
- (void)awakeFromNib;
- (void)_doScroller:(id)arg1 hitPart:(long long)arg2 multiplier:(double)arg3;
- (double)_repeatMultiplier:(double)arg1;
- (void)scrollWheel:(id)arg1;
- (BOOL)ignoreScrollWheelEvents;
- (void)setIgnoreScrollWheelEvents:(BOOL)arg1;
- (void)setFrameSize:(struct CGSize)arg1;
- (void)setMinHight:(double)arg1;
- (void)tile;
- (void)reflectScrolledClipView:(id)arg1;
- (BOOL)_ownsWindowGrowBox;

@end

