//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface XRDecoration : NSObject
{
    struct CGRect _location;
    long long _identifier;
    BOOL _isRendered;
    unsigned long long _decoratorIndex;
}

- (void)drawInContext:(struct CGContext *)arg1;
- (void)setDecoratorIndex:(unsigned long long)arg1;
- (long long)compareXPosition:(id)arg1;
- (id)initWithLocation:(struct CGRect)arg1 identifier:(long long)arg2 decoratorIndex:(unsigned long long)arg3;

@end

