//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsKit/XRGesture.h>

@interface XRGestureNonAccepting : XRGesture
{
}

- (id)gestureWithEvent:(id)arg1 fromView:(id)arg2;
- (id)initWithStartingX:(double)arg1 lastX:(double)arg2;

@end

