//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

#import "DVTWindowActivationStateObserver.h"

@class NSString;

@interface XRStrategiesToolbarView : NSView <DVTWindowActivationStateObserver>
{
    id <DVTCancellable> _windowActivationObservation;
}

+ (id)_colorForLightSeparatorLineShadowIsMain:(BOOL)arg1;
+ (id)_colorForLightSeparatorLineIsMain:(BOOL)arg1;
- (void).cxx_destruct;
- (id)_toolbarBaselineColorForceMain:(BOOL)arg1;
- (void)updateLayer;
- (BOOL)wantsUpdateLayer;
- (BOOL)wantsLayer;
- (BOOL)isFlipped;
- (void)window:(id)arg1 didChangeActivationState:(long long)arg2;
- (void)viewWillMoveToWindow:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

