//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSPathComponentCell.h"

@interface XRTargetChooserPathComponentCell : NSPathComponentCell
{
    BOOL _isFirstItem;
    BOOL _isLastItem;
    BOOL _isOffline;
    int _gradientStyle;
}

+ (id)_textDrawingAttributes;
@property int gradientStyle; // @synthesize gradientStyle=_gradientStyle;
@property BOOL isOffline; // @synthesize isOffline=_isOffline;
@property BOOL isLastItem; // @synthesize isLastItem=_isLastItem;
@property BOOL isFirstItem; // @synthesize isFirstItem=_isFirstItem;
- (void)drawInteriorWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (id)_attributedStringValue:(BOOL)arg1;
- (id)shadow;
- (void)drawWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (double)_textOffsetForIcon:(id)arg1 inFrame:(struct CGRect)arg2 doDraw:(BOOL)arg3 isActive:(BOOL)arg4;
- (double)_rightDividerWidth;
- (double)_leftDividerWidth;
- (void)_drawDividerForFrame:(struct CGRect)arg1 inControlView:(id)arg2;
- (BOOL)_isActiveWindow:(id)arg1;
- (void)_useChevronForLeftEdge:(char *)arg1 rightEdge:(char *)arg2;
- (struct CGSize)cellSizeForBounds:(struct CGRect)arg1;
- (double)iconSize;

@end

