//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSArrayController.h"

@class NSArray, NSTableView, XREventIDProxyArray, XRManagedIDArray, XRStorageManager;

@interface XRManagedEventArrayController : NSArrayController
{
    XRStorageManager *_storageManager;
    XRManagedIDArray *_contentIDs;
    XREventIDProxyArray *_proxyArray;
    struct XRTimeRange _filterTimeRange;
    CDUnknownBlockType _filterBlock;
    CDUnknownBlockType _destructorBlock;
    XREventIDProxyArray *_idArrangedCache;
    NSTableView *_scrolledTable;
    NSArray *_tokens;
    CDUnknownBlockType *_tokenCompositions;
    unsigned int _compCount;
    BOOL _logicalOR;
    BOOL _discardIDSelection;
    CDUnknownBlockType _compositionDestructor;
}

@property(retain, nonatomic) XREventIDProxyArray *arrangedCache; // @synthesize arrangedCache=_idArrangedCache;
@property(retain, nonatomic) XRStorageManager *storageManager; // @synthesize storageManager=_storageManager;
- (void)applyCompositeFilter;
- (void)_appendDestructorBlock:(CDUnknownBlockType)arg1;
- (void)_addTest:(CDUnknownBlockType)arg1 toIndex:(unsigned long long)arg2;
- (void)addTestForToken:(id)arg1 test:(CDUnknownBlockType)arg2 destructor:(CDUnknownBlockType)arg3;
- (void)addGlobalTest:(CDUnknownBlockType)arg1 destructor:(CDUnknownBlockType)arg2;
- (void)setupCompositeFilterWithTokens:(id)arg1 requireAllTokensMatch:(BOOL)arg2;
- (void)selectEventWithIdentifier:(unsigned int)arg1;
- (void)selectEventNearestTimestamp:(unsigned long long)arg1;
- (void)setAutomaticSelectionScrollInTableView:(id)arg1;
- (void)setPreservesSelection:(BOOL)arg1;
- (void)setPreservesIDSelection:(BOOL)arg1;
- (void)enumerateArrangedEventsAtIndexes:(id)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (unsigned int)identifierAtArrangedIndex:(unsigned long long)arg1;
- (unsigned long long)arrangedIndexOfIdentifier:(unsigned int)arg1;
- (CDUnknownBlockType)filterBlock;
- (void)setFilterBlock:(CDUnknownBlockType)arg1 destructor:(CDUnknownBlockType)arg2;
- (id)_kFilteredArray:(id)arg1;
- (void)setSelectedTimeRange:(struct XRTimeRange)arg1;
- (id)arrangeObjects:(id)arg1;
- (void)rearrangeObjects;
- (void)setFilterPredicate:(id)arg1;
- (void)setSortDescriptors:(id)arg1;
- (void)_doAndMaintainSelection:(CDUnknownBlockType)arg1;
- (void)_scrollToRow:(long long)arg1;
- (id)content;
- (id)contentIDs;
- (void)setContentIDs:(id)arg1;
- (void)_refreshProxyArray;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)initWithContent:(id)arg1;
- (id)init;

@end

