//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <MTLToolsServices/DYMTLResourceObject.h>

@interface DYMTLComputePipelineState : DYMTLResourceObject
{
    unsigned long long _function;
}

@property(readonly, nonatomic) unsigned long long function; // @synthesize function=_function;
- (id)initWithProperties:(id)arg1;
- (id)initWithResourceObject:(id)arg1 functionStream:(id)arg2 dataResolver:(CDUnknownBlockType)arg3;

@end

