__OAAttachAndInitialize
__OARecordAllocationEvent
__OARecordReferenceEvent
__OASetLastAllocationEventName
___OAExcludeMachThreadID
___OASharedMemoryAddress
_oainjectVersionNumber
_oainjectVersionString
