//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSBox, NSButton, NSProgressIndicator, NSString, NSTextField;

@interface WorkItemDisplayController : NSObject
{
    NSProgressIndicator *progressIndicator;
    NSTextField *statusMessageField;
    NSTextField *statusField;
    NSTextField *remainingField;
    NSTextField *remainingModeField;
    NSButton *cancelButton;
    NSBox *_container;
    NSString *_statusMessage;
    id <MZWorkItem> _item;
}

+ (id)duplicatePrototype;
+ (id)serializedPrototype;
+ (id)containerPrototype;
+ (void)setContainerPrototype:(id)arg1;
- (void)cancel:(id)arg1;
- (void)update;
- (void)setItem:(id)arg1;
- (id)item;
- (id)container;
- (void)dealloc;
- (void)awakeFromNib;
- (id)initWithWorkItem:(id)arg1;
- (id)init;
- (void)initializeUserInterface;
- (void)clearInterface;
- (void)bindFieldsFromPrototype:(id)arg1 progressIndicator:(id *)arg2 status:(id *)arg3 statusMessage:(id *)arg4 timeRemaining:(id *)arg5 remainingMode:(id *)arg6 cancelButton:(id *)arg7;

@end

