//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSURLStorageTask.h"

@class NSURLStorageURLCacheDB;

__attribute__((visibility("hidden")))
@interface NSURLStorageTaskShrink : NSURLStorageTask
{
    NSURLStorageURLCacheDB *_cacheDBInstanceToUpdate;
}

- (void).cxx_destruct;
- (void)setCacheDBInstanceToUpdateAfterShrink:(id)arg1;
- (void)run;
- (id)initWithTaskManager:(id)arg1;

@end

