//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GKMatchRequest, GKMultiplayerP2PViewController, GKPlayerInternal, NSData, NSError;

@protocol GKMultiplayerP2PViewControllerDelegate <NSObject>
- (void)multiplayerP2PViewController:(GKMultiplayerP2PViewController *)arg1 sendData:(NSData *)arg2;
- (void)multiplayerP2PViewController:(GKMultiplayerP2PViewController *)arg1 cancelInviteToPlayer:(GKPlayerInternal *)arg2;
- (void)multiplayerP2PViewController:(GKMultiplayerP2PViewController *)arg1 startMatchingWithRequest:(GKMatchRequest *)arg2;
- (void)multiplayerP2PViewControllerWasCancelled:(GKMultiplayerP2PViewController *)arg1;
- (void)multiplayerP2PViewController:(GKMultiplayerP2PViewController *)arg1 didFinishWithError:(NSError *)arg2;
@end

