//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BKSApplicationStateMonitor, NSObject<OS_dispatch_queue>, NSString;

@interface ADClientState : NSObject
{
    NSString *_clientBundleID;
    BKSApplicationStateMonitor *_stateMonitor;
    id <ADClientStateDelegate> _delegate;
    NSObject<OS_dispatch_queue> *_instanceQueue;
}

@property(nonatomic) NSObject<OS_dispatch_queue> *instanceQueue; // @synthesize instanceQueue=_instanceQueue;
@property(readonly, nonatomic) id <ADClientStateDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) BKSApplicationStateMonitor *stateMonitor; // @synthesize stateMonitor=_stateMonitor;
@property(readonly, copy, nonatomic) NSString *clientBundleID; // @synthesize clientBundleID=_clientBundleID;
- (void)_notifyDelegateOfStateChange;
@property(readonly, nonatomic) unsigned int clientApplicationState;
- (id)clientStateTags;
- (void)close;
- (void)dealloc;
- (void)globalStateDidChange:(id)arg1;
- (id)initWithDelegate:(id)arg1 bundleID:(id)arg2;

@end

