//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary, NSObject<OS_dispatch_queue>;

@interface ADiAdJSCache : NSObject
{
    _Bool _cacheLoaded;
    NSMutableDictionary *_cache;
    NSMutableDictionary *_downloadHandlers;
    NSObject<OS_dispatch_queue> *_queue;
    NSMutableArray *_pendingDownloadRecords;
}

+ (id)sharedCache;
@property(retain, nonatomic) NSMutableArray *pendingDownloadRecords; // @synthesize pendingDownloadRecords=_pendingDownloadRecords;
@property(nonatomic) _Bool cacheLoaded; // @synthesize cacheLoaded=_cacheLoaded;
@property(nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) NSMutableDictionary *downloadHandlers; // @synthesize downloadHandlers=_downloadHandlers;
@property(retain, nonatomic) NSMutableDictionary *cache; // @synthesize cache=_cache;
- (void)_extractDistributionForVersion:(id)arg1 fromData:(id)arg2;
- (void)_persistCache;
- (void)downloadiAdJSVersion:(id)arg1 fromURL:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_downloadiAdJSVersion:(id)arg1 fromURL:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)URLForiAdJSVersion:(id)arg1;
- (id)init;

@end

