//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSXPCListenerDelegate.h"

@class NSMapTable, NSMutableDictionary, NSString, NSTimer, NSXPCListener;

@interface ADSMessageCoordinator : NSObject <NSXPCListenerDelegate>
{
    NSMapTable *_webviewRemoteTestingRegistry;
    _Bool _iBooksInstalled;
    NSMutableDictionary *_clientRecords;
    NSTimer *_loggingTimer;
    double _startTime;
    NSXPCListener *_xpcListener;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSXPCListener *xpcListener; // @synthesize xpcListener=_xpcListener;
@property(nonatomic) double startTime; // @synthesize startTime=_startTime;
@property(retain, nonatomic) NSTimer *loggingTimer; // @synthesize loggingTimer=_loggingTimer;
@property(readonly, nonatomic) NSMutableDictionary *clientRecords; // @synthesize clientRecords=_clientRecords;
@property(readonly, nonatomic) _Bool iBooksInstalled; // @synthesize iBooksInstalled=_iBooksInstalled;
- (void)unregisterWebViewForRemoteTesting:(id)arg1;
- (void)registerWebViewForRemoteTesting:(id)arg1 withIdentifier:(id)arg2;
- (void)_test_reportCurrentDSID:(id)arg1;
- (void)_test_reportiAdID:(id)arg1;
- (id)_test_closeUnassignedBannerControllers:(id)arg1;
- (id)_test_runJavaScriptInWebView:(id)arg1;
- (id)_test_resetDSIDToiAdIDMap:(id)arg1;
- (id)_test_reportiBooksInstalled:(id)arg1;
- (void)_test_reportStatusBarVisibility:(id)arg1;
- (void)_test_createMemoryNotification:(id)arg1;
- (void)_test_checkActiveAssertions:(id)arg1;
- (void)_test_tickleAssertions:(id)arg1;
- (id)_test_clearLocationPermissionCache:(id)arg1;
- (id)_test_resetServerAccessCoordinator:(id)arg1;
- (id)_test_clearAdCaches:(id)arg1;
- (id)_test_clearResourceCache:(id)arg1;
- (void)_test_clearURLCache:(id)arg1;
- (void)_test_abort:(id)arg1;
- (void)_test_terminate:(id)arg1;
- (void)sessionDidClose:(id)arg1;
- (void)_logClients:(id)arg1;
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (id)sessionForBundleID:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

