//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JSExport.h"

@class JSValue, NSArray, NSString;

@protocol ADSMSComposerJSO_Bindings <JSExport>
@property(readonly, nonatomic) long long kADSMSComposerMaximumAttachmentBytes;
@property(retain, nonatomic) JSValue *listener;
@property(retain, nonatomic) NSArray *recipients;
@property(copy, nonatomic) NSString *body;
- (void)setAttachments:(NSArray *)arg1;
- (_Bool)canAttachMIMEType:(NSString *)arg1;
- (void)presentComposer;
@end

