//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ADJavaScriptObject.h"

#import "ABPeoplePickerNavigationControllerDelegate.h"
#import "ADStoreJSO_Bindings.h"
#import "SKStoreProductViewControllerDelegate.h"
#import "SSItemLookupRequestDelegate.h"
#import "SSPurchaseRequestDelegate.h"

@class NSMutableArray, NSMutableDictionary, NSNumber, NSString, SKStoreProductViewController, SSItemOffer;

@interface ADStoreJSO : ADJavaScriptObject <ADStoreJSO_Bindings, SSItemLookupRequestDelegate, SSPurchaseRequestDelegate, ABPeoplePickerNavigationControllerDelegate, SKStoreProductViewControllerDelegate>
{
    _Bool _currentPurchaseShouldIncludeiBooks;
    _Bool _hasRegisteredItems;
    NSNumber *_currentPurchaseAdamId;
    SSItemOffer *_currentPurchaseOffer;
    NSNumber *_currentPurchaseRingtoneAssigneeIdentifier;
    NSMutableDictionary *_registeredItems;
    NSMutableArray *_storeRequests;
    NSString *_iBooksBuyParameters;
    SKStoreProductViewController *_storeProductViewController;
    CDUnknownBlockType _storeProductViewControllerDidFinishHandler;
}

+ (void)initializeInContext:(id)arg1;
@property(copy, nonatomic) CDUnknownBlockType storeProductViewControllerDidFinishHandler; // @synthesize storeProductViewControllerDidFinishHandler=_storeProductViewControllerDidFinishHandler;
@property(retain, nonatomic) SKStoreProductViewController *storeProductViewController; // @synthesize storeProductViewController=_storeProductViewController;
@property _Bool hasRegisteredItems; // @synthesize hasRegisteredItems=_hasRegisteredItems;
@property(copy, nonatomic) NSString *iBooksBuyParameters; // @synthesize iBooksBuyParameters=_iBooksBuyParameters;
@property(retain, nonatomic) NSMutableArray *storeRequests; // @synthesize storeRequests=_storeRequests;
@property(retain, nonatomic) NSMutableDictionary *registeredItems; // @synthesize registeredItems=_registeredItems;
@property(copy, nonatomic) NSNumber *currentPurchaseRingtoneAssigneeIdentifier; // @synthesize currentPurchaseRingtoneAssigneeIdentifier=_currentPurchaseRingtoneAssigneeIdentifier;
@property _Bool currentPurchaseShouldIncludeiBooks; // @synthesize currentPurchaseShouldIncludeiBooks=_currentPurchaseShouldIncludeiBooks;
@property(retain, nonatomic) SSItemOffer *currentPurchaseOffer; // @synthesize currentPurchaseOffer=_currentPurchaseOffer;
@property(copy, nonatomic) NSNumber *currentPurchaseAdamId; // @synthesize currentPurchaseAdamId=_currentPurchaseAdamId;
- (void)productViewController:(id)arg1 didFinishWithResult:(long long)arg2;
- (void)presentStorePage:(id)arg1;
- (void)loadStorePageForAdamID:(id)arg1 completionHandler:(id)arg2;
- (void)redeemiTunesGiftCode:(id)arg1 listener:(id)arg2;
- (void)peoplePickerNavigationControllerDidCancel:(id)arg1;
- (_Bool)peoplePickerNavigationController:(id)arg1 shouldContinueAfterSelectingPerson:(void *)arg2 property:(int)arg3 identifier:(int)arg4;
- (_Bool)peoplePickerNavigationController:(id)arg1 shouldContinueAfterSelectingPerson:(void *)arg2;
- (void)purchaseRequest:(id)arg1 purchaseDidSucceed:(id)arg2;
- (void)purchaseRequest:(id)arg1 purchaseDidFail:(id)arg2 withError:(id)arg3;
- (void)purchaseItemWithID:(id)arg1 offerIdentifier:(id)arg2 listener:(id)arg3;
- (void)_cancelPurchase;
- (void)_checkForiBooksApp;
- (void)_getRingtoneAssignee;
- (void)_purchaseCurrentItem;
- (void)requestDidFinish:(id)arg1;
- (void)_handleFailedAdamId:(id)arg1;
- (void)request:(id)arg1 didFailWithError:(id)arg2;
- (void)itemLookupRequest:(id)arg1 didFindItems:(id)arg2;
- (void)lookupItemWithID:(id)arg1 listener:(id)arg2;
- (void)registerItemsForPurchase:(id)arg1;
- (void)_lookupRegisteredItems;
- (id)initWithDelegate:(id)arg1 impressionController:(id)arg2;
- (void)adWillDismiss;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

