//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WebArchive.h"

@interface WebArchive (ADWebArchiveExtras)
+ (id)_iAd_sanitizedArchiveFromData:(id)arg1 queryString:(id)arg2 errorMessage:(id *)arg3 subresourceOverride:(CDUnknownBlockType)arg4;
@end

