//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSObject<OS_dispatch_queue>;

@interface MIApplicationArchiveManager : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;
    NSMutableDictionary *_archiveMap;
}

+ (id)defaultManager;
- (void).cxx_destruct;
- (void)clearArchives;
- (id)archiveMap;
- (_Bool)removeArchiveForIdentifier:(id)arg1 withOptions:(id)arg2 forClient:(id)arg3 error:(id *)arg4;
- (_Bool)_onQueue_removeArchiveForIdentifier:(id)arg1 withOptions:(id)arg2 forClient:(id)arg3 error:(id *)arg4;
- (_Bool)createArchiveForIdentifier:(id)arg1 withOptions:(id)arg2 forClient:(id)arg3 error:(id *)arg4;
- (_Bool)_onQueue_createArchiveForIdentifier:(id)arg1 withOptions:(id)arg2 forClient:(id)arg3 error:(id *)arg4;
- (void)_onQueue_syncArchiveMapToDisk;
- (id)_archiveMapURL;
- (id)_archiveFileNameForIdentifier:(id)arg1;
- (id)init;

@end

