//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NDSessionManager, NSString;

@protocol NDSessionManagerDelegate <NSObject>
- (void)managerBecameEmpty:(NDSessionManager *)arg1 bundleID:(NSString *)arg2 withCompletionHandler:(void (^)(void))arg3;
@end

