//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BKEventDestination, NSString;

@interface BKHIDServiceInfo : NSObject
{
    struct __IOHIDService *_hidService;
    NSString *_displayUUID;
    int _eventSource;
    _Bool _swallowEvents;
    _Bool _capsLockOn;
    unsigned long long _keyDownCount;
    unsigned long long _touchCount;
    BKEventDestination *_currentDestination;
}

@property(retain, nonatomic) BKEventDestination *currentDestination; // @synthesize currentDestination=_currentDestination;
@property(nonatomic) unsigned long long touchCount; // @synthesize touchCount=_touchCount;
@property(nonatomic, getter=isCapsLockOn) _Bool capsLockOn; // @synthesize capsLockOn=_capsLockOn;
@property(nonatomic, getter=shouldSwallowEvents) _Bool swallowEvents; // @synthesize swallowEvents=_swallowEvents;
@property(nonatomic) unsigned long long keyDownCount; // @synthesize keyDownCount=_keyDownCount;
- (void)watchForRemoval:(CDUnknownBlockType)arg1;
- (void)setExternalKeyboardEventSource;
- (int)eventSource;
- (id)displayUUID;
- (struct __IOHIDService *)copyHIDService;
- (id)description;
- (_Bool)isEqual:(id)arg1;
- (void)dealloc;
- (id)initWithHIDService:(struct __IOHIDService *)arg1;

@end

