//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_source>;

@interface BKUserEventTimer : NSObject
{
    double _currentTimeout;
    double _lastUserEvent;
    double _lastResetTimerRequest;
    NSObject<OS_dispatch_source> *_timer;
    _Bool _isIdle;
    int _currentMode;
    NSObject<OS_dispatch_queue> *_queue;
    _Bool _shouldNotify;
}

+ (id)sharedInstance;
- (void)_clearTimer;
- (void)_scheduleTimerWithTimeInterval:(double)arg1;
- (void)notifyOnNextUserEvent;
- (void)userEventOccurredOnDisplay:(id)arg1;
- (void)_userEventOccurredInPresenceMode;
- (void)_didUnIdle;
- (void)_userEventOccurredInIdleMode;
- (void)resetTimer:(double)arg1 mode:(int)arg2;
- (double)lastUserEventTime;
- (void)dealloc;
- (id)init;

@end

