//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <GLToolsServices/DYGLResourceObject.h>

#import "DYBuffer.h"

@class NSData, NSMutableDictionary, NSString;

@interface DYGLBufferObject : DYGLResourceObject <DYBuffer>
{
    BOOL _isClientData;
    unsigned int _usage;
    NSData *_data;
    long long _offset;
    unsigned long long _size;
}

@property(readonly, nonatomic) BOOL isClientData; // @synthesize isClientData=_isClientData;
@property(readonly, nonatomic) unsigned int usage; // @synthesize usage=_usage;
@property(readonly, nonatomic) unsigned long long size; // @synthesize size=_size;
@property(readonly, nonatomic) long long offset; // @synthesize offset=_offset;
@property(readonly, nonatomic) NSData *data; // @synthesize data=_data;
- (void).cxx_destruct;
- (id)initWithProperties:(id)arg1;
- (id)initWithResourceObject:(id)arg1 functionStream:(id)arg2 dataResolver:(CDUnknownBlockType)arg3;

// Remaining properties
@property(readonly, nonatomic) unsigned long long containerID;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) int internalID;
@property(readonly, nonatomic) BOOL isStatic;
@property(readonly, copy, nonatomic) NSString *label;
@property(readonly, nonatomic) unsigned long long objectID;
@property(readonly, nonatomic) NSMutableDictionary *properties;
@property(readonly, nonatomic) unsigned int resourceType;
@property(readonly) Class superclass;
@property(readonly, nonatomic) unsigned int target;

@end

