_IDEAppleScriptCoreVersionNumber
_IDEAppleScriptCoreVersionString
_OBJC_CLASS_$_IDEAppleScriptIndexDataSource
_OBJC_CLASS_$_IDEAppleScriptIndexQueryProvider
_OBJC_METACLASS_$_IDEAppleScriptIndexDataSource
_OBJC_METACLASS_$_IDEAppleScriptIndexQueryProvider
