//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "HKSwitchTableViewCellDelegate.h"

@class HKDataCategory, HKDataUnitGroup, HKHealthStore, NSMutableArray, NSMutableDictionary, WDDataProviderOrderController, WDTitledIconView;

@interface WDDataUnitGroupDataSourcesTableViewController : UITableViewController <HKSwitchTableViewCellDelegate>
{
    HKDataCategory *_dataCategory;
    HKDataUnitGroup *_dataUnitGroup;
    HKHealthStore *_healthStore;
    WDDataProviderOrderController *_dataProviderOrderController;
    NSMutableArray *_dataProviderSources;
    NSMutableArray *_dataProviderSourcesOrdered;
    NSMutableArray *_sharingSources;
    NSMutableDictionary *_authorizationRecordsBySource;
    WDTitledIconView *_headerView;
}

- (void).cxx_destruct;
- (void)switchCellValueChanged:(id)arg1 value:(_Bool)arg2;
- (id)tableView:(id)arg1 targetIndexPathForMoveFromRowAtIndexPath:(id)arg2 toProposedIndexPath:(id)arg3;
- (_Bool)tableView:(id)arg1 shouldIndentWhileEditingRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 moveRowAtIndexPath:(id)arg2 toIndexPath:(id)arg3;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (id)_noneTableViewCell;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
- (_Bool)_sourceIsEnabled:(id)arg1;
- (void)_updateSharingSourcesFromArray:(id)arg1;
- (void)_updateDataProviderSourcesFromArray:(id)arg1;
- (void)_sortDataProviderSources;
- (void)_reloadAuthorizationRecords;
- (void)_gatherDataAndRefreshUI;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithStyle:(long long)arg1;
- (id)initWithDataUnitGroup:(id)arg1 dataCategory:(id)arg2 dataProviderOrderController:(id)arg3 healthStore:(id)arg4;

@end

