//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WDDataUnitAverageFormatter.h"

@class NSNumberFormatter;

@interface WDQuantityDataUnitAverageFormatter : WDDataUnitAverageFormatter
{
    NSNumberFormatter *_numberFormatter;
}

- (void).cxx_destruct;
- (id)_componentsForNumber:(id)arg1;
- (id)init;
- (id)initWithNumberFormatter:(id)arg1;

@end

