//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WDDataProvider.h"

@class HKQuery, NSDate;

@interface WDSleepDataProvider : WDDataProvider
{
    HKQuery *_historicalDataQuery;
    HKQuery *_currentValueQuery;
    NSDate *_lastObservedStartDate;
}

- (void).cxx_destruct;
- (id)_calculateTotalSleepFromSamples:(id)arg1 startDate:(id)arg2 endDate:(id)arg3 interval:(id)arg4 useEndDateAsReference:(_Bool)arg5;
- (id)_coalesceSleepSamples:(id)arg1 strictStart:(id)arg2 strictEnd:(id)arg3;
- (id)_dateBetweenStart:(id)arg1 andEnd:(id)arg2;
- (id)_createChartPointsFromStartDate:(id)arg1 toEndDate:(id)arg2;
- (id)_calculateAverageFromTotalSleep:(id)arg1;
- (void)_refreshHistoricalDataWithSleepSamples_Extended:(id)arg1;
- (void)_refreshHistoricalDataWithSleepSamples_Day:(id)arg1;
- (void)_refreshHistoricalDataWithSleepSamples:(id)arg1;
- (void)_historicalDataMatchingPredicate:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (id)_historicalDataQuery;
- (void)_updateDailyAverage;
- (void)_mostRecentSleepStartDate:(CDUnknownBlockType)arg1;
- (void)_totalSleepFromDate:(id)arg1 toDate:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_updateCurrentValue;
- (id)_currentValueQuery;
- (void)_stopCurrentValueQuery;
- (void)_restartCurrentValueQuery;
- (void)_stopHistoricalDataQuery;
- (void)_restartHistoricalDataQuery;
- (void)stopQueries;
- (void)restartQueries;

@end

