//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark Named Structures

struct ArticleFinderJSController;

struct CGPoint {
    double _field1;
    double _field2;
};

struct CGRect {
    struct CGPoint _field1;
    struct CGSize _field2;
};

struct CGSize {
    double _field1;
    double _field2;
};

struct OpaqueJSContext;

struct OpaqueJSValue;

struct OwnPtr<ArticleFinderJSController> {
    struct ArticleFinderJSController *_field1;
};

struct ReaderController {
    id _field1;
    struct SString _field2;
    _Bool _field3;
    _Bool _field4;
    struct OwnPtr<ArticleFinderJSController> _field5;
    id _field6;
    struct SString _field7;
    _Bool _field8;
    id _field9;
};

struct ReaderJSController {
    CDUnknownFunctionPointerType *_field1;
    struct Vector<OpaqueJSValue *, 0, WTF::CrashOnOverflow> _field2;
    struct OpaqueJSValue *_field3;
    struct OpaqueJSContext *_field4;
    id _field5;
    struct ReaderController *_field6;
    struct OwnPtr<ArticleFinderJSController> _field7;
    int _field8;
    struct RetainPtr<NSDictionary> _field9;
};

struct RetainPtr<NSDictionary> {
    void *_field1;
};

struct RetainPtr<const __CFString *> {
    void *_field1;
};

struct SString {
    struct RetainPtr<const __CFString *> _field1;
};

struct Vector<OpaqueJSValue *, 0, WTF::CrashOnOverflow> {
    struct OpaqueJSValue **_field1;
    unsigned int _field2;
    unsigned int _field3;
};

