//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary;

@interface MockiPhoneAccessibilityElement : NSObject
{
    NSDictionary *_data;
}

+ (void)initialize;
@property(copy) NSDictionary *data; // @synthesize data=_data;
- (void)dealloc;
- (BOOL)accessibilityShouldUseUniqueId;
- (void)accessibilityPerformAction:(id)arg1;
- (void)performDecrementAction;
- (void)performIncrementAction;
- (void)performPressAction;
- (id)accessibilityAttributeValue:(id)arg1;
- (id)roleDescription;
- (BOOL)accessibilityIsAttributeSettable:(id)arg1;
- (id)accessibilityActionDescription:(id)arg1;
- (BOOL)accessibilityIsIgnored;
- (int)pid;
- (id)accessibilityActionNames;
- (id)accessibilityAttributeNames;
- (void)updateDictionary:(id)arg1;
- (id)initWithDictionary:(id)arg1;

@end

