//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSImage, NSString, SKNode;

@interface SKObjectLibraryAsset : NSObject <NSCoding>
{
    SKNode *_node;
    NSImage *_image;
    NSString *_title;
    NSString *_subtitle;
    NSString *_summary;
}

@property(copy) NSString *summary; // @synthesize summary=_summary;
@property(copy) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(copy) NSString *title; // @synthesize title=_title;
@property(retain) NSImage *image; // @synthesize image=_image;
@property(retain, nonatomic) SKNode *node; // @synthesize node=_node;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

