//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SKUIServiceAccountPageViewController.h"
#import "SUClientInterfaceDelegatePrivate.h"

@class NSString, SUClientInterface, SUNavigationController, ServiceSUAccountViewController;

@interface ServiceAccountPageViewController : UIViewController <SKUIServiceAccountPageViewController, SUClientInterfaceDelegatePrivate>
{
    SUClientInterface *_clientInterface;
    SUNavigationController *_navigationController;
    ServiceSUAccountViewController *_underlyingViewController;
}

+ (id)_remoteViewControllerInterface;
+ (id)_exportedInterface;
- (void).cxx_destruct;
- (id)_clientViewControllerProxy;
- (id)newAlertViewForClientInterface:(id)arg1;
- (void)loadWithURL:(id)arg1;
- (void)_willAppearInRemoteViewController;
- (void)loadView;
- (void)dismissHostViewController;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

