//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SUAccountViewController.h"

@class ServiceAccountPageViewController;

@interface ServiceSUAccountViewController : SUAccountViewController
{
    ServiceAccountPageViewController *_hostedViewController;
}

@property(nonatomic) __weak ServiceAccountPageViewController *hostedViewController; // @synthesize hostedViewController=_hostedViewController;
- (void).cxx_destruct;
- (void)dismissViewControllerAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)dismissAnimated:(_Bool)arg1;

@end

