//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GKCollectionViewCell.h"

@class GKAchievementIconView, GKContiguousContainerView, GKLabel;

@interface GKAchievementCell : GKCollectionViewCell
{
    _Bool _hasEligibleFriends;
    GKAchievementIconView *_badgeView;
    GKLabel *_titleLabel;
    GKLabel *_descriptionLabel;
    GKLabel *_valueLabel;
    GKLabel *_pointsLabel;
    GKContiguousContainerView *_textContainerView;
    GKContiguousContainerView *_pointsContainerView;
}

+ (double)defaultRowHeight;
@property(retain, nonatomic) GKContiguousContainerView *pointsContainerView; // @synthesize pointsContainerView=_pointsContainerView;
@property(retain, nonatomic) GKContiguousContainerView *textContainerView; // @synthesize textContainerView=_textContainerView;
@property(retain, nonatomic) GKLabel *pointsLabel; // @synthesize pointsLabel=_pointsLabel;
@property(retain, nonatomic) GKLabel *valueLabel; // @synthesize valueLabel=_valueLabel;
@property(retain, nonatomic) GKLabel *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
@property(retain, nonatomic) GKLabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) _Bool hasEligibleFriends; // @synthesize hasEligibleFriends=_hasEligibleFriends;
@property(retain, nonatomic) GKAchievementIconView *badgeView; // @synthesize badgeView=_badgeView;
- (void)setupForAchievement:(id)arg1 localAchievement:(id)arg2;
- (void)establishConstraints;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

