//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GKPlayerProfileBubbleViewController.h"

#import "GKFriendActions.h"

@class GKPlayer;

@interface GKFriendProfileViewController : GKPlayerProfileBubbleViewController <GKFriendActions>
{
    _Bool _shouldPopWhenUnfriended;
    _Bool _didFloatInBubbles;
    long long _pressedBubbleType;
    long long _alreadyChangedToThisSizeClass;
}

@property(nonatomic) long long alreadyChangedToThisSizeClass; // @synthesize alreadyChangedToThisSizeClass=_alreadyChangedToThisSizeClass;
@property(nonatomic) _Bool didFloatInBubbles; // @synthesize didFloatInBubbles=_didFloatInBubbles;
@property(nonatomic) long long pressedBubbleType; // @synthesize pressedBubbleType=_pressedBubbleType;
@property(nonatomic) _Bool shouldPopWhenUnfriended; // @synthesize shouldPopWhenUnfriended=_shouldPopWhenUnfriended;
- (long long)gkFocusBubbleType;
- (void)friendRequestComposeViewControllerDidFinish:(id)arg1;
- (void)didTouchPointsBubble;
- (void)didTouchFriendsBubble;
- (void)didTouchGamesBubble;
- (void)updateBubbleLayoutForOrientation:(long long)arg1;
- (void)viewDidLayoutSubviews;
- (id)bubbleAnimatorForTransitionToViewController:(id)arg1;
- (id)bubbleAnimatorForTransitionFromViewController:(id)arg1;
- (double)bubbleFlowAnimateInDuration;
- (double)bubbleFlowAnimateOutDuration;
- (_Bool)_doScatterTransitionForThisDisappearance;
- (_Bool)_doFloatTransitionForThisAppearance;
- (id)viewsToAnimateOutWhileDisappearingWithBubbleFlow;
- (id)viewsToAnimateInWhileAppearingWithBubbleFlow;
- (void)floatInBubbles;
- (void)configureControlForBubble:(id)arg1;
- (void)viewWillAppearAnimated:(_Bool)arg1 bubbleFlow:(_Bool)arg2;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)loadView;
- (void)didTouchActionsButton;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, retain, nonatomic) GKPlayer *player;

@end

