//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GKBaseGameCell.h"

@class GKGameRecord, GKLabel;

@interface GKGamePointsCompareCell : GKBaseGameCell
{
    GKGameRecord *_localPlayerGameRecord;
    GKLabel *_friendPointsLabel;
    GKLabel *_localPointsLabel;
    GKLabel *_totalPointsLabel;
    GKLabel *_achievementsCountLabel;
}

+ (id)itemHeightList;
@property(retain, nonatomic) GKLabel *achievementsCountLabel; // @synthesize achievementsCountLabel=_achievementsCountLabel;
@property(retain, nonatomic) GKLabel *totalPointsLabel; // @synthesize totalPointsLabel=_totalPointsLabel;
@property(retain, nonatomic) GKLabel *localPointsLabel; // @synthesize localPointsLabel=_localPointsLabel;
@property(retain, nonatomic) GKLabel *friendPointsLabel; // @synthesize friendPointsLabel=_friendPointsLabel;
@property(retain, nonatomic) GKGameRecord *localPlayerGameRecord; // @synthesize localPlayerGameRecord=_localPlayerGameRecord;
- (void)didUpdateModel;
- (void)prepareForReuse;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

