//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ITunesPackage/AbstractElement.h>

@class AssetElement, NSArray, NSString;

@interface AbstractSoftwareInAppPurchaseElementBase : AbstractElement
{
    NSArray *_locales;
    NSString *_reviewNotes;
    AssetElement *_reviewScreenshot;
}

+ (id)allKnownKeyPaths;
- (id)descriptionWithLocale:(id)arg1 indent:(unsigned long long)arg2;
@property(retain, nonatomic) AssetElement *reviewScreenshot;
@property(retain, nonatomic) NSString *reviewNotes;
@property(retain, nonatomic) NSArray *locales;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)init;

@end

