//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ITunesPackage/AbstractElement.h>

@class NSArray, NSNumber, NSString;

@interface ArtistElementBase : AbstractElement
{
    NSArray *_names;
    NSString *_name;
    NSString *_phoneticName;
    NSNumber *_appleId;
    NSArray *_roles;
    NSArray *_locales;
    NSNumber *_primary;
}

+ (id)allKnownKeyPaths;
- (id)descriptionWithLocale:(id)arg1 indent:(unsigned long long)arg2;
@property(retain, nonatomic) NSNumber *primary;
@property(retain, nonatomic) NSArray *locales;
@property(retain, nonatomic) NSArray *roles;
@property(retain, nonatomic) NSNumber *appleId;
@property(retain, nonatomic) NSString *phoneticName;
@property(retain, nonatomic) NSString *name;
@property(retain, nonatomic) NSArray *names;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)init;

@end

