//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ITunesPackageLoaderProcessingDelegate.h"

@interface BookNamespaceFixer : NSObject <ITunesPackageLoaderProcessingDelegate>
{
}

- (id)preprocessObjectPriorToMarshalling:(id)arg1;
- (id)postprocessDocumentAfterMarshalling:(id)arg1 object:(id)arg2;
- (id)postprocessObjectAfterUnmarshalling:(id)arg1 document:(id)arg2;
- (id)preprocessDocumentPriorToUnmarshalling:(id)arg1;
- (id)problematicNamespaces;

@end

