//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ITunesPackage/BookProductElementBase.h>

@interface BookProductElement : BookProductElementBase
{
}

+ (void)initialize;
- (void)setCurrency:(id)arg1;
- (id)currency;
- (void)setSuggestedRetailPrice:(id)arg1;
- (id)suggestedRetailPrice;
- (id)physicalListPriceInsertingIfNeeded;
- (void)notifyObserversOfPricingChange;
- (id)init;

@end

