//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ITunesPackage/AbstractElement.h>

@class NSString;

@interface MusicLocaleElementBase : AbstractElement
{
    NSString *_name;
    NSString *_title;
    NSString *_phoneticTitle;
    NSString *_titleVersion;
    NSString *_artistName;
    NSString *_phoneticArtistName;
}

+ (id)allKnownKeyPaths;
- (id)descriptionWithLocale:(id)arg1 indent:(unsigned long long)arg2;
@property(retain, nonatomic) NSString *phoneticArtistName;
@property(retain, nonatomic) NSString *artistName;
@property(retain, nonatomic) NSString *titleVersion;
@property(retain, nonatomic) NSString *phoneticTitle;
@property(retain, nonatomic) NSString *title;
@property(retain, nonatomic) NSString *name;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)init;

@end

