//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ITunesPackage/PackageElementBase.h>

@interface PackageElement : PackageElementBase
{
}

+ (int)packageDeliveryTypeWithString:(id)arg1;
+ (id)stringWithPackageDeliveryType:(int)arg1;
+ (int)packageTypeWithString:(id)arg1;
+ (id)stringWithPackageType:(int)arg1;
+ (id)localizedString:(id)arg1 forTranslation:(id)arg2;
+ (id)defaultLocalizedString:(id)arg1;
+ (void)initialize;
- (void)removeInitialElements;
- (BOOL)addInfoFromElement:(id)arg1 error:(id *)arg2;
- (id)bestGuessVersionIfNotSpecified;
- (id)bestVendorId;
- (BOOL)isRingtone;
- (BOOL)isAssetOnly;
- (BOOL)isPublication;
- (BOOL)isSoftware;
- (BOOL)isMusic;
- (void)setPackageDeliveryType:(int)arg1;
- (int)packageDeliveryType;
- (int)packageType;
- (int)packageTypeThroughIntrospection;
- (int)packageTypeFromVideo:(id)arg1;
- (int)packageTypeFromMediaType:(id)arg1;
- (void)setVersion:(id)arg1;
- (id)init;

@end

