//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ITunesPackage/VideoCueTimeElementBase.h>

@interface VideoCueTimeElement : VideoCueTimeElementBase
{
}

+ (void)initialize;
- (id)init;

@end

