//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ITunesPackage/VideoElementBase.h>

#import "Track.h"
#import "TrackNumberAndVolume.h"

@interface VideoElement : VideoElementBase <Track, TrackNumberAndVolume>
{
}

- (BOOL)isBooklet;
- (BOOL)isITunesLP;
- (BOOL)isBonusMaterial;
- (double)duration;
- (void)setDuration:(double)arg1;
- (id)durationStringWithSeconds;
- (id)defaultSalesStartDate;
- (id)productWithTerritory:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (void)setGenres:(id)arg1;
- (void)updateGenre:(id)arg1;
- (void)removeGenreObservations;
- (void)observeGenres;
- (void)setFileElement:(id)arg1;
- (id)file;
- (id)defaultTitle;

@end

