//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ITunesPackage/AbstractElement.h>

@class NSString;

@interface VideoRegionElementBase : AbstractElement
{
    NSString *_territory;
    NSString *_copyrightPline;
    NSString *_copyrightCline;
    NSString *_theatricalReleaseDate;
}

+ (id)allKnownKeyPaths;
- (id)descriptionWithLocale:(id)arg1 indent:(unsigned long long)arg2;
@property(retain, nonatomic) NSString *theatricalReleaseDate;
@property(retain, nonatomic) NSString *copyrightCline;
@property(retain, nonatomic) NSString *copyrightPline;
@property(retain, nonatomic) NSString *territory;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)init;

@end

