//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <IDEModelFoundation/XDUMLClassifierImp.h>

#import "XDUMLDataType.h"

@class NSString;

@interface XDUMLDataTypeImp : XDUMLClassifierImp <XDUMLDataType>
{
}

@property(readonly, copy) NSString *description;
- (id)ownedOperations;
- (id)ownedAttributes;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

