//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XRPowerTimeline.h"

@interface XRMutablePowerTimeline : XRPowerTimeline
{
}

- (void)synchronizeFile;
- (void)appendStateAtIndex:(unsigned long long)arg1 atTime:(unsigned long long)arg2;
- (void)setIndex:(unsigned long long)arg1 forTimeRange:(struct XRTimeRange)arg2;

@end

