//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IDEApplication.h"

@interface IDEApplication (IDEQuickLookDocumentScripting)
- (void)setSdefSupport_activeBlueprintDocument:(id)arg1;
- (id)sdefSupport_activeBlueprintDocument;
- (id)sdefSupport_blueprintDocuments;
@end

