//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class NSString;

@interface PFTCaptureWindowOperation : NSOperation
{
    unsigned int _win;
    NSString *_filepath;
}

- (void)main;
- (void)dealloc;
- (id)initWithWindow:(unsigned int)arg1 filepath:(id)arg2;

@end

