//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "XRDisassemblerProtocol.h"

@class NSString;

@interface XRLLVMDisassemblerPlugin : NSObject <XRDisassemblerProtocol>
{
}

- (BOOL)detectAsmLoopsIn:(struct NSObject *)arg1 error:(id *)arg2;
- (BOOL)fixupCallstack:(unsigned long long *)arg1 frameCount:(unsigned int *)arg2 extraRegisters:(unsigned int)arg3 withSymbolicator:(struct _CSTypeRef)arg4 hasKernelFrames:(BOOL)arg5;
- (struct NSObject *)instructionsForBinary:(id)arg1 andAddress:(unsigned long long)arg2 withCPUType:(int)arg3 andSubtype:(int)arg4 andMode:(unsigned long long)arg5 error:(id *)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

