//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSWindow;

@interface LocaleChooserController : NSObject
{
    NSWindow *window;
    NSWindow *_sheetWindow;
    SEL _didChooseCallback;
    SEL _didCancelCallback;
    id _nonretainedDelegate;
    NSArray *_availableLocales;
}

- (void)cancel:(id)arg1;
- (void)choose:(id)arg1;
- (id)selectedLocaleCodes;
- (BOOL)windowShouldClose:(id)arg1;
- (void)_cleanup;
- (void)detailsSheetDidEnd:(id)arg1 returnCode:(int)arg2 contextInfo:(void *)arg3;
- (void)showLocalesForRemovingFromPackage:(id)arg1 withUserAddedLocales:(id)arg2;
- (void)showLocalesForAddingToPackage:(id)arg1 withUserAddedLocales:(id)arg2;
- (id)codesOfAlreadyUsedLocalesinPackage:(id)arg1 includePackageLanaguage:(BOOL)arg2 userAddedLocales:(id)arg3;
- (void)showLocales:(id)arg1;
- (id)createDisplayDictionariesForLocaleCodes:(id)arg1;
- (id)availableLocales;
- (void)setAvailableLocales:(id)arg1;
- (void)loadInterface;
- (void)dealloc;
- (id)initWithSheetWindow:(id)arg1 delegate:(id)arg2 chooseSelector:(SEL)arg3 cancelSelector:(SEL)arg4;

@end

