
/Applications/Xcode.app//Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/libTelephonyBasebandBulkUSBDynamic.dylib (for architecture armv7):
_TelephonyBasebandBulkUSBTransportCreate
_TelephonyBasebandBulkUSBTransportGetCookies
_TelephonyBasebandBulkUSBTransportGetDeviceName
_TelephonyBasebandBulkUSBTransportGetInterface
_TelephonyBasebandBulkUSBTransportGetMaxWritePacketSize
_TelephonyBasebandBulkUSBTransportGetReadPipeNumber
_TelephonyBasebandBulkUSBTransportGetVendorIDAndProductID
_TelephonyBasebandBulkUSBTransportGetWritePipeNumber
_TelephonyBasebandBulkUSBTransportInitParameters
_kTransportConfigNoZLP

/Applications/Xcode.app//Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/libTelephonyBasebandBulkUSBDynamic.dylib (for architecture armv7s):
_TelephonyBasebandBulkUSBTransportCreate
_TelephonyBasebandBulkUSBTransportGetCookies
_TelephonyBasebandBulkUSBTransportGetDeviceName
_TelephonyBasebandBulkUSBTransportGetInterface
_TelephonyBasebandBulkUSBTransportGetMaxWritePacketSize
_TelephonyBasebandBulkUSBTransportGetReadPipeNumber
_TelephonyBasebandBulkUSBTransportGetVendorIDAndProductID
_TelephonyBasebandBulkUSBTransportGetWritePipeNumber
_TelephonyBasebandBulkUSBTransportInitParameters
_kTransportConfigNoZLP

/Applications/Xcode.app//Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/libTelephonyBasebandBulkUSBDynamic.dylib (for architecture arm64):
_TelephonyBasebandBulkUSBTransportCreate
_TelephonyBasebandBulkUSBTransportGetCookies
_TelephonyBasebandBulkUSBTransportGetDeviceName
_TelephonyBasebandBulkUSBTransportGetInterface
_TelephonyBasebandBulkUSBTransportGetMaxWritePacketSize
_TelephonyBasebandBulkUSBTransportGetReadPipeNumber
_TelephonyBasebandBulkUSBTransportGetVendorIDAndProductID
_TelephonyBasebandBulkUSBTransportGetWritePipeNumber
_TelephonyBasebandBulkUSBTransportInitParameters
_kTransportConfigNoZLP
