//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTableCellView.h"

@class DVTGauge;

@interface iCloudTableCellStatusView : NSTableCellView
{
    DVTGauge *_gauge;
}

@property(retain, nonatomic) DVTGauge *gauge; // @synthesize gauge=_gauge;
- (void).cxx_destruct;
- (void)layout;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)_commonInit;

@end

