//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TrustCertificateViewControllerDelegate.h"
#import "UIApplicationDelegate.h"

@class CPDistributedMessagingCenter, CPDistributedMessagingDelayedReplyContext, NSMutableArray, NSString, NSTimer, UINavigationController, UIView, UIViewController, UIWindow;

@interface TrustMeAppDelegate : NSObject <TrustCertificateViewControllerDelegate, UIApplicationDelegate>
{
    UIView *_remoteView;
    UIViewController *_rootController;
    _Bool _rootControllerIsDismissing;
    UINavigationController *_sheetController;
    CPDistributedMessagingCenter *_center;
    CPDistributedMessagingDelayedReplyContext *_replyContext;
    NSMutableArray *_queuedMessages;
    NSMutableArray *_queuedReplyContexts;
    NSTimer *_killTimer;
}

- (void).cxx_destruct;
- (void)applicationDidFinishLaunching:(id)arg1;
- (void)applicationWillTerminate:(id)arg1;
- (void)_startCenter;
- (void)_trustInfoMessageReceived:(id)arg1 userInfo:(id)arg2;
- (void)_queueMessage:(id)arg1 withReplyContext:(id)arg2;
- (void)_presentNextQueuedMessage;
- (void)trustCertificateViewController:(id)arg1 finishedWithReturnCode:(int)arg2;
- (void)_remoteSheetDidEnd:(id)arg1 returnCode:(long long)arg2 context:(void *)arg3;
- (void)_presentSheetWithInfo:(id)arg1 replyContext:(id)arg2;
- (void)_dismissSheet;
- (void)_sheetControllerDismissedView;
- (void)_endRemoteSheet;
- (_Bool)_usingFormSheet;
- (void)_sendResponse:(int)arg1;
- (void)_killTimerFired;
- (void)_clearTimer;
- (void)_scheduleTimer;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(retain, nonatomic) UIWindow *window;

@end

