
/Applications/Xcode.app//Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/liblangid.dylib (for architecture armv7):
__env
__env_mutex
__langid_create_with_datapath_internal
__langid_dispose_internal
__langid_env_create
__langid_env_dispose
_langid_consume_string
_langid_create
_langid_create_with_datapath
_langid_dispose
_langid_global_dispose
_langid_highest_score
_langid_identify
_langid_identify_bufsize
_langid_identify_withbuf
_langid_languagecode
_langid_numlanguages
_langid_reset
_textcat_Classify
_textcat_Init

/Applications/Xcode.app//Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/liblangid.dylib (for architecture armv7s):
__env
__env_mutex
__langid_create_with_datapath_internal
__langid_dispose_internal
__langid_env_create
__langid_env_dispose
_langid_consume_string
_langid_create
_langid_create_with_datapath
_langid_dispose
_langid_global_dispose
_langid_highest_score
_langid_identify
_langid_identify_bufsize
_langid_identify_withbuf
_langid_languagecode
_langid_numlanguages
_langid_reset
_textcat_Classify
_textcat_Init

/Applications/Xcode.app//Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/liblangid.dylib (for architecture arm64):
__env
__env_mutex
__langid_create_with_datapath_internal
__langid_dispose_internal
__langid_env_create
__langid_env_dispose
_langid_consume_string
_langid_create
_langid_create_with_datapath
_langid_dispose
_langid_global_dispose
_langid_highest_score
_langid_identify
_langid_identify_bufsize
_langid_identify_withbuf
_langid_languagecode
_langid_numlanguages
_langid_reset
_textcat_Classify
_textcat_Init
