//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindow.h"

@interface AWTWindow_Normal : NSWindow
{
}

- (id)initWithDelegate:(id)arg1 frameRect:(struct CGRect)arg2 styleMask:(unsigned long long)arg3 contentView:(id)arg4;
- (BOOL)canBecomeKeyWindow;
- (BOOL)canBecomeMainWindow;
- (BOOL)worksWhenModal;
- (void)sendEvent:(id)arg1;

@end

