//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GPUSharedTabUIState, NSMapTable;

__attribute__((visibility("hidden")))
@interface GPUReportBuilder : NSObject
{
    NSMapTable *_reportSectionMapTable;
    GPUSharedTabUIState *_sharedTabState;
}

- (void).cxx_destruct;
- (id)reportSectionOfType:(int)arg1 reportComponentsArray:(id)arg2 containsUpdatedResults:(BOOL)arg3;
- (void)removeSectionOfType:(int)arg1 removeFromSuperView:(BOOL)arg2;
- (void)updateReportSectionOfType:(int)arg1 withTreeNode:(id)arg2 parentNode:(id)arg3 asFirstChild:(BOOL)arg4;
- (void)updateReportSectionOfType:(int)arg1 withCompletionStatus:(BOOL)arg2;
- (void)dealloc;
- (id)initWithSharedTabState:(id)arg1;

@end

