//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NETPACWrapperDelegate.h"

@class NSArray, NSMutableSet, NSObject<OS_xpc_object>, NSString, NSURL;

@interface NETProxyLookup : NSObject <NETPACWrapperDelegate>
{
    struct __CFRunLoopSource *_pacSrc;
    _Bool _complete;
    _Bool _directAllowed;
    _Bool _urlValid;
    _Bool _urlIsSynthesized;
    int _ifindex;
    int _hostIsSimple;
    id <NETProxyLookupDelegate> _delegate;
    NSObject<OS_xpc_object> *_proxies;
    NSObject<OS_xpc_object> *_euuid;
    NSObject<OS_xpc_object> *_matchingProxies;
    NSObject<OS_xpc_object> *_parameters;
    unsigned long long _resolving;
    NSURL *_url;
    NSMutableSet *_pacWrappers;
    NSString *_host;
    NSArray *_hostNodes;
}

@property _Bool urlIsSynthesized; // @synthesize urlIsSynthesized=_urlIsSynthesized;
@property _Bool urlValid; // @synthesize urlValid=_urlValid;
@property int hostIsSimple; // @synthesize hostIsSimple=_hostIsSimple;
@property(retain, nonatomic) NSArray *hostNodes; // @synthesize hostNodes=_hostNodes;
@property(retain, nonatomic) NSString *host; // @synthesize host=_host;
@property(retain) NSMutableSet *pacWrappers; // @synthesize pacWrappers=_pacWrappers;
@property(retain) NSURL *url; // @synthesize url=_url;
@property unsigned long long resolving; // @synthesize resolving=_resolving;
@property(retain) NSObject<OS_xpc_object> *parameters; // @synthesize parameters=_parameters;
@property(retain) NSObject<OS_xpc_object> *matchingProxies; // @synthesize matchingProxies=_matchingProxies;
@property(retain) NSObject<OS_xpc_object> *euuid; // @synthesize euuid=_euuid;
@property int ifindex; // @synthesize ifindex=_ifindex;
@property(retain) NSObject<OS_xpc_object> *proxies; // @synthesize proxies=_proxies;
@property _Bool directAllowed; // @synthesize directAllowed=_directAllowed;
@property _Bool complete; // @synthesize complete=_complete;
@property __weak id <NETProxyLookupDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)initWithParameters:(id)arg1;
- (id)init;
- (_Bool)pollForChanges;
- (void)cancel;
- (void)startResolve;
- (void)cancelResolve;
- (void)resolveNextProxy;
- (_Bool)resolvePACURL:(id)arg1;
- (_Bool)resolvePACScript:(id)arg1;
- (void)pacLookupComplete:(id)arg1 proxies:(id)arg2 error:(id)arg3;
- (id)copyURL;
- (id)findMatchingProxies;
- (id)convertSchemeProxy:(id)arg1 type:(long long)arg2 enabledkey:(struct __CFString *)arg3 hostKey:(struct __CFString *)arg4 portKey:(struct __CFString *)arg5 defaultPort:(unsigned short)arg6;
- (id)createProxyDictionary:(long long)arg1 host:(id)arg2 port:(unsigned short)arg3;
- (_Bool)matchesException:(id)arg1 forHost:(const char *)arg2 address:(const CDUnion_4a4a8072 *)arg3;
- (_Bool)isHostSimple;
- (_Bool)isEnabled:(id)arg1 defaultValue:(_Bool)arg2;
- (void)notifyDelegate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

