//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AWDLBEndpointsFetchReport, NSArray, NSDictionary, NSObject<OS_dispatch_source>, NSURLSession, NSURLSessionDataTask;

@interface NETWaldo : NSObject
{
    _Bool _waldoTimerSet;
    _Bool _statsReported;
    NSDictionary *_waldoReply;
    NSObject<OS_dispatch_source> *_waldoTimerSource;
    NSURLSession *_waldoSession;
    NSURLSessionDataTask *_waldoFetchTask;
    unsigned long long _errInWaldoTimer;
    unsigned long long _defaultWaldoTTLBasedTimer;
    AWDLBEndpointsFetchReport *_waldoReport;
}

+ (void)dumpState;
+ (id)url;
+ (void)waldoFellbackToCellular;
+ (_Bool)isWaldoHostname:(const char *)arg1;
+ (void)removeClient:(id)arg1;
+ (void)addClient:(id)arg1;
+ (void)notifyClients:(id)arg1;
+ (id)copyReply;
@property(nonatomic) _Bool statsReported; // @synthesize statsReported=_statsReported;
@property(retain, nonatomic) AWDLBEndpointsFetchReport *waldoReport; // @synthesize waldoReport=_waldoReport;
@property unsigned long long defaultWaldoTTLBasedTimer; // @synthesize defaultWaldoTTLBasedTimer=_defaultWaldoTTLBasedTimer;
@property unsigned long long errInWaldoTimer; // @synthesize errInWaldoTimer=_errInWaldoTimer;
@property(retain, nonatomic) NSURLSessionDataTask *waldoFetchTask; // @synthesize waldoFetchTask=_waldoFetchTask;
@property(retain, nonatomic) NSURLSession *waldoSession; // @synthesize waldoSession=_waldoSession;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *waldoTimerSource; // @synthesize waldoTimerSource=_waldoTimerSource;
@property _Bool waldoTimerSet; // @synthesize waldoTimerSet=_waldoTimerSet;
@property(retain) NSDictionary *waldoReply; // @synthesize waldoReply=_waldoReply;
- (void).cxx_destruct;
- (void)fellbackToCellular;
@property(readonly) NSArray *edges;
- (void)cancel;
- (void)start;
- (void)fetchURL;
- (void)handleResponse:(id)arg1 error:(id)arg2;
- (void)startTimer;
- (_Bool)verifyDictionary:(id)arg1;
- (void)dealloc;
- (id)init;

@end

