
/Applications/Xcode.app//Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/system/libsystem_coreservices.dylib (for architecture armv7):
_NSGetNextSearchPathEnumeration
_NSStartSearchPathEnumeration
___coreservicesVersionNumber
___coreservicesVersionString
___dirhelper_create_user_local
___dirhelper_idle_exit
___user_local_dirname
___user_local_mkdir_p
__dirhelper
__libcoreservices_fork_child

/Applications/Xcode.app//Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/system/libsystem_coreservices.dylib (for architecture armv7s):
_NSGetNextSearchPathEnumeration
_NSStartSearchPathEnumeration
___coreservicesVersionNumber
___coreservicesVersionString
___dirhelper_create_user_local
___dirhelper_idle_exit
___user_local_dirname
___user_local_mkdir_p
__dirhelper
__libcoreservices_fork_child

/Applications/Xcode.app//Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/system/libsystem_coreservices.dylib (for architecture arm64):
_NSGetNextSearchPathEnumeration
_NSStartSearchPathEnumeration
___coreservicesVersionNumber
___coreservicesVersionString
___dirhelper_create_user_local
___dirhelper_idle_exit
___user_local_dirname
___user_local_mkdir_p
__dirhelper
__libcoreservices_fork_child
