//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CAAnimation.h"

@class NSImage;

@interface CAAnimation (SceneKit_SKEAdditions)
- (id)ide_displayName;
@property(readonly) NSImage *ide_icon;
@end

