//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IDEInspectorProperty.h"

@class DVTStepperTextField, IDEInspectorKeyPath, NSString, NSTextField;

@interface SKEInspectorVector4Property : IDEInspectorProperty
{
    DVTStepperTextField *_xScrubber;
    DVTStepperTextField *_yScrubber;
    DVTStepperTextField *_zScrubber;
    DVTStepperTextField *_wScrubber;
    NSTextField *_xLabel;
    NSTextField *_yLabel;
    NSTextField *_zLabel;
    NSTextField *_wLabel;
    IDEInspectorKeyPath *_valueKeyPath;
    NSString *_nilPlaceholder;
}

- (void).cxx_destruct;
- (void)setupRefreshTriggersAndConfigure;
- (void)refresh;
- (void)userDidChangeValue:(id)arg1;
- (CDUnknownBlockType)vectorComponentSetter:(long long)arg1 componentValue:(double)arg2;
- (CDUnknownBlockType)vectorComponentExtractor:(long long)arg1;
- (double)baseline;

@end

