
/Applications/Xcode.app//Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/system/libremovefile.dylib (for architecture armv7):
___removefileVersionNumber
___removefileVersionString
___removefile_init_random
___removefile_process_file
___removefile_random_char
___removefile_randomize_buffer
___removefile_rename_unlink
___removefile_sunlink
___removefile_tree_walker
_removefile
_removefile_cancel
_removefile_state_alloc
_removefile_state_free
_removefile_state_get
_removefile_state_set

/Applications/Xcode.app//Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/system/libremovefile.dylib (for architecture armv7s):
___removefileVersionNumber
___removefileVersionString
___removefile_init_random
___removefile_process_file
___removefile_random_char
___removefile_randomize_buffer
___removefile_rename_unlink
___removefile_sunlink
___removefile_tree_walker
_removefile
_removefile_cancel
_removefile_state_alloc
_removefile_state_free
_removefile_state_get
_removefile_state_set

/Applications/Xcode.app//Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/system/libremovefile.dylib (for architecture arm64):
___removefileVersionNumber
___removefileVersionString
___removefile_init_random
___removefile_process_file
___removefile_random_char
___removefile_randomize_buffer
___removefile_rename_unlink
___removefile_sunlink
___removefile_tree_walker
_removefile
_removefile_cancel
_removefile_state_alloc
_removefile_state_free
_removefile_state_get
_removefile_state_set
