//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSURL;

@protocol ASAssetMetadataUpdatePolicy <NSObject>
- (double)automaticMetadataUpdateIntervalForAssetType:(NSString *)arg1;
- (double)defaultNetworkTimeout;
- (NSURL *)serverURLForAssetType:(NSString *)arg1;
@end

