
/Applications/Xcode.app//Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/libcupolicy.dylib (for architecture armv7):
__ZN30cellular_usage_policy_client_sC1Ev
__ZN30cellular_usage_policy_client_sC2Ev
__ZTINSt3__117bad_function_callE
__ZTSNSt3__117bad_function_callE
_cellular_usage_policy_copy_datausage_blacklist
_cellular_usage_policy_copy_for_bundle
_cellular_usage_policy_copy_for_pid
_cellular_usage_policy_copy_for_uuid
_cellular_usage_policy_copy_uuids_for_bundle
_cellular_usage_policy_create_client
_cellular_usage_policy_destroy_client
_cellular_usage_policy_get_bundle_from_policy
_cellular_usage_policy_get_data_allowed_from_policy
_cellular_usage_policy_get_pid_from_policy
_cellular_usage_policy_get_uuid_from_policy
_cellular_usage_policy_is_data_allowed_for_bundle
_cellular_usage_policy_is_data_allowed_for_pid
_cellular_usage_policy_is_data_allowed_for_uuid
_cellular_usage_policy_set_changed_handler

/Applications/Xcode.app//Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/libcupolicy.dylib (for architecture armv7s):
__ZN30cellular_usage_policy_client_sC1Ev
__ZN30cellular_usage_policy_client_sC2Ev
__ZTINSt3__117bad_function_callE
__ZTSNSt3__117bad_function_callE
_cellular_usage_policy_copy_datausage_blacklist
_cellular_usage_policy_copy_for_bundle
_cellular_usage_policy_copy_for_pid
_cellular_usage_policy_copy_for_uuid
_cellular_usage_policy_copy_uuids_for_bundle
_cellular_usage_policy_create_client
_cellular_usage_policy_destroy_client
_cellular_usage_policy_get_bundle_from_policy
_cellular_usage_policy_get_data_allowed_from_policy
_cellular_usage_policy_get_pid_from_policy
_cellular_usage_policy_get_uuid_from_policy
_cellular_usage_policy_is_data_allowed_for_bundle
_cellular_usage_policy_is_data_allowed_for_pid
_cellular_usage_policy_is_data_allowed_for_uuid
_cellular_usage_policy_set_changed_handler

/Applications/Xcode.app//Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/libcupolicy.dylib (for architecture arm64):
__ZN30cellular_usage_policy_client_sC1Ev
__ZN30cellular_usage_policy_client_sC2Ev
_cellular_usage_policy_copy_datausage_blacklist
_cellular_usage_policy_copy_for_bundle
_cellular_usage_policy_copy_for_pid
_cellular_usage_policy_copy_for_uuid
_cellular_usage_policy_copy_uuids_for_bundle
_cellular_usage_policy_create_client
_cellular_usage_policy_destroy_client
_cellular_usage_policy_get_bundle_from_policy
_cellular_usage_policy_get_data_allowed_from_policy
_cellular_usage_policy_get_pid_from_policy
_cellular_usage_policy_get_uuid_from_policy
_cellular_usage_policy_is_data_allowed_for_bundle
_cellular_usage_policy_is_data_allowed_for_pid
_cellular_usage_policy_is_data_allowed_for_uuid
_cellular_usage_policy_set_changed_handler
