//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSMutableString.h"

@interface NSMutableString (Xcode3ProjectTemplateDefinitionNodeAdditions)
- (void)appendNonEmptyString:(id)arg1 indenting:(long long)arg2 withString:(id)arg3 wildcardString:(id)arg4;
@end

