//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DVTSourceExpression, NSArray, NSString, Xcode3ProjectEditor;

@protocol Xcode3SourceListItemEditor <NSObject>
+ (NSString *)localizedSourceListItemEditorName;
+ (BOOL)canInspectBlueprint:(id)arg1;
@property(retain) Xcode3ProjectEditor *projectEditor;

@optional
@property(readonly, nonatomic) DVTSourceExpression *mouseOverExpression;
@property(readonly) struct CGRect currentSelectionFrame;
@property(readonly, nonatomic) DVTSourceExpression *selectedExpression;
@property(retain, nonatomic) id inspectedBlueprint;
@property(copy, nonatomic) NSArray *inspectedBlueprints;
- (NSString *)titleKeyPathForToolbarButtonWithIdentifier:(NSString *)arg1;
- (SEL)menuSourceSelectorForToolbarButtonWithIdentifier:(NSString *)arg1;
- (NSArray *)supportedToolbarButtonIdentifiers;
- (void)selectLocations:(NSArray *)arg1;
- (NSArray *)currentSelectedLocations;
@end

