
/Applications/Xcode.app//Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/libGestureServer.dylib (for architecture armv7):
_OBJC_CLASS_$__UIGestureRecognizerContextState
_OBJC_CLASS_$__UIGestureRecognizerServer
_OBJC_IVAR_$__UIGestureRecognizerContextState._ancestorContextId
_OBJC_IVAR_$__UIGestureRecognizerContextState._ancestorDidReset
_OBJC_IVAR_$__UIGestureRecognizerContextState._ancestorGestureRecognizerState
_OBJC_IVAR_$__UIGestureRecognizerContextState._contextId
_OBJC_IVAR_$__UIGestureRecognizerContextState._didReset
_OBJC_IVAR_$__UIGestureRecognizerContextState._gestureRecognizerState
_OBJC_IVAR_$__UIGestureRecognizerContextState._initialTouchTimestamp
_OBJC_IVAR_$__UIGestureRecognizerContextState._lastAncestorTouchTimestamp
_OBJC_IVAR_$__UIGestureRecognizerContextState._lastTouchTimestamp
_OBJC_METACLASS_$__UIGestureRecognizerContextState
_OBJC_METACLASS_$__UIGestureRecognizerServer
_kUIGestureServerResetTimeoutDuration

/Applications/Xcode.app//Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/libGestureServer.dylib (for architecture armv7s):
_OBJC_CLASS_$__UIGestureRecognizerContextState
_OBJC_CLASS_$__UIGestureRecognizerServer
_OBJC_IVAR_$__UIGestureRecognizerContextState._ancestorContextId
_OBJC_IVAR_$__UIGestureRecognizerContextState._ancestorDidReset
_OBJC_IVAR_$__UIGestureRecognizerContextState._ancestorGestureRecognizerState
_OBJC_IVAR_$__UIGestureRecognizerContextState._contextId
_OBJC_IVAR_$__UIGestureRecognizerContextState._didReset
_OBJC_IVAR_$__UIGestureRecognizerContextState._gestureRecognizerState
_OBJC_IVAR_$__UIGestureRecognizerContextState._initialTouchTimestamp
_OBJC_IVAR_$__UIGestureRecognizerContextState._lastAncestorTouchTimestamp
_OBJC_IVAR_$__UIGestureRecognizerContextState._lastTouchTimestamp
_OBJC_METACLASS_$__UIGestureRecognizerContextState
_OBJC_METACLASS_$__UIGestureRecognizerServer
_kUIGestureServerResetTimeoutDuration

/Applications/Xcode.app//Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/libGestureServer.dylib (for architecture arm64):
_OBJC_CLASS_$__UIGestureRecognizerContextState
_OBJC_CLASS_$__UIGestureRecognizerServer
_OBJC_IVAR_$__UIGestureRecognizerContextState._ancestorContextId
_OBJC_IVAR_$__UIGestureRecognizerContextState._ancestorDidReset
_OBJC_IVAR_$__UIGestureRecognizerContextState._ancestorGestureRecognizerState
_OBJC_IVAR_$__UIGestureRecognizerContextState._contextId
_OBJC_IVAR_$__UIGestureRecognizerContextState._didReset
_OBJC_IVAR_$__UIGestureRecognizerContextState._gestureRecognizerState
_OBJC_IVAR_$__UIGestureRecognizerContextState._initialTouchTimestamp
_OBJC_IVAR_$__UIGestureRecognizerContextState._lastAncestorTouchTimestamp
_OBJC_IVAR_$__UIGestureRecognizerContextState._lastTouchTimestamp
_OBJC_METACLASS_$__UIGestureRecognizerContextState
_OBJC_METACLASS_$__UIGestureRecognizerServer
_kUIGestureServerResetTimeoutDuration
