//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface MZMD5Operation : NSObject
{
    unsigned long long _analyzed;
    NSString *_file;
    BOOL _cancelled;
}

+ (id)operationWthFile:(id)arg1;
+ (id)operation;
+ (id)md5ForString:(id)arg1 encoding:(unsigned long long)arg2 error:(id *)arg3;
+ (id)md5ForStream:(id)arg1 error:(id *)arg2;
+ (id)md5ForData:(id)arg1 error:(id *)arg2;
+ (id)md5ForFilename:(id)arg1 error:(id *)arg2;
@property(copy) NSString *file; // @synthesize file=_file;
- (id)computeMD5WithError:(id *)arg1;
- (id)computeMD5WithStream:(id)arg1 error:(id *)arg2;
- (void)cancel;
@property unsigned long long bytesAnalyzed;
- (void)dealloc;
- (id)initWithFile:(id)arg1;
- (id)init;

@end

