//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface MZSecurityKeychain : NSObject
{
    struct OpaqueSecKeychainRef *_keychain;
    NSString *_path;
}

+ (id)defaultKeychain;
- (id)allGenericPasswordEntriesWithError:(id *)arg1;
- (id)removeGenericPasswordForServiceName:(id)arg1 accountName:(id)arg2;
- (id)removeGenericPasswordForServiceName:(id)arg1;
- (id)setGenericPassword:(id)arg1 forServiceName:(id)arg2 accountName:(id)arg3;
- (id)genericPasswordForServiceName:(id)arg1 accountName:(id)arg2 error:(id *)arg3;
- (id)setGenericPassword:(id)arg1 forServiceName:(id)arg2;
- (id)genericPasswordForServiceName:(id)arg1 error:(id *)arg2;
- (void)dealloc;
- (id)initWithPath:(id)arg1 error:(id *)arg2;
- (id)initWithKeychain:(struct OpaqueSecKeychainRef *)arg1;

@end

