//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSError, NSNumber, NSString;

@interface MZToolExecutorResult : NSObject
{
    unsigned long long _outputEncoding;
    NSString *_commandString;
    NSData *_standardOutput;
    NSData *_standardError;
    NSNumber *_errorCode;
    NSError *_error;
}

+ (id)resultWithTask:(id)arg1;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(retain, nonatomic) NSNumber *errorCode; // @synthesize errorCode=_errorCode;
@property(retain, nonatomic) NSData *standardError; // @synthesize standardError=_standardError;
@property(retain, nonatomic) NSData *standardOutput; // @synthesize standardOutput=_standardOutput;
@property(retain, nonatomic) NSString *commandString; // @synthesize commandString=_commandString;
@property(nonatomic) unsigned long long outputEncoding; // @synthesize outputEncoding=_outputEncoding;
- (id)describeAsPlist;
- (id)errorCodeString;
- (id)standardErrorString;
- (id)standardOutputString;
- (void)dealloc;
- (id)initWithTask:(id)arg1;

@end

