//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ITunesConnectFoundation/MZITunesProducerServiceClient.h>

@class MZLookupMetadataSubItemInfo, NSArray, NSString;

@interface MZWebServiceLookupMetadata : MZITunesProducerServiceClient
{
    NSString *_vendorId;
    NSString *_appleId;
    NSString *_genericId;
    NSArray *_knownVersions;
    BOOL _encodingMetadata;
    MZLookupMetadataSubItemInfo *_subItemInfo;
    NSString *_metadata;
    BOOL _coverArtFixDisabled;
}

+ (int)maxNumberOfIapsAllowedForLookup;
+ (void)initialize;
- (BOOL)hasTooManySubItemsErrorMessage;
- (BOOL)isCoverArtFixDisabled;
- (id)metadata;
- (id)subItemInfo;
- (void)setSubItemInfo:(id)arg1;
- (BOOL)isEncodingMetadata;
- (void)setEncodingMetadata:(BOOL)arg1;
- (id)knownVersions;
- (void)setKnownVersions:(id)arg1;
- (id)vendorId;
- (void)setVendorId:(id)arg1;
- (id)appleId;
- (void)setAppleId:(id)arg1;
- (id)genericId;
- (void)setGenericId:(id)arg1;
- (id)processUncancelledSuccessfulResult:(id)arg1;
- (id)decodeMetadata:(id)arg1 error:(id *)arg2;
- (void)operationWillStart;
- (id)completedMessage;
- (id)runningMessage;
- (id)initialMessage;
- (id)operationMethod;
- (id)generateArguments;
- (void)dealloc;
- (id)init;

@end

